#!/usr/bin/env python3
"""Generate EN overlay JSON files for Italy Level 3 lessons."""
import json, os

BASE = os.path.join(os.path.dirname(__file__), "..", "src", "locales", "en", "lessons", "italy")
os.makedirs(BASE, exist_ok=True)

def write(filename, data):
    path = os.path.join(BASE, filename)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"Created {filename}")

# ─── L3M1L1 Rare Northern Varieties ──────────────────────────────────────────
write("L3M1L1.json", {
  "title": "Northern Italy's Rare Variety Treasures",
  "slides.0.title": "💎 Northern Italy's Rare Variety Treasures",
  "slides.1.title": "⭐ Timorasso — Piemonte's White Wine Legend",
  "slides.2.title": "🌸 Ruché — Queen of Aromatics",
  "slides.3.title": "🍷 Freisa — Ancient Piemontese Red",
  "slides.4.title": "📊 Three Rare Varieties Compared",
  "slides.5.title": "🏰 Top Producers",
  "slides.6.title": "🍽️ Expert Food Pairings",
  "slides.7.title": "🎓 Key Takeaways",
  "slides.8.title": "🧠 Northern Italian Rare Varieties Knowledge Check",
  "quiz.0.question": "Who is credited as the pioneer of Timorasso's revival?",
  "quiz.0.options.0": "Bruno Giacosa",
  "quiz.0.options.1": "Walter Massa",
  "quiz.0.options.2": "Angelo Gaja",
  "quiz.0.options.3": "Giacomo Conterno",
  "quiz.0.explanation": "Walter Massa of Monleale single-handedly revived Timorasso in the 1980s–90s, transforming it from a nearly extinct variety into one of Piemonte's most sought-after white wines.",
  "quiz.1.question": "What is Ruché's most distinctive flavour characteristic?",
  "quiz.1.options.0": "Intense blackberry and tobacco",
  "quiz.1.options.1": "Unique combination of rose petals, geranium, white pepper and exotic spice",
  "quiz.1.options.2": "Fresh citrus and mineral character",
  "quiz.1.options.3": "Deep, tannic structure like Barolo",
  "quiz.1.explanation": "Ruché di Castagnole Monferrato DOCG is unlike any other Italian red — its extraordinary aromatic profile of rose, geranium and exotic spices makes it instantly recognisable.",
  "quiz.2.question": "How many different styles can Freisa be produced in?",
  "quiz.2.options.0": "Only one — still dry red",
  "quiz.2.options.1": "Three: dry still, sweet (amabile), and lightly sparkling (frizzante)",
  "quiz.2.options.2": "Only sparkling",
  "quiz.2.options.3": "Two: dry and sweet",
  "quiz.2.explanation": "Freisa is remarkably versatile — it can be made as a dry still red, a gently sweet (amabile) version or a lightly sparkling (frizzante) wine — all with its characteristic raspberry and tar character.",
  "quiz.3.question": "What is Timorasso's typical ageing potential?",
  "quiz.3.options.0": "1–2 years",
  "quiz.3.options.1": "10–20 years for top examples",
  "quiz.3.options.2": "5 years maximum",
  "quiz.3.options.3": "30+ years",
  "quiz.3.explanation": "Top Timorasso (Colli Tortonesi DOC) can age for 10–20 years, developing a remarkable mineral, petrolly complexity similar to great aged Riesling — extraordinary for a Piemontese white."
})

# ─── L3M1L2 Rare Central Italian Varieties ────────────────────────────────────
write("L3M1L2.json", {
  "title": "Central Italy's Rare Varieties",
  "slides.0.title": "🍒 Central Italy's Rare Varieties",
  "slides.1.title": "🍒 Ciliegiolo — The Cherry Wine",
  "slides.2.title": "🏛️ Cesanese — Rome's Ancient Heritage",
  "slides.3.title": "📊 Two Varieties Compared",
  "slides.4.title": "🏰 Top Producer Recommendations",
  "slides.5.title": "🍽️ Expert Food Pairing Guide",
  "slides.6.title": "📈 Market Insights and Investment Advice",
  "slides.7.title": "🎓 Expert Key Takeaways",
  "slides.8.title": "🧠 Northern Italian Special Varieties Knowledge Check",
  "quiz.0.question": "What is the origin of the name Ciliegiolo?",
  "quiz.0.options.0": "Named after a winemaker called Ciliegio",
  "quiz.0.options.1": "From 'ciliegia' (cherry in Italian) — the variety's defining cherry fruit character",
  "quiz.0.options.2": "Named after the village of Ciliegiolo",
  "quiz.0.options.3": "From a Latin term meaning 'small vineyard'",
  "quiz.0.explanation": "Ciliegiolo means 'cherry-flavoured' in Italian — named for the grape's intense, vivid cherry aroma that is its most distinctive and defining characteristic.",
  "quiz.1.question": "Which ancient Roman writer mentioned the Cesanese grape in their writings?",
  "quiz.1.options.0": "Julius Caesar",
  "quiz.1.options.1": "Pliny the Elder",
  "quiz.1.options.2": "Virgil",
  "quiz.1.options.3": "Cicero",
  "quiz.1.explanation": "Pliny the Elder (AD 23–79) mentioned a grape variety in the area around modern Lazio that scholars believe to be an ancestor of today's Cesanese — making it one of ancient Rome's documented wine grapes.",
  "quiz.2.question": "In what year did Cesanese del Piglio achieve DOCG status?",
  "quiz.2.options.0": "1999",
  "quiz.2.options.1": "2008",
  "quiz.2.options.2": "2015",
  "quiz.2.options.3": "2021",
  "quiz.2.explanation": "Cesanese del Piglio was elevated to DOCG status in 2008 — the first red wine DOCG in Lazio, recognising the variety's unique character and quality potential.",
  "quiz.3.question": "Which winery is considered a standard-bearer for Ciliegiolo natural wine?",
  "quiz.3.options.0": "Valentini",
  "quiz.3.options.1": "Sassotondo",
  "quiz.3.options.2": "Biondi-Santi",
  "quiz.3.options.3": "Lungarotti",
  "quiz.3.explanation": "Sassotondo in the Maremma (Tuscany) is widely considered the reference producer for serious, natural-style Ciliegiolo — making wines of striking purity and red-fruit character."
})

# ─── L3M1L3 Southern Italian Native Varieties ─────────────────────────────────
write("L3M1L3.json", {
  "title": "Southern Italy's Native Variety Treasury",
  "slides.0.title": "🌋 Southern Italy's Native Variety Treasury",
  "slides.1.title": "🌋 Aglianico del Vulture — King of the Volcano",
  "slides.2.title": "⭐ Greco di Tufo — The White Legend",
  "slides.3.title": "🌸 Fiano di Avellino — Queen of Aromatics",
  "slides.4.title": "💪 Primitivo di Manduria — Power of Puglia",
  "slides.5.title": "📊 Four Southern Varieties — Full Comparison",
  "slides.6.title": "🏰 Top Producer Guide",
  "slides.7.title": "🍽️ Southern Italian Terroir Food Pairings",
  "slides.8.title": "🎓 Expert Key Takeaways",
  "slides.9.title": "🧠 Southern Italian Rare Varieties Knowledge Check",
  "quiz.0.question": "Why is Aglianico del Vulture called 'the Barolo of the South'?",
  "quiz.0.options.0": "It uses the same Nebbiolo grape",
  "quiz.0.options.1": "Like Barolo, it is a late-ripening, volcanic-terroir, powerfully tannic wine with extraordinary ageing potential",
  "quiz.0.options.2": "It is aged in the same type of oak barrels as Barolo",
  "quiz.0.options.3": "It comes from the same latitude as Barolo",
  "quiz.0.explanation": "Aglianico del Vulture earns its 'Barolo of the South' nickname through its late ripening (often October), volcanic soil origin, massive tannic structure and capacity to age for decades.",
  "quiz.1.question": "What does the 'Tufo' in Greco di Tufo refer to?",
  "quiz.1.options.0": "An ancient Roman fortress",
  "quiz.1.options.1": "The tufa volcanic rock underlying the vineyard soils",
  "quiz.1.options.2": "The name of the village's founder",
  "quiz.1.options.3": "A type of barrel used for ageing",
  "quiz.1.explanation": "Tufo refers to the sulphurous tufaceous volcanic soil of the Irpinia hills — the ancient volcanic substrate that gives Greco di Tufo its distinctive mineral and flint-like character.",
  "quiz.2.question": "Which variety is genetically identical to Primitivo?",
  "quiz.2.options.0": "Grenache",
  "quiz.2.options.1": "Zinfandel (and the original Croatian Crljenak Kaštelanski)",
  "quiz.2.options.2": "Nero d'Avola",
  "quiz.2.options.3": "Negroamaro",
  "quiz.2.explanation": "DNA profiling confirmed that Primitivo, Californian Zinfandel and Croatian Crljenak Kaštelanski are genetically the same variety — one of the most celebrated genetic revelations in wine history.",
  "quiz.3.question": "Which producer is the biodynamic reference estate for Aglianico del Vulture?",
  "quiz.3.options.0": "Feudi di San Gregorio",
  "quiz.3.options.1": "Elena Fucci",
  "quiz.3.options.2": "Mastroberardino",
  "quiz.3.options.3": "Paternoster",
  "quiz.3.explanation": "Elena Fucci's Titolo vineyard on Monte Vulture is considered Aglianico del Vulture's most celebrated biodynamic estate — producing concentrated, mineral wines of extraordinary precision."
})

# ─── L3M1L4 Hidden Gem Appellations ───────────────────────────────────────────
write("L3M1L4.json", {
  "title": "Hidden Gem Appellations",
  "slides.0.title": "💎 Hidden Gem Appellations",
  "slides.1.title": "📜 Alto Piemonte — Historical Changes",
  "slides.2.title": "🏔️ Carema DOC — Alpine Nebbiolo",
  "slides.3.title": "👑 Gattinara DOCG — The Forgotten Great",
  "slides.4.title": "🔍 Boca DOC — Rare Among the Rare",
  "slides.5.title": "📊 Three Appellations Compared",
  "slides.6.title": "🍽️ Food Pairings and Service",
  "slides.7.title": "📈 Investment and Collecting Advice",
  "slides.8.title": "🎓 Expert Key Takeaways",
  "slides.9.title": "🧠 Friuli Orange Wine Revolution Knowledge Check",
  "quiz.0.question": "What was the vineyard area of Alto Piemonte at the end of the 19th century?",
  "quiz.0.options.0": "~3,000 hectares",
  "quiz.0.options.1": "~40,000 hectares",
  "quiz.0.options.2": "~10,000 hectares",
  "quiz.0.options.3": "~100,000 hectares",
  "quiz.0.explanation": "In the late 19th century, Alto Piemonte had approximately 40,000 hectares of vineyards — today reduced to under 500 ha after phylloxera, world wars and rural depopulation.",
  "quiz.1.question": "What unique vine-training system does Carema use?",
  "quiz.1.options.0": "Guyot (single curtain)",
  "quiz.1.options.1": "Toppia — stone pillar pergola system",
  "quiz.1.options.2": "Alberello (bush vine)",
  "quiz.1.options.3": "Double Guyot",
  "quiz.1.explanation": "Carema's traditional Toppia system uses stone or concrete pillars supporting a pergola — the vines trained horizontally to maximise heat absorption in this cool Alpine environment.",
  "quiz.2.question": "What is the volcanic rock in Gattinara's soils?",
  "quiz.2.options.0": "Limestone",
  "quiz.2.options.1": "Porphyry (reddish volcanic rock with granite-like mineral complexity)",
  "quiz.2.options.2": "Basalt",
  "quiz.2.options.3": "Tufa",
  "quiz.2.explanation": "Gattinara is underlain by porphyry — an ancient, iron-rich reddish volcanic rock — that contributes to the wine's distinctive mineral character and perfumed, iron-like complexity.",
  "quiz.3.question": "What is the total vineyard area of Boca DOC?",
  "quiz.3.options.0": "~5,000 hectares",
  "quiz.3.options.1": "~30–50 hectares",
  "quiz.3.options.2": "~500 hectares",
  "quiz.3.options.3": "~2,000 hectares",
  "quiz.3.explanation": "Boca DOC has only around 30–50 hectares of vineyards — one of Italy's smallest appellations. Its rarity, coupled with exceptional quality from committed producers, makes it a true collector's appellation."
})

# ─── L3M2L1 MGA and Cru System ────────────────────────────────────────────────
write("L3M2L1.json", {
  "title": "MGA and the Cru System — A Complete Guide",
  "slides.0.title": "🗺️ MGA and the Cru System — A Complete Guide",
  "slides.1.title": "📚 What is MGA?",
  "slides.2.title": "🏘️ Barolo's 11 Villages and MGA Distribution",
  "slides.3.title": "⭐ Barolo's Legendary MGAs — Deep Dive",
  "slides.4.title": "🍇 Barbaresco's Cru System",
  "slides.5.title": "🏷️ How to Read an MGA Wine Label",
  "slides.6.title": "🎓 Expert Key Takeaways",
  "slides.7.title": "🧠 MGA and Cru Knowledge Check",
  "quiz.0.question": "In what year was Barolo's MGA system officially implemented?",
  "quiz.0.options.0": "1980",
  "quiz.0.options.1": "2010",
  "quiz.0.options.2": "2000",
  "quiz.0.options.3": "2024",
  "quiz.0.explanation": "The Barolo MGA (Menzioni Geografiche Aggiuntive — Additional Geographic Mentions) system was formally established in 2010, codifying 181 individual vineyard sites across Barolo's 11 communes.",
  "quiz.1.question": "Giacomo Conterno's legendary Monfortino wine actually comes from which MGA?",
  "quiz.1.options.0": "Cannubi (Barolo village)",
  "quiz.1.options.1": "Francia (Serralunga d'Alba)",
  "quiz.1.options.2": "Vigna Rionda (Serralunga)",
  "quiz.1.options.3": "Brunate (La Morra)",
  "quiz.1.explanation": "Giacomo Conterno's Monfortino Riserva — often called Italy's greatest red wine — comes from the Francia vineyard in Serralunga d'Alba, a Conterno family-owned MGA.",
  "quiz.2.question": "How many official MGAs does Barbaresco have?",
  "quiz.2.options.0": "66",
  "quiz.2.options.1": "181",
  "quiz.2.options.2": "42",
  "quiz.2.options.3": "250",
  "quiz.2.explanation": "Barbaresco has 66 official MGAs across its three core communes (Barbaresco, Neive and Treiso) — compared with Barolo's 181, reflecting the smaller production zone.",
  "quiz.3.question": "When an MGA name appears on a label, what typographic rule must be followed?",
  "quiz.3.options.0": "The MGA name must appear in italics",
  "quiz.3.options.1": "The MGA name must be no larger than half the font size of the appellation name (Barolo/Barbaresco)",
  "quiz.3.options.2": "The MGA name must appear in red text",
  "quiz.3.options.3": "The MGA name must appear below the vintage",
  "quiz.3.explanation": "Italian labelling rules state that the MGA name must be no more than half the font size of the main appellation name (Barolo or Barbaresco) — to prevent any geographic mention from overshadowing the appellation itself."
})

# ─── L3M2L2 Complete Labelling Terminology Guide ──────────────────────────────
write("L3M2L2.json", {
  "title": "Complete Labelling Terminology Guide",
  "slides.0.title": "🏷️ Complete Labelling Terminology Guide",
  "slides.1.title": "⏳ Ageing Terminology Explained",
  "slides.2.title": "🍇 Variety Labelling",
  "slides.3.title": "🗺️ Appellation Terminology — Advanced",
  "slides.4.title": "🫧 Sparkling Wine Terminology",
  "slides.5.title": "🔍 Label Reading Practice",
  "slides.6.title": "🎓 Expert Key Takeaways",
  "slides.7.title": "🧠 Advanced Label Reading Knowledge Check",
  "quiz.0.question": "What is the minimum ageing requirement for Barolo Riserva?",
  "quiz.0.options.0": "2 years",
  "quiz.0.options.1": "5 years (including at least 18 months in oak)",
  "quiz.0.options.2": "3 years",
  "quiz.0.options.3": "7 years",
  "quiz.0.explanation": "Barolo Riserva requires a minimum 5 years' total ageing from harvest (including at least 18 months in oak) — the standard Barolo requires 3 years.",
  "quiz.1.question": "What does the term 'Superiore' primarily indicate?",
  "quiz.1.options.0": "Sweeter than standard",
  "quiz.1.options.1": "Higher minimum alcohol and/or longer ageing than the base appellation requirement",
  "quiz.1.options.2": "Produced from a single vineyard",
  "quiz.1.options.3": "A sparkling wine style",
  "quiz.1.explanation": "'Superiore' in Italian wine denotes a higher standard — usually higher minimum alcohol, lower yields and/or additional ageing — over the base DOC standard.",
  "quiz.2.question": "In sparkling wine terminology, which term is sweeter than Brut?",
  "quiz.2.options.0": "Extra Brut",
  "quiz.2.options.1": "Extra Dry",
  "quiz.2.options.2": "Brut Nature",
  "quiz.2.options.3": "Pas Dosé",
  "quiz.2.explanation": "The sweetness scale from driest to sweetest: Brut Nature/Pas Dosé → Extra Brut → Brut → Extra Dry → Dry/Sec → Demi-Sec → Doux. 'Extra Dry' is paradoxically sweeter than 'Brut'.",
  "quiz.3.question": "Chianti Classico Gran Selezione requires the grapes to come from where?",
  "quiz.3.options.0": "Any vineyard in Tuscany",
  "quiz.3.options.1": "A single, estate-owned vineyard (single vineyard or single selection)",
  "quiz.3.options.2": "Multiple estates blended together",
  "quiz.3.options.3": "Any Chianti Classico DOCG vineyard",
  "quiz.3.explanation": "Chianti Classico Gran Selezione must come from a single vineyard (vigna) selection from the producer's own estate — the most demanding quality tier in the Chianti Classico hierarchy."
})

# ─── L3M2L3 Producer Style Identification ─────────────────────────────────────
write("L3M2L3.json", {
  "title": "Producer Style Identification",
  "slides.0.title": "🎭 Producer Style Identification",
  "slides.1.title": "⚔️ The Barolo Style Wars (1980–2010)",
  "slides.2.title": "🔍 Top Producers — Deep Analysis",
  "slides.3.title": "🍷 How to Identify Style from the Wine",
  "slides.4.title": "🗺️ Style Differences in Other Appellations",
  "slides.5.title": "🎓 Expert Key Takeaways",
  "slides.6.title": "🧠 Fake Wine Identification Knowledge Check",
  "quiz.0.question": "In which decade did the Barolo Boys revolution begin?",
  "quiz.0.options.0": "1970s",
  "quiz.0.options.1": "1980s",
  "quiz.0.options.2": "1990s",
  "quiz.0.options.3": "2000s",
  "quiz.0.explanation": "The Barolo Boys movement emerged in the 1980s — led by Elio Altare, Enrico Scavino and others — who adopted small French barriques, shorter maceration and radical new techniques that split the Barolo world into 'traditionalists' vs 'modernists'.",
  "quiz.1.question": "What type of oak barrel do traditional-style Barolo producers principally use?",
  "quiz.1.options.0": "Small French barriques (225 litres)",
  "quiz.1.options.1": "Large Slavonian or Italian oak casks (botti grandi, 25–50 hl+)",
  "quiz.1.options.2": "New American oak barrels",
  "quiz.1.options.3": "Acacia barrels",
  "quiz.1.explanation": "Traditionalists use large Slavonian (or Italian) oak botti (2,500–5,000+ litres), ageing the wine for 3–5+ years — imparting minimal oak flavour while slowly refining the tannins.",
  "quiz.2.question": "Giacomo Conterno's Monfortino grapes come from which MGA?",
  "quiz.2.options.0": "Cannubi (Barolo)",
  "quiz.2.options.1": "Francia (Serralunga d'Alba)",
  "quiz.2.options.2": "Vigna Rionda (Serralunga)",
  "quiz.2.options.3": "Brunate (La Morra)",
  "quiz.2.explanation": "Monfortino Riserva — Giacomo Conterno's greatest wine — comes exclusively from the Francia vineyard in Serralunga d'Alba, owned by the Conterno family.",
  "quiz.3.question": "In blind tasting, how can you quickly distinguish traditional from modern Barolo?",
  "quiz.3.options.0": "Modern Barolo always has higher alcohol",
  "quiz.3.options.1": "Traditional Barolo: pale, orange-edged colour + tar & roses + austere tannins; Modern: deeper colour + vanilla + rounder, softer tannins",
  "quiz.3.options.2": "Traditional Barolo smells of oak; Modern smells of fruit",
  "quiz.3.options.3": "There is no reliable way to distinguish them blind",
  "quiz.3.explanation": "Traditional Barolo: pale garnet with orange rim, classic tar-roses-dried violet aromas, strict chalky tannins, high acidity, long evolution. Modern Barolo: deeper ruby, vanilla-fruit bouquet, rounder tannins, more immediately approachable."
})

# ─── L3M2L4 Classification System Deep Dive ───────────────────────────────────
write("L3M2L4.json", {
  "title": "Classification System — Deep Dive",
  "slides.0.title": "📊 Classification System — Deep Dive",
  "slides.1.title": "📜 Historical Evolution of Italy's Classification System",
  "slides.2.title": "🏆 DOCG — Deep Analysis",
  "slides.3.title": "⚖️ DOC vs DOCG: Key Differences",
  "slides.4.title": "🌍 International Classification Comparison",
  "slides.5.title": "🛒 Practical Consumer Guide",
  "slides.6.title": "🎓 Expert Key Takeaways",
  "slides.7.title": "🧠 Super Tuscan Knowledge Check",
  "quiz.0.question": "In what year was the DOCG system established?",
  "quiz.0.options.0": "1963",
  "quiz.0.options.1": "1980",
  "quiz.0.options.2": "1992",
  "quiz.0.options.3": "2009",
  "quiz.0.explanation": "The DOCG (Denominazione di Origine Controllata e Garantita) system was officially established by Decree in 1980, with Brunello di Montalcino, Barolo, Barbaresco, Vino Nobile di Montepulciano and Chianti among the first wines designated.",
  "quiz.1.question": "What is the most significant difference between DOCG and DOC?",
  "quiz.1.options.0": "DOCG wines are always more expensive",
  "quiz.1.options.1": "DOCG requires official government tasting panels to approve every batch before release; DOC does not",
  "quiz.1.options.2": "DOCG allows more grape varieties in the blend",
  "quiz.1.options.3": "DOC wines can be exported; DOCG cannot",
  "quiz.1.explanation": "The key difference: all DOCG wines must pass a government-appointed tasting commission (commissione di degustazione) before they can be released — adding a layer of quality control absent from DOC.",
  "quiz.2.question": "What unique physical feature must appear on a DOCG wine label?",
  "quiz.2.options.0": "A holographic sticker",
  "quiz.2.options.1": "A numbered government seal (fascia) across the bottle neck/cap",
  "quiz.2.options.2": "A QR code linking to the producer's website",
  "quiz.2.options.3": "The government taster's signature",
  "quiz.2.explanation": "Every DOCG bottle must carry a numbered government seal (fascia or contrassegno) affixed across the cap or cork — guaranteeing the wine has passed inspection. Each seal is unique and traceable.",
  "quiz.3.question": "As of 2024, how many DOCGs does Italy have?",
  "quiz.3.options.0": "77",
  "quiz.3.options.1": "77",
  "quiz.3.options.2": "46",
  "quiz.3.options.3": "120",
  "quiz.3.explanation": "As of 2024, Italy has 77 DOCGs and 341 DOCs — the most complex appellation system of any wine-producing country, reflecting Italy's extraordinary diversity of regions and grape varieties."
})

# ─── L3M3L1 Barolo Vintage Guide ──────────────────────────────────────────────
write("L3M3L1.json", {
  "title": "Barolo Vintage Guide",
  "slides.0.title": "📅 Barolo Vintage Guide",
  "slides.1.title": "❓ Why Vintages Matter So Much in Barolo",
  "slides.2.title": "🌡️ Key Factors Influencing Barolo Vintage Quality",
  "slides.3.title": "⭐ 2000–2024 Barolo Vintage Ratings and Profiles",
  "slides.4.title": "⚖️ 2016 vs 2013: Comparing Two Great Vintages",
  "slides.5.title": "🗺️ Village-by-Village Vintage Variation",
  "slides.6.title": "🛒 Vintage Purchasing Strategy",
  "slides.7.title": "🎓 Summary: Mastering Barolo Vintages",
  "slides.8.title": "🧠 Italian Vintage Assessment Knowledge Check",
  "quiz.0.question": "At which point does weather most critically affect Barolo vintage quality?",
  "quiz.0.options.0": "Bud break in April",
  "quiz.0.options.1": "Late summer ripening (August–September) and harvest timing",
  "quiz.0.options.2": "Winter rainfall levels",
  "quiz.0.options.3": "Spring frost frequency",
  "quiz.0.explanation": "Nebbiolo ripens very late (often October). The critical window is late August through harvest — heat accumulation, rain during harvest and temperature swings during final maturation determine the vintage's character.",
  "quiz.1.question": "What is the main stylistic difference between the great 2016 and 2013 vintages?",
  "quiz.1.options.0": "2013 has higher alcohol than 2016",
  "quiz.1.options.1": "2016 is more classical, elegant and age-worthy; 2013 is richer, opulent and approachable earlier",
  "quiz.1.options.2": "2013 is more acidic than 2016",
  "quiz.1.options.3": "2016 was affected by hail and is uneven",
  "quiz.1.explanation": "2016 is the more 'classic' Barolo — perfect Nebbiolo structure with razor-sharp acidity and iron tannins built for 30+ years. 2013 is equally superb but riper and more immediately seductive.",
  "quiz.2.question": "In a difficult vintage, which Barolo village should you prioritise?",
  "quiz.2.options.0": "La Morra (lowest elevation, warmest)",
  "quiz.2.options.1": "Castiglione Falletto or Serralunga (higher elevation, better drainage)",
  "quiz.2.options.2": "All villages perform equally in difficult vintages",
  "quiz.2.options.3": "Verduno (northernmost, coolest)",
  "quiz.2.explanation": "In rain-challenged vintages, the well-drained, higher-elevation communes (Castiglione Falletto, Serralunga d'Alba) tend to outperform lower-lying, heavier-soil La Morra and Barolo village.",
  "quiz.3.question": "Which Barolo vintage purchasing strategy is most sensible?",
  "quiz.3.options.0": "Always buy the most recent vintage",
  "quiz.3.options.1": "Buy top vintages (2016, 2013, 2010) on release or early, then cellar for 10–20 years",
  "quiz.3.options.2": "Only buy Riserva wines",
  "quiz.3.options.3": "Buy only from one village for consistency",
  "quiz.3.explanation": "The classic strategy: buy great vintages (2010, 2013, 2016, 2019) on release while they are still available at producer prices, then cellar. Great Barolo typically needs 10–15 years and can last 30–40 years."
})

# ─── L3M3L2 Brunello & Chianti Classico Vintage Analysis ──────────────────────
write("L3M3L2.json", {
  "title": "Brunello & Chianti Classico Vintage Analysis",
  "slides.0.title": "🍷 Brunello & Chianti Classico Vintage Analysis",
  "slides.1.title": "⚖️ Brunello vs Chianti Classico: Why Vintages Differ",
  "slides.2.title": "⭐ Brunello Vintage Ratings 2000–2021",
  "slides.3.title": "📊 Chianti Classico Vintage Ratings 2000–2021",
  "slides.4.title": "🔍 Special Vintages Deep Dive: 2015 vs 2016",
  "slides.5.title": "🗺️ Sub-Zone and Vintage Matching Strategy",
  "slides.6.title": "🎓 Summary: Mastering Tuscan Vintages",
  "slides.7.title": "🧠 Ageing and Cellaring Knowledge Check",
  "quiz.0.question": "What is the main reason Brunello and Chianti Classico have different vintage sensitivity?",
  "quiz.0.options.0": "They use different grape varieties",
  "quiz.0.options.1": "Montalcino's higher elevation and drier climate make it more consistent; Chianti Classico's larger, more varied zone creates greater variation",
  "quiz.0.options.2": "Brunello has longer minimum ageing requirements",
  "quiz.0.options.3": "Chianti Classico uses many different grape varieties",
  "quiz.0.explanation": "Montalcino sits at higher elevations with a more consistently warm, dry microclimate — producing great vintages more reliably than the larger, more topographically diverse Chianti Classico zone.",
  "quiz.1.question": "What is the key stylistic difference between the great 2015 and 2016 vintages?",
  "quiz.1.options.0": "2015 is a cool, austere year; 2016 is rich and opulent",
  "quiz.1.options.1": "2015 is richer, more opulent and earlier-maturing; 2016 is more classically structured, higher in acidity and better for long ageing",
  "quiz.1.options.2": "Both vintages are identical in style",
  "quiz.1.options.3": "2016 is a warm vintage; 2015 is a cold vintage",
  "quiz.1.explanation": "In Tuscany: 2015 was a warm year producing rich, plummy, earlier-drinkable wines. 2016 was the more 'perfect' vintage — combining ripeness with natural freshness and structure for maximum ageing.",
  "quiz.2.question": "In a warm Chianti Classico vintage, which sub-zone should you prioritise?",
  "quiz.2.options.0": "Castelnuovo Berardenga (southernmost, warmest)",
  "quiz.2.options.1": "Panzano in Chianti or Radda in Chianti (higher elevation, cooler)",
  "quiz.2.options.2": "All sub-zones perform equally in warm years",
  "quiz.2.options.3": "Greve in Chianti (lower, warmer)",
  "quiz.2.explanation": "In warm, ripe vintages, look to Chianti Classico's cooler higher-altitude sub-zones — Panzano, Radda in Chianti, Gaiole — where natural acidity is preserved better.",
  "quiz.3.question": "Which vintage purchasing strategy is most sensible for Tuscan wines?",
  "quiz.3.options.0": "Only buy Brunello di Montalcino",
  "quiz.3.options.1": "Buy great vintages (2010, 2015, 2016) on release, then cellar — especially Brunello Riserva",
  "quiz.3.options.2": "Always buy the most recent vintage",
  "quiz.3.options.3": "Avoid Chianti Classico — it does not age",
  "quiz.3.explanation": "The same principle as Barolo: secure great vintages on release, cellar patiently. Brunello is released after 5 years and needs another 5–15 years. Chianti Classico Gran Selezione also ages superbly in great vintages."
})

# ─── L3M3L3 Amarone Ageing Evolution ──────────────────────────────────────────
write("L3M3L3.json", {
  "title": "Amarone Ageing Evolution",
  "slides.0.title": "🍷 Amarone Ageing Evolution",
  "slides.1.title": "🔬 Why Is Amarone So Special? The Science of Appassimento",
  "slides.2.title": "📈 Ageing Evolution: The First Decade (0–10 Years)",
  "slides.3.title": "📊 Ageing Evolution: Second and Third Decades (11–30 Years)",
  "slides.4.title": "🏰 Top Producer Styles and Ageing Characteristics",
  "slides.5.title": "🛒 Amarone Purchasing and Ageing Strategy — Complete Guide",
  "slides.6.title": "🎓 Summary: Mastering the Art of Amarone Ageing",
  "slides.7.title": "🧠 Peak Drinking Window Knowledge Check",
  "quiz.0.question": "During the Appassimento drying process, approximately how much weight do the grapes lose?",
  "quiz.0.options.0": "10–15%",
  "quiz.0.options.1": "30–40%",
  "quiz.0.options.2": "60%+",
  "quiz.0.options.3": "5%",
  "quiz.0.explanation": "Grapes for Amarone are dried on bamboo mats (arele) for 90–120 days, losing approximately 30–40% of their weight through dehydration — concentrating sugars, acids and flavour compounds.",
  "quiz.1.question": "In Amarone's ageing evolution, which phase is considered the 'first peak of drinkability'?",
  "quiz.1.options.0": "0–3 years (immediately after release)",
  "quiz.1.options.1": "7–12 years after harvest",
  "quiz.1.options.2": "20–25 years",
  "quiz.1.options.3": "30+ years",
  "quiz.1.explanation": "Most serious Amarone reaches its first major peak around 7–12 years from the harvest — the tannins have softened, the fruit has integrated with secondary complexity, and the wine shows its first hints of evolved character.",
  "quiz.2.question": "Which description most accurately describes top producer styles?",
  "quiz.2.options.0": "All top producers use the same style",
  "quiz.2.options.1": "Dal Forno Romano produces the most concentrated, extracted style; Quintarelli is the classic, contemplative traditionalist; Allegrini is the modern benchmark",
  "quiz.2.options.2": "Traditional producers are better than modern producers",
  "quiz.2.options.3": "Small producers always make better Amarone than large ones",
  "quiz.2.explanation": "Dal Forno Romano: most concentrated and opulent (longest drying). Quintarelli: the gold standard of classical Amarone — complex, meticulous, multi-year ageing. Allegrini: modern precision and consistency.",
  "quiz.3.question": "Which of the following is the most fatal error in long-term Amarone storage?",
  "quiz.3.options.0": "Storing at 16°C",
  "quiz.3.options.1": "Temperature fluctuation — cycling between hot and cold repeatedly",
  "quiz.3.options.2": "Storing horizontally",
  "quiz.3.options.3": "Storing in the dark",
  "quiz.3.explanation": "Temperature fluctuation is the most destructive factor for wine storage. For a concentrated, long-lived wine like Amarone, repeated temperature swings cause expansion/contraction of the cork and premature oxidation."
})

# ─── L3M3L4 Ageing Potential Assessment ───────────────────────────────────────
write("L3M3L4.json", {
  "title": "Assessing Ageing Potential",
  "slides.0.title": "🧪 Assessing Ageing Potential",
  "slides.1.title": "🔬 What Determines a Wine's Ageing Potential?",
  "slides.2.title": "📊 Italian Varieties' Ageing Potential Rankings",
  "slides.3.title": "🔍 Practical Assessment: How to Evaluate Your Wine's Ageing Potential",
  "slides.4.title": "👁️ Visual and Olfactory Clues: Quickly Judging Ageing Stage",
  "slides.5.title": "🌡️ Storage Conditions and Their Effect on Ageing",
  "slides.6.title": "🎓 Summary: Becoming an Ageing Potential Expert",
  "slides.7.title": "🧠 Investment Vintage Knowledge Check",
  "quiz.0.question": "Among the four chemical pillars of wine ageing, which is the most critical 'first line of defence'?",
  "quiz.0.options.0": "Tannins",
  "quiz.0.options.1": "Acidity (tartaric acid) — protecting against microbial spoilage and oxidation",
  "quiz.0.options.2": "Alcohol",
  "quiz.0.options.3": "Residual sugar",
  "quiz.0.explanation": "Natural acidity is wine's primary preservative — it lowers pH to inhibit microbial growth and slows oxidation. Without sufficient acidity, even high tannin or alcohol cannot guarantee long-term preservation.",
  "quiz.1.question": "If a Barolo is stored at 20°C room temperature for 20 years, this is equivalent to ageing how long in a professional cellar (14°C)?",
  "quiz.1.options.0": "20 years — no difference",
  "quiz.1.options.1": "Approximately 10–12 years (wine ages roughly twice as fast at 20°C vs 14°C)",
  "quiz.1.options.2": "40 years",
  "quiz.1.options.3": "5 years",
  "quiz.1.explanation": "Biochemical reaction rates roughly double with every 10°C temperature rise (Arrhenius equation). Storing at 20°C instead of 14°C means the wine ages nearly twice as quickly — effectively shortening the ageing window by half.",
  "quiz.2.question": "Which combination of characteristics represents a wine at its 'peak maturity' (10–20 years)?",
  "quiz.2.options.0": "Bright ruby with intense primary fruit",
  "quiz.2.options.1": "Garnet colour with orange rim + dried fruit + earthy/forest-floor notes + silky tannins",
  "quiz.2.options.2": "Very pale brown with vinegar-like aromas",
  "quiz.2.options.3": "Deep inky purple with jammy blackberry",
  "quiz.2.explanation": "A wine at its peak shows: garnet colour with developing orange rim (oxidation at the edge), evolving tertiary aromas (dried fruit, earth, leather), and tannins softened to a silky, integrated texture.",
  "quiz.3.question": "When using an ageing potential checklist, which wine would score highest?",
  "quiz.3.options.0": "A light Barbera d'Asti with 12.5% alcohol",
  "quiz.3.options.1": "A Barolo Riserva from a great vintage with high acidity, high tannins and high concentration",
  "quiz.3.options.2": "A young Pinot Grigio",
  "quiz.3.options.3": "A Prosecco from the current vintage",
  "quiz.3.explanation": "An ageing potential checklist considers: acidity, tannin, concentration/extract, structure balance, provenance and vintage. A Barolo Riserva from a top vintage scores highest on all criteria."
})

# ─── L3M4L1 Blind Tasting Methodology ────────────────────────────────────────
write("L3M4L1.json", {
  "title": "Blind Tasting Methodology: The SAT System",
  "slides.0.title": "🎭 Blind Tasting Methodology",
  "slides.1.title": "❓ What is Blind Tasting? Why Does It Matter?",
  "slides.2.title": "📋 The SAT System: Three-Step Professional Blind Tasting Framework",
  "slides.3.title": "👁️ SIGHT: 30-Second Visual Analysis",
  "slides.4.title": "👃 AROMA: 90-Second Aromatic Fingerprint Building",
  "slides.5.title": "👅 TASTE: Palate Analysis and Deductive Reasoning",
  "slides.6.title": "🎓 Summary: Mastering the SAT Blind Tasting System",
  "slides.7.title": "🧠 Blind Tasting Methodology Knowledge Check",
  "quiz.0.question": "Why must the SAT blind tasting system follow the S→A→T sequence?",
  "quiz.0.options.0": "It is faster in this order",
  "quiz.0.options.1": "Each step builds on the previous — visual informs aromatic interpretation, and together they guide the palate analysis and final deduction",
  "quiz.0.options.2": "Regulatory requirements",
  "quiz.0.options.3": "It has no particular reason — any order is acceptable",
  "quiz.0.explanation": "The S→A→T sequence builds a cumulative picture: visual clues (colour depth, hue) prime your aromatic expectations; together, sight and aroma narrow the field; taste confirms or challenges your preliminary conclusions.",
  "quiz.1.question": "'Pale ruby-red + distinct orange rim + high translucency' — which Italian variety does this most suggest?",
  "quiz.1.options.0": "Nero d'Avola",
  "quiz.1.options.1": "Nebbiolo (aged Barolo or Barbaresco)",
  "quiz.1.options.2": "Aglianico",
  "quiz.1.options.3": "Primitivo",
  "quiz.1.explanation": "This is the classic visual fingerprint of Nebbiolo: paradoxically pale and translucent for a structured red, with a characteristic orange rim developing quickly — even in young wines.",
  "quiz.2.question": "'Rose petals + tar + violet' — which Italian variety's core aromatic signature is this?",
  "quiz.2.options.0": "Sangiovese",
  "quiz.2.options.1": "Nebbiolo",
  "quiz.2.options.2": "Barbera",
  "quiz.2.options.3": "Aglianico",
  "quiz.2.explanation": "'Rose petals, tar and violets' is the classic triumvirate of Nebbiolo's aromatic signature — one of wine's most distinctive and recognisable aroma profiles.",
  "quiz.3.question": "'Extremely high acidity + extremely high tannins (but silky, fine-grained) + 120-second+ finish' — combined with the visual and aromatic evidence, what is the most likely conclusion?",
  "quiz.3.options.0": "Barolo or Barbaresco DOCG (Nebbiolo)",
  "quiz.3.options.1": "Chianti Classico Riserva (Sangiovese)",
  "quiz.3.options.2": "Amarone della Valpolicella",
  "quiz.3.options.3": "Brunello di Montalcino",
  "quiz.3.explanation": "Combining all three SAT steps: pale/orange visual + rose-tar-violet aromas + extreme acidity/silky tannins/epic finish = the definitive sensory profile of a great Nebbiolo — almost certainly Barolo or Barbaresco."
})

# ─── L3M4L2 Italian Red Wine Blind Tasting ────────────────────────────────────
write("L3M4L2.json", {
  "title": "Italian Red Wine Blind Tasting: Core Characteristics",
  "slides.0.title": "🍷 Italian Red Wine Blind Tasting: Core Characteristics",
  "slides.1.title": "👑 Northern King: Nebbiolo's Blind Tasting Profile",
  "slides.2.title": "❤️ Central Soul: Sangiovese's Blind Tasting Profile",
  "slides.3.title": "🌋 Southern Powerhouse: Aglianico's Blind Tasting Profile",
  "slides.4.title": "📊 Other Important Varieties Compared",
  "slides.5.title": "🧠 Variety Identification Knowledge Check",
  "quiz.0.question": "Which Italian red grape is known for 'pale colour with orange-red rim, yet extremely high acidity and powerful tannins'?",
  "quiz.0.options.0": "Nero d'Avola",
  "quiz.0.options.1": "Nebbiolo",
  "quiz.0.options.2": "Aglianico",
  "quiz.0.options.3": "Primitivo",
  "quiz.0.explanation": "Nebbiolo's paradox: despite its structurally powerful character (massive tannins and acidity), it has a surprisingly pale, translucent colour with a rapid orange-red rim evolution — unique among great red varieties.",
  "quiz.1.question": "Distinct 'sour cherry' and 'tomato leaf' aromas plus dusty, gritty tannins — which variety does this most suggest?",
  "quiz.1.options.0": "Nebbiolo",
  "quiz.1.options.1": "Sangiovese",
  "quiz.1.options.2": "Aglianico",
  "quiz.1.options.3": "Corvina",
  "quiz.1.explanation": "Sour cherry, tomato leaf and dried herbs are Sangiovese's primary aromatic fingerprints. Its tannins feel dusty and slightly gritty — characteristic of Sangiovese's fine but numerous tannin molecules.",
  "quiz.2.question": "What is the primary blind tasting structural difference between Aglianico and Nebbiolo?",
  "quiz.2.options.0": "Aglianico is always lighter in colour",
  "quiz.2.options.1": "Aglianico generally has a deeper, more opaque colour and more aggressive, tar-like tannins; Nebbiolo is paler with more refined tannins",
  "quiz.2.options.2": "Nebbiolo has much higher alcohol",
  "quiz.2.options.3": "There is no reliable structural difference",
  "quiz.2.explanation": "Aglianico vs Nebbiolo: Aglianico is typically deeper ruby-garnet and its tannins feel more abrasive and tar-like; Nebbiolo's tannins, though equally firm, are finer and more silky in texture — a key distinction.",
  "quiz.3.question": "Which variety has the characteristic of 'high acidity but extremely low tannins'?",
  "quiz.3.options.0": "Nebbiolo",
  "quiz.3.options.1": "Barbera",
  "quiz.3.options.2": "Aglianico",
  "quiz.3.options.3": "Sagrantino",
  "quiz.3.explanation": "Barbera is distinctive for its combination of vivid, natural high acidity and unusually low tannins — making it the most food-friendly of Italy's major red varieties and uniquely refreshing."
})

# ─── L3M4L3 Italian White Wine Blind Tasting ──────────────────────────────────
write("L3M4L3.json", {
  "title": "Italian White Wine Blind Tasting Techniques",
  "slides.0.title": "🍾 Italian White Wine Blind Tasting: Core Characteristics",
  "slides.1.title": "❄️ Northern Fresh Style: Pinot Grigio & Cortese",
  "slides.2.title": "🌿 North-East Aromatic and Structured: Garganega (Soave)",
  "slides.3.title": "⏳ Central Italy's Age-Worthy: Verdicchio",
  "slides.4.title": "☀️ Southern Full-Bodied: Fiano & Greco",
  "slides.5.title": "🧠 Appellation Terroir Identification Knowledge Check",
  "quiz.0.question": "Which Italian white wine characteristic is most often used as a marker for identifying Italian appellations?",
  "quiz.0.options.0": "Very high alcohol",
  "quiz.0.options.1": "Higher natural acidity compared with equivalent wines from other countries",
  "quiz.0.options.2": "Always light yellow in colour",
  "quiz.0.options.3": "Always very oaky",
  "quiz.0.explanation": "Italy's varied geography and cool-to-warm climates generally preserve more natural acidity in white wines than many New World regions — making natural freshness a key Italian white wine marker.",
  "quiz.1.question": "'Chamomile + white peach aromas, round palate with a toasted almond finish' — which variety is this most likely?",
  "quiz.1.options.0": "Pinot Grigio",
  "quiz.1.options.1": "Garganega (Soave)",
  "quiz.1.options.2": "Verdicchio",
  "quiz.1.options.3": "Fiano",
  "quiz.1.explanation": "Chamomile, white peach and almonds (particularly the bitter almond finish) are the hallmarks of Garganega from Soave — one of Italy's most distinctive white wine aromatic profiles.",
  "quiz.2.question": "Which Italian white variety often shows a greenish hue, fennel/anise aromas, green apple and extraordinary ageing potential?",
  "quiz.2.options.0": "Pinot Grigio",
  "quiz.2.options.1": "Verdicchio",
  "quiz.2.options.2": "Trebbiano",
  "quiz.2.options.3": "Falanghina",
  "quiz.2.explanation": "Verdicchio (literally 'little green one') is distinctive for its greenish reflections, anise-fennel aromatic character and exceptional ageing potential — developing extraordinary complexity over 10–20 years.",
  "quiz.3.question": "What is Fiano's most distinctive aromatic characteristic in blind tasting?",
  "quiz.3.options.0": "Very floral — rose and jasmine",
  "quiz.3.options.1": "Honey, beeswax, hazelnut and toasted notes — honeyed richness with nuts",
  "quiz.3.options.2": "Intensely mineral and flinty",
  "quiz.3.options.3": "Fresh citrus and green herb",
  "quiz.3.explanation": "Fiano di Avellino is immediately recognisable from its honeyed, waxy richness (Romans called it 'Vitis Apiana' for the bees it attracted) combined with hazelnut and toasted notes — rich and complex."
})

# ─── L3M4L4 Sparkling Wine Style Identification ───────────────────────────────
write("L3M4L4.json", {
  "title": "Italian Sparkling Wine Style Identification",
  "slides.0.title": "🫧 Italian Sparkling Wine Blind Tasting: Production Method Determines Style",
  "slides.1.title": "🍑 Fruit Bomb: Prosecco (Glera)",
  "slides.2.title": "🥂 Italy's Champagne: Franciacorta",
  "slides.3.title": "🏔️ Alpine Chill: Trento DOC",
  "slides.4.title": "🔀 Full Comparison: Blind Tasting Decision Tree",
  "slides.5.title": "🧠 Vintage Identification Knowledge Check",
  "quiz.0.question": "'Toasted bread, brioche and biscuit' aromas indicate which production method?",
  "quiz.0.options.0": "Charmat (tank) method — with autolysis contact",
  "quiz.0.options.1": "Metodo Classico (secondary fermentation in bottle with extended lees contact)",
  "quiz.0.options.2": "Ancestrale (pétillant naturel) method",
  "quiz.0.options.3": "Asti method (single fermentation)",
  "quiz.0.explanation": "Toasted bread, brioche and biscuit aromas ('autolytic' notes) are exclusively produced by extended contact with spent yeast (lees) in a sealed bottle — the signature of Metodo Classico.",
  "quiz.1.question": "'Pure green apple and pear aromas, no toasted notes, a faint sweet edge' — what is this most likely?",
  "quiz.1.options.0": "Franciacorta DOCG",
  "quiz.1.options.1": "Prosecco DOC/DOCG (Charmat method, minimal lees contact)",
  "quiz.1.options.2": "Trento DOC",
  "quiz.1.options.3": "Lambrusco di Sorbara",
  "quiz.1.explanation": "Prosecco (Charmat method, short lees contact) shows pure, simple fruit (green apple, pear, peach), no autolytic complexity and is usually off-dry — the most instantly recognisable Italian sparkling profile.",
  "quiz.2.question": "What structural characteristic does Trento DOC typically show that distinguishes it from Franciacorta?",
  "quiz.2.options.0": "Lower acidity",
  "quiz.2.options.1": "Even higher natural acidity and a more linear, alpine mineral character — from high-altitude, cool Trentino",
  "quiz.2.options.2": "More residual sugar",
  "quiz.2.options.3": "Orange or rosé colour",
  "quiz.2.explanation": "Trento DOC vineyards are higher-altitude and cooler than Franciacorta — producing sparkling wines with even crisper natural acidity, a pronounced alpine mineral freshness and perhaps slightly less richness.",
  "quiz.3.question": "Compared with French Champagne, Franciacorta's fruit character is typically?",
  "quiz.3.options.0": "More restrained and austere",
  "quiz.3.options.1": "More expressive, warmer and riper — Italian sunshine in a glass",
  "quiz.3.options.2": "Identical to Champagne",
  "quiz.3.options.3": "More acidic and green",
  "quiz.3.explanation": "Franciacorta, made in northern Italy's warmer summers, typically shows riper, more generous fruit (peach, nectarine, brioche) compared with Champagne's more restrained, brioche-and-green-apple profile."
})

# ─── L3M4L5 Blind Tasting Practice ───────────────────────────────────────────
write("L3M4L5.json", {
  "title": "Blind Tasting Practice (Interactive)",
  "slides.0.title": "🎭 Blind Tasting in Practice: How to Use This Lesson",
  "slides.1.title": "🔍 Mystery Wine 1",
  "slides.2.title": "🔍 Mystery Wine 2",
  "slides.3.title": "🔍 Mystery Wine 3",
  "slides.4.title": "🧠 Practical Blind Tasting Knowledge Check",
  "quiz.0.question": "Based on the Mystery Wine 1 tasting notes, what is the most likely wine?",
  "quiz.0.options.0": "Vermentino di Gallura DOCG",
  "quiz.0.options.1": "Barolo DOCG",
  "quiz.0.options.2": "Chianti Classico DOCG",
  "quiz.0.options.3": "Amarone della Valpolicella DOCG",
  "quiz.0.explanation": "Apply the SAT system step by step — integrate visual, aromatic and structural evidence to reach the most probable conclusion.",
  "quiz.1.question": "Based on the Mystery Wine 2 tasting notes, what is the most likely wine?",
  "quiz.1.options.0": "Prosecco DOC",
  "quiz.1.options.1": "Brunello di Montalcino DOCG",
  "quiz.1.options.2": "Aglianico del Vulture DOCG",
  "quiz.1.options.3": "Soave Classico DOC",
  "quiz.1.explanation": "Apply the SAT system step by step — integrate visual, aromatic and structural evidence to reach the most probable conclusion.",
  "quiz.2.question": "Based on the Mystery Wine 3 tasting notes, what is the most likely wine?",
  "quiz.2.options.0": "Franciacorta DOCG",
  "quiz.2.options.1": "Nero d'Avola Sicilia DOC",
  "quiz.2.options.2": "Primitivo di Manduria DOCG",
  "quiz.2.options.3": "Verdicchio dei Castelli di Jesi DOCG Riserva",
  "quiz.2.explanation": "Apply the SAT system step by step — integrate visual, aromatic and structural evidence to reach the most probable conclusion.",
  "quiz.3.question": "'Deep opaque colour, blackberry and volcanic ash aromas, extremely powerful thick tannins' — which variety is most likely?",
  "quiz.3.options.0": "Nebbiolo",
  "quiz.3.options.1": "Aglianico",
  "quiz.3.options.2": "Sangiovese",
  "quiz.3.options.3": "Barbera",
  "quiz.3.explanation": "Deep opaque colour + volcanic ash and dark fruit aromas + massively powerful, thick tannins = Aglianico — especially from volcanic soils (Taurasi, Aglianico del Vulture). Nebbiolo is paler; Sangiovese has dusty, not thick tannins."
})

# ─── L3M5L1 Italian Wine Industry Structure ──────────────────────────────────
write("L3M5L1.json", {
  "title": "Italian Wine Industry Structure",
  "slides.0.title": "🏭 The World's Largest Wine Producer",
  "slides.1.title": "🔍 Three Production Models Explained",
  "slides.2.title": "🌍 Export Markets and Global Distribution",
  "slides.3.title": "⚠️ Current Industry Challenges",
  "slides.4.title": "🧠 Industry Structure Knowledge Check",
  "quiz.0.question": "Which production model contributes over 50% of Italy's total wine output?",
  "quiz.0.options.0": "Small family estates (Azienda Agricola)",
  "quiz.0.options.1": "Wine cooperatives (Cantina Cooperativa / Cantina Sociale)",
  "quiz.0.options.2": "Large négociant merchants",
  "quiz.0.options.3": "DOCG estates only",
  "quiz.0.explanation": "Wine cooperatives (Cantina Cooperativa) account for over 50% of Italy's total wine production — formed by groups of grape-growers who pool their fruit and share winemaking facilities.",
  "quiz.1.question": "By export VALUE, which country is Italy's largest wine export market?",
  "quiz.1.options.0": "China",
  "quiz.1.options.1": "United States",
  "quiz.1.options.2": "Germany",
  "quiz.1.options.3": "United Kingdom",
  "quiz.1.explanation": "The United States is consistently Italy's single largest wine export market by value — with particularly strong demand for Prosecco, Pinot Grigio and premium Barolo/Brunello.",
  "quiz.2.question": "What does 'Azienda Agricola' on a wine label typically indicate?",
  "quiz.2.options.0": "A large industrial wine producer",
  "quiz.2.options.1": "An estate winery that grows its own grapes — 'from our own vineyards'",
  "quiz.2.options.2": "A winery that buys grapes from other growers",
  "quiz.2.options.3": "A winery that specialises in organic wines",
  "quiz.2.explanation": "Azienda Agricola signifies that the producer grows its own grapes on estate-owned or leased vineyards — suggesting greater terroir control and estate integrity compared with négociant producers.",
  "quiz.3.question": "What is the main internal (domestic) market challenge facing the Italian wine industry?",
  "quiz.3.options.0": "Overproduction of premium wines",
  "quiz.3.options.1": "Declining per capita wine consumption in Italy, particularly among younger generations",
  "quiz.3.options.2": "Falling export prices",
  "quiz.3.options.3": "Competition from other alcoholic beverages has always been the industry's main challenge",
  "quiz.3.explanation": "Like most traditional wine-producing countries, Italy faces a significant drop in domestic per-capita wine consumption — particularly among young Italians who prefer beer and spirits, challenging the industry's home market base."
})

# ─── L3M5L2 Fine Wine Investment Analysis ────────────────────────────────────
write("L3M5L2.json", {
  "title": "Fine Wine Investment Analysis",
  "slides.0.title": "📈 Italy's Fine Wine Market: The Rise",
  "slides.1.title": "💎 Four Factors Affecting Investment Value",
  "slides.2.title": "🏆 Case Study: The Sassicaia Investment Myth",
  "slides.3.title": "🌟 Emerging Investment Targets: Etna and Alto Piemonte",
  "slides.4.title": "🧠 Export Market Knowledge Check",
  "quiz.0.question": "In Italy's fine wine investment market, which category was first to enter international auction houses and is regarded as the 'blue-chip' representative?",
  "quiz.0.options.0": "Prosecco",
  "quiz.0.options.1": "Barolo and Brunello di Montalcino — Italy's classic 'noble' wines",
  "quiz.0.options.2": "Super Tuscans (Sassicaia, Masseto)",
  "quiz.0.options.3": "Amarone della Valpolicella",
  "quiz.0.explanation": "Barolo and Brunello di Montalcino were the original Italian fine wines to appear in major international auction rooms — establishing Italy's investment wine credentials from the 1980s onwards.",
  "quiz.1.question": "When assessing a fine wine's investment value, which factor is typically LEAST important?",
  "quiz.1.options.0": "Producer reputation and track record",
  "quiz.1.options.1": "Bottle label design",
  "quiz.1.options.2": "Vintage quality",
  "quiz.1.options.3": "Storage and provenance documentation",
  "quiz.1.explanation": "Label design has no bearing on investment value — a wine's investment worth is determined by producer, vintage quality, critical scores, scarcity and verifiable storage history.",
  "quiz.2.question": "What is the main reason Sassicaia 1985 is legendary in the auction market?",
  "quiz.2.options.0": "It was the first Super Tuscan",
  "quiz.2.options.1": "It scored 100 points from Robert Parker — the first Italian wine ever to do so — in a major international tasting",
  "quiz.2.options.2": "It was drunk at a royal wedding",
  "quiz.2.options.3": "It was the most expensive Italian wine ever produced",
  "quiz.2.explanation": "Sassicaia 1985 was awarded 100 points by Robert Parker in the late 1980s — the first Italian wine to receive a perfect score from Parker. This catapulted Italian fine wine onto the international investment stage.",
  "quiz.3.question": "Which Sicilian appellation has been called 'the Burgundy of the Mediterranean' by investors?",
  "quiz.3.options.0": "Marsala DOC",
  "quiz.3.options.1": "Etna DOC",
  "quiz.3.options.2": "Cerasuolo di Vittoria DOCG",
  "quiz.3.options.3": "Nero d'Avola Sicilia DOC",
  "quiz.3.explanation": "Etna DOC has become Italy's most exciting fine wine investment region — its single-vineyard Nerello Mascalese wines, with Burgundy-like elegance and volcanic mineral complexity, have attracted global collectors."
})

# ─── L3M5L3 Natural Wine and Organic Trends ──────────────────────────────────
write("L3M5L3.json", {
  "title": "Natural Wine and Organic Trends",
  "slides.0.title": "🌿 Italy: Europe's Organic Viticulture Leader",
  "slides.1.title": "📊 Three Sustainable Philosophies Compared",
  "slides.2.title": "🎭 Italy's Natural Wine Icons and Appellations",
  "slides.3.title": "📈 Market Impact and Future Outlook",
  "slides.4.title": "🧠 Natural Wine and Sustainability Knowledge Check",
  "quiz.0.question": "Which sustainable farming practice has the clearest legal framework and the EU-unified 'Euro Leaf' certification?",
  "quiz.0.options.0": "Biodynamic farming",
  "quiz.0.options.1": "Certified Organic farming",
  "quiz.0.options.2": "Natural wine",
  "quiz.0.options.3": "Lutte Raisonnée (sustainable viticulture)",
  "quiz.0.explanation": "Certified Organic farming is regulated by EU law (EC No 834/2007 and successor regulations) and identified by the green Euro Leaf logo — the clearest, most legally defined sustainability standard.",
  "quiz.1.question": "In addition to organic farming, what core philosophy does biodynamic farming emphasise?",
  "quiz.1.options.0": "Maximum yield per hectare",
  "quiz.1.options.1": "The farm as a self-sustaining ecosystem, guided by cosmic and lunar cycles",
  "quiz.1.options.2": "Use of only indigenous yeasts",
  "quiz.1.options.3": "No sulphur additions at any stage",
  "quiz.1.explanation": "Biodynamics (based on Rudolf Steiner's lectures) goes beyond organic — treating the farm as a closed, self-sustaining organism, using homeopathic preparations and working according to a lunar calendar.",
  "quiz.2.question": "Friuli pioneers such as Josko Gravner became world-famous for reviving which ancient winemaking technique?",
  "quiz.2.options.0": "Carbonic maceration",
  "quiz.2.options.1": "Amphorae/Qvevri fermentation and extended skin contact (orange wine)",
  "quiz.2.options.2": "Metodo Classico sparkling wine",
  "quiz.2.options.3": "Barrel fermentation",
  "quiz.2.explanation": "Josko Gravner of Collio travelled to Georgia in the 1990s and returned inspired to ferment white wines in clay amphorae (Qvevri) with months of skin contact — sparking the global orange wine revolution.",
  "quiz.3.question": "Which statement about natural wine is most accurate?",
  "quiz.3.options.0": "Natural wine has a universally agreed legal definition",
  "quiz.3.options.1": "Natural wine has no universally agreed legal definition — it is a concept based on minimal intervention, but standards vary widely between producers",
  "quiz.3.options.2": "Natural wine is the same as organic wine",
  "quiz.3.options.3": "Natural wine contains no alcohol",
  "quiz.3.explanation": "Unlike organic or biodynamic, 'natural wine' has no binding legal definition or official certification body. It is a philosophy — broadly meaning minimal vineyard and cellar intervention — but its boundaries are interpreted very differently by different producers."
})

# ─── L3M5L4 Climate Change Impact ────────────────────────────────────────────
write("L3M5L4.json", {
  "title": "Climate Change and Its Impact",
  "slides.0.title": "🌡️ Climate Change: The Greatest Challenge for Italian Wine",
  "slides.1.title": "🗺️ Redrawn Wine Maps: Moving Uphill and North",
  "slides.2.title": "🌱 Vineyard Management and Winemaking Adaptation",
  "slides.3.title": "📋 Regulatory Challenges and the Future",
  "slides.4.title": "🧠 Climate Change Knowledge Check",
  "quiz.0.question": "What is the most direct and widespread effect of global warming on Italian wine styles?",
  "quiz.0.options.0": "Lower alcohol levels",
  "quiz.0.options.1": "Higher alcohol levels from riper, more sugar-rich grapes — and reduced natural acidity",
  "quiz.0.options.2": "Lighter-bodied wines",
  "quiz.0.options.3": "More complex aromatic profiles",
  "quiz.0.explanation": "Warmer temperatures accelerate sugar ripening faster than phenolic maturity — producing wines with higher alcohol while natural acidity decreases. This is the most immediate and universal impact of climate change on Italian wine.",
  "quiz.1.question": "To adapt to climate change heat and drought, what is one of the most common vineyard management strategies adopted by Italian estates?",
  "quiz.1.options.0": "Planting at lower altitudes",
  "quiz.1.options.1": "Moving vineyards to higher elevations or cooler north-facing slopes",
  "quiz.1.options.2": "Switching to international varieties",
  "quiz.1.options.3": "Installing artificial irrigation regardless of regulations",
  "quiz.1.explanation": "Higher elevations are cooler — allowing grapes to ripen more slowly and retain more natural acidity. Many Italian producers are increasingly planting at higher altitudes to offset warming temperatures.",
  "quiz.2.question": "In the traditional Barolo appellation, which aspect (slope orientation) was once most prized, and what aspects are now being reassessed because of climate change?",
  "quiz.2.options.0": "South-facing was prized; now east-facing is reassessed",
  "quiz.2.options.1": "South and southwest-facing slopes were once the most coveted; now cooler north and east-facing slopes are gaining value",
  "quiz.2.options.2": "No aspect was ever particularly valued",
  "quiz.2.options.3": "East-facing was always best",
  "quiz.2.explanation": "Historically, south and southwest-facing Barolo slopes commanded the highest prices (maximum sun exposure). As temperatures rise, these plots risk over-ripening — making once-overlooked cooler north and east-facing sites increasingly attractive.",
  "quiz.3.question": "Which of the following is NOT a common winemaking adaptation strategy for climate change?",
  "quiz.3.options.0": "Earlier harvesting to preserve natural acidity",
  "quiz.3.options.1": "Acidification (adding tartaric acid)",
  "quiz.3.options.2": "Removing large amounts of water from the wine using reverse osmosis",
  "quiz.3.options.3": "Night-time harvesting to preserve aromatic freshness",
  "quiz.3.explanation": "While earlier harvesting, acidification and night harvesting are all legitimate and widely used adaptation strategies, excessive use of concentration techniques (reverse osmosis, spinning cone) to fix structural imbalances from over-ripening is generally considered a less desirable 'correction' rather than adaptation."
})

# ─── L3M6L1 Advanced Food Pairing Theory ─────────────────────────────────────
write("L3M6L1.json", {
  "title": "Advanced Food and Wine Pairing Theory",
  "slides.0.title": "🎯 Beyond Tradition: The Core Elements of Food Pairing",
  "slides.1.title": "🔀 Interaction Principles: Complementary and Contrasting",
  "slides.2.title": "🌶️ Tricky Elements: Umami and Spice",
  "slides.3.title": "🗺️ Italy's 'Regional Pairing' Philosophy",
  "slides.4.title": "🧠 Advanced Food Pairing Knowledge Check",
  "quiz.0.question": "In advanced food pairing, what effect does food 'sweetness' have on wine?",
  "quiz.0.options.0": "Makes the wine taste sweeter",
  "quiz.0.options.1": "Makes the wine taste drier, more bitter and less fruity — the wine appears to lose its sweetness",
  "quiz.0.options.2": "Has no effect on the wine's perceived sweetness",
  "quiz.0.options.3": "Makes the wine's tannins softer",
  "quiz.0.explanation": "Sweet food reduces the perceived sweetness of the wine — a dry wine beside a sweet dish tastes austere, thin and bitter. The wine must match or exceed the sweetness of the food.",
  "quiz.1.question": "When facing a rich, fatty dish (fried seafood, creamy risotto), what is the best 'contrasting pairing' strategy?",
  "quiz.1.options.0": "Pair with a heavy, tannic red wine",
  "quiz.1.options.1": "Pair with a high-acid wine (Prosecco, Verdicchio, Gavi) — the acidity cuts through the fat",
  "quiz.1.options.2": "Pair with a sweet wine",
  "quiz.1.options.3": "Avoid pairing — fatty food doesn't need wine",
  "quiz.1.explanation": "The classic contrasting principle: high acidity provides contrast to rich fat — cutting through the richness and refreshing the palate. This is why Champagne with fried food works so brilliantly.",
  "quiz.2.question": "Umami-rich food makes wine more bitter. But if the umami dish also has strong SALTINESS (Parmigiano, prosciutto), how should you pair?",
  "quiz.2.options.0": "Avoid wine with salty umami food",
  "quiz.2.options.1": "Saltiness counteracts the negative effect of umami on wine — moderately salty umami dishes become much more wine-friendly",
  "quiz.2.options.2": "Pair with very sweet wine to counter the saltiness",
  "quiz.2.options.3": "Only pair with water",
  "quiz.2.explanation": "Saltiness suppresses bitterness (including umami-induced bitterness in wine). Salty-umami dishes (aged Parmigiano, prosciutto crudo) are far more wine-friendly than pure umami — the salt corrects the wine-pairing problem.",
  "quiz.3.question": "Which pairing best represents the 'regional pairing' philosophy — 'what grows together, goes together'?",
  "quiz.3.options.0": "Barolo with fresh mozzarella",
  "quiz.3.options.1": "Chianti Classico with Florentine bistecca or ribollita (Tuscany)",
  "quiz.3.options.2": "Prosecco with Sicilian arancini",
  "quiz.3.options.3": "Vermentino with a Piemontese truffle dish",
  "quiz.3.explanation": "Regional pairing means pairing within the same wine and food traditions — Chianti Classico and Florentine cuisine evolved together over centuries. The tannic, acidic Sangiovese perfectly suits the fatty, herb-rich Tuscan cuisine."
})

# ─── L3M6L2 Aged Wine Service and Decanting ──────────────────────────────────
write("L3M6L2.json", {
  "title": "The Art of Serving and Decanting Aged Wine",
  "slides.0.title": "🍷 The Fragility and Preciousness of Aged Wine",
  "slides.1.title": "🔧 Before Opening: Resting and Tools",
  "slides.2.title": "🫧 Decanting vs Aeration",
  "slides.3.title": "🥂 Glass Shape Selection and Temperature Control",
  "slides.4.title": "🧠 Wine Consultant Knowledge Check",
  "quiz.0.question": "Before opening a Barolo stored horizontally for 20 years, what is the single most important preparation step?",
  "quiz.0.options.0": "Chill it in the refrigerator for 30 minutes",
  "quiz.0.options.1": "Stand the bottle upright for 24–48 hours to allow sediment to settle to the bottom",
  "quiz.0.options.2": "Immediately decant as soon as you remove it from storage",
  "quiz.0.options.3": "Warm the bottle in warm water",
  "quiz.0.explanation": "Old wines stored horizontally accumulate sediment against the side of the bottle. Standing the bottle upright for 24–48 hours allows sediment to fall to the bottom — making careful decanting without disturbing the sediment possible.",
  "quiz.1.question": "Why is using an Ah-So (twin-prong cork puller) strongly recommended for old wines?",
  "quiz.1.options.0": "It opens bottles faster",
  "quiz.1.options.1": "An old, fragile cork may crumble when a screw is inserted — the Ah-So grips both sides of the cork without penetrating it, allowing extraction intact",
  "quiz.1.options.2": "It prevents the wine from oxidising",
  "quiz.1.options.3": "It is the only tool that fits old bottle sizes",
  "quiz.1.explanation": "After 20+ years, natural corks become brittle and compressed. A traditional cork screw risks piercing the centre and causing it to crumble into the wine. The Ah-So's twin prongs slide down the sides of the cork, gripping it without damage.",
  "quiz.2.question": "Regarding aged wine 'decanting' vs 'aeration' — which statement is correct?",
  "quiz.2.options.0": "All old wines should be aerated for 3+ hours",
  "quiz.2.options.1": "Old wines are decanted gently to remove sediment — NOT to add oxygen. Aeration should be brief (30 minutes maximum) as old wines fade quickly when exposed to air",
  "quiz.2.options.2": "Old wines do not need decanting at all",
  "quiz.2.options.3": "Double decanting (back and forth) is recommended for all old wines",
  "quiz.2.explanation": "Old wines are decanted for one reason only: sediment separation. They do NOT benefit from prolonged aeration — unlike young tannic wines, old wines can fade rapidly when exposed to oxygen. Serve soon after decanting.",
  "quiz.3.question": "Which glass shape is most suitable for drinking aged Nebbiolo (old Barolo)?",
  "quiz.3.options.0": "A narrow flute glass",
  "quiz.3.options.1": "A large Burgundy-style balloon glass — wide bowl to concentrate aromas, with a slight taper",
  "quiz.3.options.2": "A standard Bordeaux glass",
  "quiz.3.options.3": "A small dessert wine glass",
  "quiz.3.explanation": "Aged Nebbiolo requires a large, wide-bowled Burgundy-style glass — the generous surface area encourages the complex, delicate tertiary aromas (tar, roses, dried violets, earth) to develop and concentrate before tasting."
})

# ─── L3M6L3 Wine List Design and Inventory Management ────────────────────────
write("L3M6L3.json", {
  "title": "Wine List Design and Inventory Management",
  "slides.0.title": "📋 Core Principles of Wine List Design",
  "slides.1.title": "🍷 Building an Italian-Focused Wine List",
  "slides.2.title": "💰 Pricing Strategy",
  "slides.3.title": "🍾 Inventory Management and By-the-Glass (BTG) Strategy",
  "slides.4.title": "🧠 Wine Event Planning Knowledge Check",
  "quiz.0.question": "When designing a wine list with real depth for Italian wines, beyond the 'three pillars (Piemonte, Tuscany, Veneto)', what elements do sommeliers typically add to demonstrate expertise?",
  "quiz.0.options.0": "Only more French wines",
  "quiz.0.options.1": "Hidden gem regions (Campania, Friuli, Alto Piemonte), older vintages and unusual indigenous varieties",
  "quiz.0.options.2": "Only the most expensive wines",
  "quiz.0.options.3": "Only organic and natural wines",
  "quiz.0.explanation": "A sophisticated Italian wine list goes beyond the classics to include: southern Italian gems (Taurasi, Greco di Tufo), Friuli whites, Alto Piemonte Nebbiolo, interesting indigenous varieties and older vintages — signalling genuine depth of knowledge.",
  "quiz.1.question": "What pricing strategy do modern restaurants most commonly use to encourage customers to trade up to premium wines while maintaining entry-level margins?",
  "quiz.1.options.0": "Flat markup (fixed amount above cost)",
  "quiz.1.options.1": "Regressive scaling — high markup percentage on entry-level, lower percentage (but higher absolute margin) on premium wines",
  "quiz.1.options.2": "Fixed percentage markup for all wines",
  "quiz.1.options.3": "Price everything at cost × 3",
  "quiz.1.explanation": "Regressive scaling: entry-level wines carry a higher percentage markup (e.g., ×4–5 wholesale cost); premium wines carry a lower percentage (e.g., ×2–3) — making expensive bottles more attractive while ensuring the restaurant profits adequately at every level.",
  "quiz.2.question": "What is the industry's most common 'golden rule' for BTG pricing?",
  "quiz.2.options.0": "Price at the same level as bottled wine",
  "quiz.2.options.1": "One glass (usually 150ml) = the wholesale bottle cost — meaning the whole bottle's revenue covers the bottle cost on the first glass",
  "quiz.2.options.2": "Price at double the bottled wine per-glass equivalent",
  "quiz.2.options.3": "Price based solely on what the market will bear",
  "quiz.2.explanation": "The BTG golden rule: price one glass at approximately the wine's wholesale cost — so the first pour covers your cost, and remaining glasses are profit. A standard 750ml bottle yields approximately 5 glasses.",
  "quiz.3.question": "If a restaurant wants to offer very expensive wines by the glass (e.g., a $50 glass of aged Barolo) without worrying about unsold glasses oxidising, what is the most effective solution?",
  "quiz.3.options.0": "Only open on weekends",
  "quiz.3.options.1": "Use a Coravin wine preservation system — extract wine without removing the cork",
  "quiz.3.options.2": "Re-cork the bottle and refrigerate immediately",
  "quiz.3.options.3": "Only pour the wine for parties of 4 or more",
  "quiz.3.explanation": "Coravin uses a thin needle to extract wine through the cork, replacing it with argon gas — the cork reseals naturally. This allows restaurants to offer premium aged wines by the glass without committing to opening the full bottle."
})

# ─── L3M7L1 Regional Pairing Philosophy ──────────────────────────────────────
write("L3M7L1.json", {
  "title": "Regional Pairing Philosophy: North to South",
  "slides.0.title": "🗺️ 'Regional Pairing' Philosophy: Terroir as the Perfect Match",
  "slides.1.title": "🏔️ Northern Italy: Rich Cuisine and Powerful Reds",
  "slides.2.title": "🌞 Central and Southern Italy: Olive Oil, Tomatoes and Seafood",
  "slides.3.title": "🧠 Regional Pairing Knowledge Test"
})

# ─── L3M7L2 Special Wine Pairings ────────────────────────────────────────────
write("L3M7L2.json", {
  "title": "Special Wine Pairings: Sparkling, Sweet and Fortified",
  "slides.0.title": "🫧 Sparkling Wine: Not Just an Aperitivo",
  "slides.1.title": "🍯 The Art of Sweet Wine: From Pre-Dessert to Post-Dessert",
  "slides.2.title": "🧀 The Cheese Course: Italian Cheese Pairing Guide",
  "slides.3.title": "🧠 Special Wine Pairing Knowledge Test"
})

# ─── L3M7L3 Sommelier Service Practice ───────────────────────────────────────
write("L3M7L3.json", {
  "title": "Sommelier Practice: Temperature, Opening, Decanting and Service",
  "slides.0.title": "🌡️ Service Temperature: The Invisible Flavour Factor",
  "slides.1.title": "🫧 The Art of Decanting: When It's Needed and How to Judge",
  "slides.2.title": "🥂 Glass Selection Logic and Restaurant Service Applications",
  "slides.3.title": "🧠 Sommelier Service Practice Knowledge Test"
})

# ─── L3M7L4 Food Pairing in Practice ─────────────────────────────────────────
write("L3M7L4.json", {
  "title": "Food Pairing in Practice: Designing a Complete Tasting Menu Wine List",
  "slides.0.title": "🎯 The Logical Framework for Designing a Complete Tasting Menu Wine List",
  "slides.1.title": "🍽️ Case Study: Designing a Piemontese Dinner Wine Pairing",
  "slides.2.title": "🧠 Food Pairing Comprehensive Practice Test"
})

print("Level 3 EN overlays created successfully!")
