#!/usr/bin/env python3
"""Generate EN overlay JSON files for all Italy Level 2 lessons."""
import json, os

BASE = os.path.join(os.path.dirname(__file__), "..", "src", "locales", "en", "lessons", "italy")
os.makedirs(BASE, exist_ok=True)

def write(filename, data):
    path = os.path.join(BASE, filename)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"Created {filename}")

# ─── L2M1L1 Trentino-Alto Adige ───────────────────────────────────────────────
write("L2M1L1.json", {
  "title": "Trentino-Alto Adige",
  "slides.0.title": "🏔️ Trentino-Alto Adige",
  "slides.0.subtitle": "Italy's Alpine Wine Paradise",
  "slides.1.title": "🏔️ Trentino Wine Region Map",
  "slides.2.title": "🗺️ A Region of Dual Identity",
  "slides.3.title": "🏛️ History and Cultural Heritage",
  "slides.4.title": "🍇 Alto Adige's Five Key White Varieties",
  "slides.5.title": "🏔️ Alto Adige — Deep Dive",
  "slides.6.title": "🍇 Native and Speciality Varieties",
  "slides.7.title": "🍷 Trentino's Pride",
  "slides.8.title": "🍾 Trento DOC — Deep Dive",
  "slides.9.title": "🏔️ Advantages of Alpine Terroir",
  "slides.10.title": "🗺️ Sub-Zones and Terroir Microclimates",
  "slides.11.title": "📊 Alto Adige vs Trentino Comparison",
  "slides.12.title": "🏰 Notable Producers and Wines",
  "slides.13.title": "🍴 Food Pairing Suggestions",
  "slides.14.title": "🎓 Key Takeaways",
  "slides.15.title": "🧠 Trentino-Alto Adige Knowledge Check",
  "quiz.0.question": "Where did Gewürztraminer originate?",
  "quiz.0.options.0": "Alsace, France",
  "quiz.0.options.1": "Tramin (Termeno), Alto Adige, Italy",
  "quiz.0.options.2": "Baden, Germany",
  "quiz.0.options.3": "Graubünden, Switzerland",
  "quiz.0.explanation": "Gewürztraminer takes its name from the village of Tramin (Termeno) in Alto Adige. It is one of the world's most aromatic white grapes.",
  "quiz.1.question": "What production method does Trento DOC use?",
  "quiz.1.options.0": "Charmat (tank) method",
  "quiz.1.options.1": "Metodo Classico (traditional Champagne method)",
  "quiz.1.options.2": "Ancestrale method",
  "quiz.1.options.3": "Asti (single-fermentation) method",
  "quiz.1.explanation": "Trento DOC uses Metodo Classico (secondary fermentation in bottle), producing Italy's finest mountain sparkling wines.",
  "quiz.2.question": "What is Trentino's most representative red grape variety?",
  "quiz.2.options.0": "Lagrein",
  "quiz.2.options.1": "Teroldego",
  "quiz.2.options.2": "Marzemino",
  "quiz.2.options.3": "Schiava",
  "quiz.2.explanation": "Teroldego Rotaliano DOC is Trentino's flagship red — a bold, deeply coloured wine from the Campo Rotaliano plain.",
  "quiz.3.question": "Before 1919, Alto Adige was part of which empire?",
  "quiz.3.options.0": "German Empire",
  "quiz.3.options.1": "Austro-Hungarian Empire",
  "quiz.3.options.2": "Swiss Confederation",
  "quiz.3.options.3": "Kingdom of Savoy",
  "quiz.3.explanation": "Alto Adige (South Tyrol) was part of the Austro-Hungarian Empire until 1919, which is why Austrian grape varieties such as Gewürztraminer and Riesling thrive here."
})

# ─── L2M1L2 Friuli Venezia Giulia ─────────────────────────────────────────────
write("L2M1L2.json", {
  "title": "Friuli Venezia Giulia",
  "slides.0.title": "🌿 Friuli Venezia Giulia",
  "slides.0.subtitle": "Italy's White Wine Treasure",
  "slides.1.title": "🌿 Friuli Wine Region Map",
  "slides.2.title": "🗺️ A Wine Treasure on the Eastern Border",
  "slides.3.title": "🏛️ History and Cultural Heritage",
  "slides.4.title": "🍇 Three Core Appellations",
  "slides.5.title": "🌍 Ponca Soil and Terroir — Deep Dive",
  "slides.6.title": "🌟 Friuli's Six Key White Grape Varieties",
  "slides.7.title": "🍇 Native and International Varieties",
  "slides.8.title": "🍊 The Orange Wine Revolution",
  "slides.9.title": "🧡 Orange Wine — Deep Dive",
  "slides.10.title": "🗺️ Sub-Zones and Single-Vineyard Culture",
  "slides.11.title": "🏰 Notable Producers and Wines",
  "slides.12.title": "📊 Friuli Quality Pyramid",
  "slides.13.title": "🍴 Friuli White Wine Food Pairings",
  "slides.14.title": "🎓 Key Takeaways",
  "slides.15.title": "🧠 Friuli Knowledge Check",
  "quiz.0.question": "What is Friuli's most prestigious appellation?",
  "quiz.0.options.0": "Grave del Friuli DOC",
  "quiz.0.options.1": "Collio DOCG / Friuli Colli Orientali DOC",
  "quiz.0.options.2": "Isonzo DOC",
  "quiz.0.options.3": "Carso DOC",
  "quiz.0.explanation": "Collio (now a DOCG) and Friuli Colli Orientali DOC are the most prestigious appellations in Friuli, producing Italy's finest white wines.",
  "quiz.1.question": "What is Friuli's 'King of White Grapes'?",
  "quiz.1.options.0": "Pinot Grigio",
  "quiz.1.options.1": "Friulano (Tocai Friulano)",
  "quiz.1.options.2": "Ribolla Gialla",
  "quiz.1.options.3": "Verduzzo",
  "quiz.1.explanation": "Friulano (formerly Tocai Friulano) is considered the king of Friuli's white grapes — complex, mineral and age-worthy.",
  "quiz.2.question": "How is orange wine (vino arancione) made?",
  "quiz.2.options.0": "By adding orange juice",
  "quiz.2.options.1": "By fermenting white grapes with extended skin contact",
  "quiz.2.options.2": "By blending red and white wines",
  "quiz.2.options.3": "Using a special yeast strain",
  "quiz.2.explanation": "Orange wine is made by fermenting white grapes in contact with their skins, like red wine — extracting tannins, colour and texture.",
  "quiz.3.question": "What is the distinctive soil type of the Collio appellation?",
  "quiz.3.options.0": "Volcanic basalt",
  "quiz.3.options.1": "Ponca (Flysch — alternating marl and sandstone)",
  "quiz.3.options.2": "Glacial moraine",
  "quiz.3.options.3": "Red clay (Terra Rossa)",
  "quiz.3.explanation": "Collio's unique Ponca (Flysch) soil — alternating layers of compressed marl and sandstone — gives its wines an extraordinary mineral character."
})

# ─── L2M1L3 Liguria ───────────────────────────────────────────────────────────
write("L2M1L3.json", {
  "title": "Liguria — Coastal Wines",
  "slides.0.title": "🌊 Liguria",
  "slides.0.subtitle": "Italy's Heroic Viticulture",
  "slides.1.title": "🌊 Liguria Wine Region Map",
  "slides.2.title": "🏛️ History and Cultural Heritage",
  "slides.3.title": "🏖️ Italy's 'Riviera'",
  "slides.4.title": "⛰️ Heroic Viticulture — Deep Dive",
  "slides.5.title": "🍇 Three Key White Varieties",
  "slides.6.title": "🍇 Vermentino and Native Varieties — Deep Dive",
  "slides.7.title": "🏞️ Cinque Terre — The Five Lands",
  "slides.8.title": "🍯 Sciacchetrà — Sweet Wine Deep Dive",
  "slides.9.title": "🌊 The Influence of Maritime Terroir",
  "slides.10.title": "🌊 Maritime Terroir and Microclimate — Deep Dive",
  "slides.11.title": "📍 Other Important Appellations",
  "slides.12.title": "🏰 Notable Producers and Wines",
  "slides.13.title": "🍴 Ligurian Food Culture",
  "slides.14.title": "🎓 Key Takeaways",
  "slides.15.title": "🧠 Liguria Knowledge Check",
  "quiz.0.question": "What is Liguria's most representative white grape variety?",
  "quiz.0.options.0": "Vermentino",
  "quiz.0.options.1": "Bosco",
  "quiz.0.options.2": "Pigato",
  "quiz.0.options.3": "Albarola",
  "quiz.0.explanation": "Vermentino is Liguria's most widely planted and celebrated white grape, producing wines with fresh citrus, mineral and herbal character.",
  "quiz.1.question": "What are the main white grape varieties used in Cinque Terre wines?",
  "quiz.1.options.0": "Vermentino only",
  "quiz.1.options.1": "Bosco, Albarola and Vermentino",
  "quiz.1.options.2": "Trebbiano and Verdicchio",
  "quiz.1.options.3": "Cortese and Garganega",
  "quiz.1.explanation": "The Cinque Terre DOC blend requires Bosco (minimum 40%), with Albarola and Vermentino as the main supporting grapes.",
  "quiz.2.question": "What type of wine is Sciacchetrà?",
  "quiz.2.options.0": "Dry sparkling wine",
  "quiz.2.options.1": "Sweet passito wine",
  "quiz.2.options.2": "Fortified wine",
  "quiz.2.options.3": "Light dry rosé",
  "quiz.2.explanation": "Sciacchetrà is a rare sweet passito wine made from dried Cinque Terre grapes — one of Italy's most unique and hard-to-find wines.",
  "quiz.3.question": "What is the key characteristic of Liguria's vineyards?",
  "quiz.3.options.0": "Flat plains along river valleys",
  "quiz.3.options.1": "Extremely steep terraced hillsides — 'heroic viticulture'",
  "quiz.3.options.2": "High-altitude plateau vineyards",
  "quiz.3.options.3": "Volcanic soil on island terrain",
  "quiz.3.explanation": "Liguria's vineyards are among the most dramatic in Italy — tiny, vertiginous terraced plots (known as 'heroic viticulture') clinging to seaside cliffs."
})

# ─── L2M1L4 Emilia-Romagna ────────────────────────────────────────────────────
write("L2M1L4.json", {
  "title": "Emilia-Romagna",
  "slides.0.title": "🍾 Emilia-Romagna",
  "slides.0.subtitle": "Italy's Food Capital",
  "slides.1.title": "🍾 Emilia-Romagna Wine Region Map",
  "slides.2.title": "🗺️ Italy's Culinary Capital",
  "slides.3.title": "🍾 Lambrusco — The Misunderstood Sparkling Red",
  "slides.4.title": "🍇 Lambrusco's Three Key DOCs",
  "slides.5.title": "⚪ Emilia-Romagna White Wines",
  "slides.6.title": "🍷 Sangiovese di Romagna DOC",
  "slides.7.title": "🧀 Lambrusco and Emilia Food Pairings",
  "slides.8.title": "🎓 Key Takeaways",
  "slides.9.title": "🧠 Emilia-Romagna Knowledge Check",
  "quiz.0.question": "What is the mainstream style of quality Lambrusco?",
  "quiz.0.options.0": "Sweet and still",
  "quiz.0.options.1": "Dry (Secco) or off-dry (Amabile) sparkling red",
  "quiz.0.options.2": "Full still red wine",
  "quiz.0.options.3": "Sweet sparkling rosé",
  "quiz.0.explanation": "Quality Lambrusco is made dry (Secco) or off-dry (Amabile) — a revelation compared with the sugary versions widely exported in the 1980s.",
  "quiz.1.question": "Among the three Lambrusco DOCs, which is considered the most elegant and lightest-bodied?",
  "quiz.1.options.0": "Lambrusco di Sorbara DOC",
  "quiz.1.options.1": "Lambrusco Grasparossa di Castelvetro DOC",
  "quiz.1.options.2": "Lambrusco Salamino di Santa Croce DOC",
  "quiz.1.options.3": "Lambrusco Reggiano DOC",
  "quiz.1.explanation": "Lambrusco di Sorbara is the finest — pale in colour, with vivid raspberry and violet aromas and the highest acidity of all Lambrusco styles.",
  "quiz.2.question": "What was Italy's first white DOCG?",
  "quiz.2.options.0": "Soave Classico DOCG",
  "quiz.2.options.1": "Albana di Romagna DOCG",
  "quiz.2.options.2": "Gavi DOCG",
  "quiz.2.options.3": "Vernaccia di San Gimignano DOCG",
  "quiz.2.explanation": "Albana di Romagna was Italy's first white wine to achieve DOCG status (1987), though it remains controversial due to its variable quality.",
  "quiz.3.question": "Why is Lambrusco a good match for Emilia's rich, fatty cuisine?",
  "quiz.3.options.0": "High tannins cut through the fat",
  "quiz.3.options.1": "Bubbles and high acidity cut through the fat and refresh the palate",
  "quiz.3.options.2": "Its sweetness complements the savoury flavours",
  "quiz.3.options.3": "Its low alcohol doesn't overwhelm the food",
  "quiz.3.explanation": "Lambrusco's fizz and naturally high acidity cut through the fat of Emilia's pork, cheese and pasta dishes, refreshing the palate between bites."
})

# ─── L2M2L1 Marche ────────────────────────────────────────────────────────────
write("L2M2L1.json", {
  "title": "Marche",
  "slides.0.title": "🌊 Marche",
  "slides.0.subtitle": "Central Italy's Hidden Gem",
  "slides.1.title": "🌊 Marche Wine Region Map",
  "slides.2.title": "🗺️ Central Italy's Hidden Treasure",
  "slides.3.title": "🍇 Verdicchio — Marche's Star",
  "slides.4.title": "🍷 Rosso Conero & Rosso Piceno",
  "slides.5.title": "📚 Verdicchio's Ageing Potential",
  "slides.6.title": "🍇 Other Notable Varieties",
  "slides.7.title": "🍽️ Marche Cuisine and Food Pairings",
  "slides.8.title": "🏛️ History and Cultural Heritage",
  "slides.9.title": "🌄 Terroir — Deep Dive",
  "slides.10.title": "🍇 Verdicchio Variety Profile",
  "slides.11.title": "🍾 Winemaking Style Evolution",
  "slides.12.title": "🏔️ Conero and Montepulciano",
  "slides.13.title": "🌸 Three Emerging Varieties",
  "slides.14.title": "🏰 Producers and Buying Guide",
  "slides.15.title": "🎓 Key Takeaways",
  "slides.16.title": "🧠 Marche Knowledge Check",
  "quiz.0.question": "Of Verdicchio's two DOCGs, which has greater body and ageing potential?",
  "quiz.0.options.0": "Verdicchio di Matelica DOCG",
  "quiz.0.options.1": "Verdicchio dei Castelli di Jesi DOCG",
  "quiz.0.options.2": "Both are identical",
  "quiz.0.options.3": "Marche Bianco IGT",
  "quiz.0.explanation": "Verdicchio di Matelica DOCG is produced at higher altitude with cooler temperatures — giving it greater concentration, structure and ageing potential than Castelli di Jesi.",
  "quiz.1.question": "What is the primary grape variety used in Rosso Conero DOCG?",
  "quiz.1.options.0": "Sangiovese",
  "quiz.1.options.1": "Montepulciano",
  "quiz.1.options.2": "Montepulciano (minimum 85%)",
  "quiz.1.options.3": "Lacrima di Morro d'Alba",
  "quiz.1.explanation": "Rosso Conero DOCG is made from Montepulciano (minimum 85%), grown on the slopes of Monte Conero on the Adriatic coast.",
  "quiz.2.question": "What aromas does aged Verdicchio Riserva develop?",
  "quiz.2.options.0": "Dark chocolate and tobacco",
  "quiz.2.options.1": "Honey, beeswax, toasted almonds and nutty notes",
  "quiz.2.options.2": "Leather and animal notes",
  "quiz.2.options.3": "Tropical fruit and vanilla",
  "quiz.2.explanation": "With age, quality Verdicchio develops complex secondary aromas: honey, beeswax, toasted almonds and nutty richness — similar to aged Burgundy.",
  "quiz.3.question": "What is Lacrima di Morro d'Alba's most distinctive characteristic?",
  "quiz.3.options.0": "Extremely high tannins",
  "quiz.3.options.1": "Exceptionally intense floral aromas (rose, violet, spice)",
  "quiz.3.options.2": "Very high alcohol",
  "quiz.3.options.3": "Deep mineral character",
  "quiz.3.explanation": "Lacrima di Morro d'Alba is famous for its explosively floral aromas — rose petals, violets and exotic spice — which is virtually unique among Italian red grapes."
})

# ─── L2M2L2 Umbria ────────────────────────────────────────────────────────────
write("L2M2L2.json", {
  "title": "Umbria",
  "slides.0.title": "🍇 Umbria",
  "slides.0.subtitle": "Italy's Green Heart",
  "slides.1.title": "🍇 Umbria Wine Region Map",
  "slides.2.title": "💚 Italy's Green Heart",
  "slides.3.title": "🍇 Sagrantino — Italy's King of Tannins",
  "slides.4.title": "🍷 Sagrantino's Two Styles",
  "slides.5.title": "⚪ Orvieto DOC — Umbria's Classic White",
  "slides.6.title": "🍷 Montefalco Rosso DOC",
  "slides.7.title": "🍇 Other Umbrian Wines",
  "slides.8.title": "🍽️ Umbrian Food Culture",
  "slides.9.title": "🏛️ History and Cultural Heritage",
  "slides.10.title": "🌍 Geological Terroir — Deep Dive",
  "slides.11.title": "🧬 Sagrantino Variety Science and Clones",
  "slides.12.title": "🍷 Winemaking Style Evolution",
  "slides.13.title": "🗺️ Montefalco Sub-Zones and Cru System",
  "slides.14.title": "🏆 Legendary Producers",
  "slides.15.title": "🎓 Key Takeaways",
  "slides.16.title": "🧠 Umbria Knowledge Check",
  "quiz.0.question": "Approximately how much tannin does Sagrantino contain?",
  "quiz.0.options.0": "~1,000 mg/L",
  "quiz.0.options.1": "~3,000–3,500 mg/L — the world's highest",
  "quiz.0.options.2": "~500 mg/L",
  "quiz.0.options.3": "~2,000 mg/L",
  "quiz.0.explanation": "Sagrantino di Montefalco has the highest tannin content of any grape in the world — around 3,000–3,500 mg/L — far exceeding Nebbiolo or Cabernet.",
  "quiz.1.question": "How is Sagrantino di Montefalco Passito made?",
  "quiz.1.options.0": "Using botrytis (noble rot)",
  "quiz.1.options.1": "From dried (raisined) grapes — Appassimento",
  "quiz.1.options.2": "By late harvesting in winter",
  "quiz.1.options.3": "By freezing the grapes (Icewine method)",
  "quiz.1.explanation": "The Passito style of Sagrantino is made by drying the grapes to concentrate their sugar, then fermenting to produce a rich, complex sweet red wine.",
  "quiz.2.question": "What is the dominant variety of Orvieto DOC?",
  "quiz.2.options.0": "Trebbiano only",
  "quiz.2.options.1": "Grechetto (supported by Trebbiano and others)",
  "quiz.2.options.2": "Vermentino",
  "quiz.2.options.3": "Chardonnay",
  "quiz.2.explanation": "Orvieto DOC is based on Grechetto (minimum 40–60%), supported by Trebbiano Toscano and Verdello, producing a fresh and mineral white wine.",
  "quiz.3.question": "What is the main difference between Montefalco Rosso and Sagrantino di Montefalco?",
  "quiz.3.options.0": "They are made in different regions",
  "quiz.3.options.1": "Montefalco Rosso uses a Sangiovese-based blend; Sagrantino is 100% Sagrantino",
  "quiz.3.options.2": "Montefalco Rosso is a white wine",
  "quiz.3.options.3": "Sagrantino is only produced as a sweet wine",
  "quiz.3.explanation": "Montefalco Rosso uses a blend led by Sangiovese (60–70%) with Sagrantino (10–15%) and is more approachable. Sagrantino di Montefalco DOCG requires 100% Sagrantino."
})

# ─── L2M2L3 Lazio ─────────────────────────────────────────────────────────────
write("L2M2L3.json", {
  "title": "Lazio",
  "slides.0.title": "🏛️ Lazio",
  "slides.0.subtitle": "The Wines of the Eternal City",
  "slides.1.title": "🏛️ Lazio Wine Region Map",
  "slides.2.title": "🏛️ Wines of the Eternal City",
  "slides.3.title": "🍇 Frascati DOCG — Lazio's Star",
  "slides.4.title": "📖 Est! Est!! Est!!! di Montefiascone DOC",
  "slides.5.title": "🍷 Cesanese Red Wines",
  "slides.6.title": "🌋 The Influence of Volcanic Soils",
  "slides.7.title": "🍇 Other Lazio DOCs",
  "slides.8.title": "🍽️ Roman Cuisine and Food Pairings",
  "slides.9.title": "Falernian Wine: Ancient Rome's Liquid Gold",
  "slides.10.title": "Colli Albani Volcanic Complex: Geological Context",
  "slides.11.title": "The Malvasia Family DNA Lineage",
  "slides.12.title": "Traditional vs Modern Winemaking: Full Comparison",
  "slides.13.title": "Castelli Romani: Geography and History",
  "slides.14.title": "The Rise of Lazio Boutique Producers",
  "slides.15.title": "🎓 Key Takeaways",
  "slides.16.title": "🧠 Lazio Knowledge Check",
  "quiz.0.question": "From which area of Rome does Frascati originate?",
  "quiz.0.options.0": "The Roman hills north of Rome (Sabine Hills)",
  "quiz.0.options.1": "The Castelli Romani hills southeast of Rome",
  "quiz.0.options.2": "The volcanic plateau west of Rome",
  "quiz.0.options.3": "The Tiber valley plains",
  "quiz.0.explanation": "Frascati DOCG comes from the Castelli Romani hills in the Colli Albani area southeast of Rome — the cradle of Lazio's most famous white wine.",
  "quiz.1.question": "In the legend of Est! Est!! Est!!!, why did the servant write three 'Est' markings?",
  "quiz.1.options.0": "It was a secret code",
  "quiz.1.options.1": "The wine was so good, one 'Est' (meaning 'it is here!') was not enough",
  "quiz.1.options.2": "He needed to mark three different barrels",
  "quiz.1.options.3": "It was three separate wine stops",
  "quiz.1.explanation": "According to legend, a bishop's servant marked 'Est' on inns with good wine. Finding the Montefiascone wine exceptional, he wrote 'Est! Est!! Est!!!' — three times to convey his enthusiasm.",
  "quiz.2.question": "What is Lazio's only red wine DOCG?",
  "quiz.2.options.0": "Frascati Superiore DOCG",
  "quiz.2.options.1": "Cesanese del Piglio DOCG",
  "quiz.2.options.2": "Castelli Romani DOCG",
  "quiz.2.options.3": "Marino DOCG",
  "quiz.2.explanation": "Cesanese del Piglio DOCG (also known as Piglio) is Lazio's only red wine DOCG, made from the indigenous Cesanese grape with complex, silky character.",
  "quiz.3.question": "Among Rome's four classic pasta dishes, which wine best complements Carbonara?",
  "quiz.3.options.0": "Barolo DOCG",
  "quiz.3.options.1": "Frascati Superiore DOCG or Castelli Romani Bianco",
  "quiz.3.options.2": "Chianti Classico DOCG",
  "quiz.3.options.3": "Prosecco DOC",
  "quiz.3.explanation": "The creamy richness of Carbonara pairs beautifully with the crisp acidity of local Frascati or Castelli Romani white wines — a classic regional pairing."
})

# ─── L2M2L4 Abruzzo ───────────────────────────────────────────────────────────
write("L2M2L4.json", {
  "title": "Abruzzo",
  "slides.0.title": "🏔️ Abruzzo",
  "slides.0.subtitle": "Between Mountain and Sea",
  "slides.1.title": "🏔️ Abruzzo Wine Region Map",
  "slides.2.title": "🏔️ Between Mountain and Sea",
  "slides.3.title": "🍇 Montepulciano d'Abruzzo DOC",
  "slides.4.title": "🍷 Montepulciano Variety Profile",
  "slides.5.title": "⚪ Trebbiano d'Abruzzo DOC",
  "slides.6.title": "🌸 Cerasuolo d'Abruzzo DOC",
  "slides.7.title": "🎯 How to Select Quality Abruzzo Wines",
  "slides.8.title": "🍽️ Abruzzo Cuisine and Food Pairings",
  "slides.9.title": "Abruzzo Terroir Deep Analysis",
  "slides.10.title": "Abruzzo Historical Wine Evolution",
  "slides.11.title": "Vine Varieties and Classification Systems",
  "slides.12.title": "Abruzzo Modern Winemaking Revolution (1990s–2020s)",
  "slides.13.title": "Trebbiano Abruzzese Revival and Cerasuolo Winemaking",
  "slides.14.title": "Abruzzo Legendary Producers and Boutique Wineries",
  "slides.15.title": "🎓 Key Takeaways",
  "slides.16.title": "🧠 Abruzzo Knowledge Check",
  "quiz.0.question": "What is the key difference between Montepulciano d'Abruzzo and Vino Nobile di Montepulciano?",
  "quiz.0.options.0": "They are the same wine with different names",
  "quiz.0.options.1": "Montepulciano d'Abruzzo uses the Montepulciano grape; Vino Nobile uses Sangiovese (Prugnolo Gentile)",
  "quiz.0.options.2": "Vino Nobile is made in Abruzzo",
  "quiz.0.options.3": "Montepulciano d'Abruzzo is a white wine",
  "quiz.0.explanation": "A classic confusion: Montepulciano d'Abruzzo is a red wine from Abruzzo using the Montepulciano grape. Vino Nobile di Montepulciano is from Tuscany and uses Sangiovese (Prugnolo Gentile) — an entirely different wine.",
  "quiz.1.question": "What is the highest quality designation within Montepulciano d'Abruzzo?",
  "quiz.1.options.0": "Montepulciano d'Abruzzo DOC Riserva",
  "quiz.1.options.1": "Montepulciano d'Abruzzo Colline Teramane DOCG",
  "quiz.1.options.2": "Montepulciano d'Abruzzo Superiore DOC",
  "quiz.1.options.3": "Colline Pescaresi IGT",
  "quiz.1.explanation": "Montepulciano d'Abruzzo Colline Teramane DOCG is Abruzzo's only DOCG for red wine — from the hills around Teramo, requiring longer ageing.",
  "quiz.2.question": "What is distinctive about Cerasuolo d'Abruzzo?",
  "quiz.2.options.0": "It is a light red wine",
  "quiz.2.options.1": "It is a deeply coloured, powerful dry rosé made from Montepulciano",
  "quiz.2.options.2": "It is a sweet wine made from dried grapes",
  "quiz.2.options.3": "It is Italy's most expensive rosé",
  "quiz.2.explanation": "Cerasuolo d'Abruzzo DOC is Italy's most serious rosé — made from 100% Montepulciano with deep cherry-red colour, rich body and real ageing potential.",
  "quiz.3.question": "What is the relationship between Trebbiano d'Abruzzo and Trebbiano Toscano?",
  "quiz.3.options.0": "They are genetically identical",
  "quiz.3.options.1": "Trebbiano d'Abruzzo (Bombino Bianco) is a completely different variety from Trebbiano Toscano",
  "quiz.3.options.2": "Trebbiano Toscano is a sub-type of Trebbiano d'Abruzzo",
  "quiz.3.options.3": "They are the same variety grown in different regions",
  "quiz.3.explanation": "DNA studies revealed that 'Trebbiano d'Abruzzo' in the finest vineyards is actually Bombino Bianco — a completely different variety from the neutral Trebbiano Toscano."
})

# ─── L2M2L5 Molise ────────────────────────────────────────────────────────────
write("L2M2L5.json", {
  "title": "Molise",
  "slides.0.title": "🌿 Molise",
  "slides.0.subtitle": "Italy's Smallest and Most Unknown Region",
  "slides.1.title": "📍 Molise Wine Region Map",
  "slides.2.title": "🔍 Italy's Least-Known Wine Region",
  "slides.3.title": "🍇 Molise's Native Varieties",
  "slides.4.title": "🍷 Tintilia del Molise DOC",
  "slides.5.title": "🍷 Other Molise DOCs",
  "slides.6.title": "🏛️ Molise History and Culture",
  "slides.7.title": "🍽️ Molise Cuisine and Food Pairings",
  "slides.8.title": "❓ Why Is Molise Unknown?",
  "slides.9.title": "Molise Terroir and Viticulture",
  "slides.10.title": "Molise Historical Context",
  "slides.11.title": "Molise Native Varieties Overview",
  "slides.12.title": "Molise Modern Winemaking Revolution (1980s–2020s)",
  "slides.13.title": "Molise Native Variety Revival and Winemaking",
  "slides.14.title": "Molise Wine Industry Awakening",
  "slides.15.title": "🎓 Key Takeaways",
  "slides.16.title": "🧠 Molise Knowledge Check",
  "quiz.0.question": "What is the historical relationship between Molise and Abruzzo?",
  "quiz.0.options.0": "They have always been separate regions",
  "quiz.0.options.1": "Molise was part of Abruzzo until 1963, when it became Italy's second-smallest autonomous region",
  "quiz.0.options.2": "Abruzzo was once part of Molise",
  "quiz.0.options.3": "They share the same wine appellation system",
  "quiz.0.explanation": "Molise and Abruzzo were united as 'Abruzzo e Molise' until 1963, when Molise became Italy's youngest and second-smallest region.",
  "quiz.1.question": "What is Tintilia?",
  "quiz.1.options.0": "A white grape variety from Sardinia",
  "quiz.1.options.1": "Molise's indigenous red grape — possibly of Spanish origin — producing powerful, structured reds",
  "quiz.1.options.2": "A sweet fortified wine from Molise",
  "quiz.1.options.3": "A sparkling wine made by the traditional method",
  "quiz.1.explanation": "Tintilia del Molise is the region's unique indigenous red grape, believed to have been introduced from Spain. It produces deep-coloured, tannic reds with genuine personality.",
  "quiz.2.question": "Approximately what percentage of Italian total wine production does Molise account for?",
  "quiz.2.options.0": "~5%",
  "quiz.2.options.1": "~0.5%",
  "quiz.2.options.2": "~2%",
  "quiz.2.options.3": "~10%",
  "quiz.2.explanation": "Molise produces less than 0.5% of Italy's total wine output — the smallest of any region — which is why it remains virtually unknown outside Italy.",
  "quiz.3.question": "Which is Molise's most celebrated producer?",
  "quiz.3.options.0": "Feudi di San Gregorio",
  "quiz.3.options.1": "Di Majo Norante",
  "quiz.3.options.2": "Mastroberardino",
  "quiz.3.options.3": "Cantele",
  "quiz.3.explanation": "Di Majo Norante is Molise's most respected estate — almost single-handedly responsible for raising the region's international profile through high-quality Tintilia and other wines."
})

print("Level 2 Module 1 and Module 2 EN overlays created successfully!")
