#!/usr/bin/env python3
"""Generate EN overlay JSON files for Italy Level 2 Module 3-5 lessons."""
import json, os

BASE = os.path.join(os.path.dirname(__file__), "..", "src", "locales", "en", "lessons", "italy")
os.makedirs(BASE, exist_ok=True)

def write(filename, data):
    path = os.path.join(BASE, filename)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"Created {filename}")

# ─── L2M3L1 Campania ──────────────────────────────────────────────────────────
write("L2M3L1.json", {
  "title": "Campania",
  "slides.0.title": "🌋 Campania",
  "slides.0.subtitle": "Cradle of Ancient Wine Culture",
  "slides.1.title": "🗺️ Campania Wine Region Map",
  "slides.2.title": "🗺️ Campania Wine Region Map (detail)",
  "slides.3.title": "🏛️ Cradle of Ancient Wine Culture",
  "slides.4.title": "🍇 Aglianico — King of the South",
  "slides.5.title": "🏆 Taurasi DOCG — Aglianico at Its Peak",
  "slides.6.title": "🍾 Campania's White Grape Trinity",
  "slides.7.title": "🌋 Volcanic Wine Appellations",
  "slides.8.title": "🍷 Other Important Campania Wines",
  "slides.9.title": "🍕 Napoli Cuisine and Food Pairings",
  "slides.10.title": "🏰 Campania Legendary and Boutique Producers",
  "slides.11.title": "💰 Campania Wine Price Guide",
  "slides.12.title": "🍽️ Campania Food Pairing & Wine Tourism",
  "slides.13.title": "📜 Campania Wine History (8th Century BC → 2025)",
  "slides.14.title": "🧬 Aglianico Variety Science and DNA Research",
  "slides.15.title": "🌋 Volcanic Soil Deep Dive (Vesuvius & Campi Flegrei)",
  "slides.16.title": "🏆 Taurasi DOCG vs Global Top Appellations",
  "slides.17.title": "🍾 Campania White Wine Innovation",
  "slides.18.title": "🏰 Legendary Campania Producers (Part 1)",
  "slides.19.title": "🌟 Boutique Campania Producers (Part 2) + Price Guide",
  "slides.20.title": "🗺️ Food Pairing Guide & Wine Tourism Routes",
  "slides.21.title": "🎓 Key Takeaways",
  "slides.22.title": "🧠 Campania Knowledge Check",
  "quiz.0.question": "Why is Aglianico called 'the Nebbiolo of the South'?",
  "quiz.0.options.0": "It originated in Piemonte and was brought south",
  "quiz.0.options.1": "Like Nebbiolo, it is a late-ripening, high-acid, high-tannin variety with great ageing potential",
  "quiz.0.options.2": "It has the same DNA as Nebbiolo",
  "quiz.0.options.3": "It requires the same amount of oak ageing as Barolo",
  "quiz.0.explanation": "Aglianico shares Nebbiolo's key characteristics: late ripening, powerful tannins, high acidity and exceptional longevity — making it the south's answer to the north's king.",
  "quiz.1.question": "What are Campania's three great white grapes?",
  "quiz.1.options.0": "Greco di Tufo, Fiano di Avellino, Falanghina",
  "quiz.1.options.1": "Vermentino, Garganega, Trebbiano",
  "quiz.1.options.2": "Cortese, Arneis, Verdicchio",
  "quiz.1.options.3": "Ribolla Gialla, Friulano, Malvasia",
  "quiz.1.explanation": "Campania's 'white trinity' — Greco di Tufo DOCG, Fiano di Avellino DOCG and Falanghina — are considered three of southern Italy's greatest white wines.",
  "quiz.2.question": "What is distinctive about Vesuvio DOC?",
  "quiz.2.options.0": "It produces only sparkling wines",
  "quiz.2.options.1": "Vineyards are planted on the slopes of Mount Vesuvius on volcanic soil",
  "quiz.2.options.2": "It is Campania's only DOCG",
  "quiz.2.options.3": "It is made exclusively from Aglianico",
  "quiz.2.explanation": "Vesuvio DOC (which includes the historic Lacryma Christi sub-zone) is grown on the volcanic slopes of Mount Vesuvius — giving wines a unique mineral and smoky character.",
  "quiz.3.question": "What is the minimum ageing requirement for Taurasi DOCG?",
  "quiz.3.options.0": "12 months",
  "quiz.3.options.1": "3 years (including 1 year in oak)",
  "quiz.3.options.2": "5 years",
  "quiz.3.options.3": "18 months",
  "quiz.3.explanation": "Taurasi DOCG requires a minimum of 3 years total ageing (at least 1 year in oak). Riserva requires 4 years — rivalling Barolo and Brunello in its demands."
})

# ─── L2M3L2 Puglia ────────────────────────────────────────────────────────────
write("L2M3L2.json", {
  "title": "Apulia (Puglia)",
  "slides.0.title": "📜 Puglia Wine History (Ancient → 2025 Revolution)",
  "slides.1.title": "🍇 Primitivo vs Zinfandel: Same Variety, Two Souls",
  "slides.2.title": "🌊 Puglia Terroir: Dual Coastline and Inland Hills",
  "slides.3.title": "🧬 Negroamaro Variety Science and Appellation Comparison",
  "slides.4.title": "🍷 Puglia Modern Winemaking Revolution (1990–2025)",
  "slides.5.title": "🏰 Legendary Puglia Producers (Part 1)",
  "slides.6.title": "🌟 Boutique Puglia Producers (Part 2) + Price Guide",
  "slides.7.title": "🍽️ Puglia Food Pairing Guide & Baroque Wine Tourism",
  "slides.8.title": "🌞 Apulia (Puglia)",
  "slides.8.subtitle": "Italy's Wine Powerhouse",
  "slides.9.title": "🗺️ Puglia Wine Region Map",
  "slides.10.title": "🏭 Italy's Largest (or Second-Largest) Wine-Producing Region",
  "slides.11.title": "🍇 Primitivo — Apulia's Star",
  "slides.12.title": "🏆 Primitivo's Two DOCGs",
  "slides.13.title": "🍷 Negroamaro — Apulia's Other Jewel",
  "slides.14.title": "⚪ Apulia White Wines",
  "slides.15.title": "🏰 Castel del Monte DOC",
  "slides.16.title": "🍽️ Apulia Cuisine and Food Pairings",
  "slides.17.title": "🎓 Key Takeaways",
  "slides.18.title": "🧠 Puglia Knowledge Check",
  "quiz.0.question": "Which Californian variety is genetically identical to Primitivo?",
  "quiz.0.options.0": "Petite Sirah",
  "quiz.0.options.1": "Zinfandel",
  "quiz.0.options.2": "Cabernet Sauvignon",
  "quiz.0.options.3": "Grenache",
  "quiz.0.explanation": "DNA studies confirmed that Primitivo and Californian Zinfandel are genetically identical — both originating from the Croatian variety Crljenak Kaštelanski.",
  "quiz.1.question": "What does the name Negroamaro mean?",
  "quiz.1.options.0": "Black and bitter",
  "quiz.1.options.1": "'Black' (from Italian 'nero') and 'bitter' (from Italian 'amaro')",
  "quiz.1.options.2": "'Dark' in Greek and 'sweet' in Arabic",
  "quiz.1.options.3": "Named after the Negros family of winemakers",
  "quiz.1.explanation": "Negroamaro means 'black-bitter' — nero (black) for the grape's deep colour and amaro (bitter) for its characteristically dry, slightly bitter finish.",
  "quiz.2.question": "What is the typical alcohol content of Primitivo di Manduria Dolce Naturale DOCG?",
  "quiz.2.options.0": "12.5%",
  "quiz.2.options.1": "17.5% minimum",
  "quiz.2.options.2": "14.5%",
  "quiz.2.options.3": "20%",
  "quiz.2.explanation": "Primitivo di Manduria Dolce Naturale DOCG is a naturally sweet wine with a minimum alcohol of 17.5% — one of Italy's most powerful naturally sweet red wines.",
  "quiz.3.question": "What is Orecchiette?",
  "quiz.3.options.0": "A Puglia dessert",
  "quiz.3.options.1": "Ear-shaped pasta — Puglia's iconic pasta shape",
  "quiz.3.options.2": "A Puglia aperitivo",
  "quiz.3.options.3": "A type of focaccia bread",
  "quiz.3.explanation": "Orecchiette ('little ears' in Italian) is Puglia's signature pasta — small, ear-shaped pasta traditionally served with cime di rapa (turnip tops) and orecchiette con le cime di rapa is Puglia's most iconic dish."
})

# ─── L2M3L3 Basilicata ────────────────────────────────────────────────────────
write("L2M3L3.json", {
  "title": "Basilicata",
  "slides.0.title": "🌋 Basilicata",
  "slides.0.subtitle": "Italy's Poorest but Proudest Region",
  "slides.1.title": "📍 Basilicata Wine Region Map",
  "slides.2.title": "🏆 Italy's Poorest but Proudest Wine Region",
  "slides.3.title": "🌋 Aglianico del Vulture DOCG",
  "slides.4.title": "⚖️ Aglianico del Vulture vs Taurasi",
  "slides.5.title": "🍷 Other Basilicata Wines",
  "slides.6.title": "🍾 Aglianico del Vulture Spumante",
  "slides.7.title": "🍽️ Basilicata Cuisine and Food Pairings",
  "slides.8.title": "🎓 Key Takeaways",
  "slides.9.title": "📜 Basilicata Wine History — Deep Dive",
  "slides.10.title": "🧬 Aglianico Variety Science",
  "slides.11.title": "🌋 Monte Vulture Volcanic Terroir Science",
  "slides.12.title": "🔍 Aglianico del Vulture Appellation — Deep Dive",
  "slides.13.title": "🏰 Legendary Producers",
  "slides.14.title": "🍽️ Food Pairing + Wine Tourism Guide",
  "slides.15.title": "(Extended content)",
  "slides.16.title": "🧠 Basilicata Knowledge Check",
  "quiz.0.question": "What geological environment does Aglianico del Vulture grow in?",
  "quiz.0.options.0": "Limestone and clay on the coast",
  "quiz.0.options.1": "Ancient volcanic soils on the slopes of Monte Vulture",
  "quiz.0.options.2": "Sandy soils on river plains",
  "quiz.0.options.3": "Glacial moraine in mountain valleys",
  "quiz.0.explanation": "Aglianico del Vulture DOCG grows on the ancient volcanic soils of Monte Vulture — an extinct volcano. The volcanic ash-rich basaltic soils give the wine its unique mineral complexity.",
  "quiz.1.question": "How long must Aglianico del Vulture Superiore Riserva be aged?",
  "quiz.1.options.0": "2 years",
  "quiz.1.options.1": "5 years (including at least 1 year in bottle)",
  "quiz.1.options.2": "3 years",
  "quiz.1.options.3": "7 years",
  "quiz.1.explanation": "Aglianico del Vulture Superiore Riserva requires a minimum of 5 years total ageing — demonstrating the wine's exceptional longevity and seriousness.",
  "quiz.2.question": "What is the main difference between Aglianico del Vulture and Taurasi?",
  "quiz.2.options.0": "They are made from completely different grape varieties",
  "quiz.2.options.1": "Aglianico del Vulture has higher acidity and a more volcanic mineral character; Taurasi is more structured and tannic",
  "quiz.2.options.2": "Taurasi is made in the north; Aglianico del Vulture in the south",
  "quiz.2.options.3": "Aglianico del Vulture is always sweeter",
  "quiz.2.explanation": "Both use Aglianico but on different terroirs: Basilicata's volcanic soils give del Vulture a more volcanic mineral character and higher acidity; Campania's Irpinia hills give Taurasi greater structure.",
  "quiz.3.question": "What is Basilicata cuisine's signature spice?",
  "quiz.3.options.0": "Saffron",
  "quiz.3.options.1": "Peperoncino (chilli pepper)",
  "quiz.3.options.2": "Cinnamon",
  "quiz.3.options.3": "Cloves",
  "quiz.3.explanation": "Basilicata (and neighbouring Calabria) cuisines are defined by peperoncino — chilli pepper — used liberally in sausages, cheeses and sauces, reflecting the region's bold character."
})

# ─── L2M3L4 Calabria ──────────────────────────────────────────────────────────
write("L2M3L4.json", {
  "title": "Calabria",
  "slides.0.title": "🌊 Calabria",
  "slides.0.subtitle": "Italy's 'Toe'",
  "slides.1.title": "📍 Calabria Wine Region Map",
  "slides.2.title": "👢 Italy's 'Toe'",
  "slides.3.title": "🏆 Cirò DOC — Calabria's Most Famous Appellation",
  "slides.4.title": "🍷 Gaglioppo — Calabria's King of Red Grapes",
  "slides.5.title": "🍇 Other Native Calabrian Varieties",
  "slides.6.title": "🍯 Greco di Bianco DOC — A Rare Sweet White",
  "slides.7.title": "🍷 Other Important Calabria DOCs",
  "slides.8.title": "🍽️ Calabria Cuisine and Food Pairings",
  "slides.9.title": "🎓 Key Takeaways",
  "slides.10.title": "📜 Calabria Wine History — Deep Dive",
  "slides.11.title": "🧬 Gaglioppo Variety Science",
  "slides.12.title": "🌍 Cirò Appellation Terroir Science",
  "slides.13.title": "🏺 Calabria Native Variety Treasury",
  "slides.14.title": "🏰 Five Legendary Producers",
  "slides.15.title": "🌶️ 'Nduja Food Culture + Food Pairing + Dual-Sea Tourism",
  "slides.16.title": "🧠 Calabria Knowledge Check",
  "quiz.0.question": "What legend is Cirò DOC associated with?",
  "quiz.0.options.0": "It was the wine offered to the gods of Olympus",
  "quiz.0.options.1": "It was supposedly the Krimisa wine drunk by athletes at the ancient Greek Olympics",
  "quiz.0.options.2": "It was favoured by Julius Caesar",
  "quiz.0.options.3": "It was the wine of the Norman kings of Sicily",
  "quiz.0.explanation": "Legend holds that Cirò (known as Krimisa in ancient Greek times) was the wine given to victorious athletes at the ancient Greek Olympics — making it one of the world's oldest wine traditions.",
  "quiz.1.question": "Why is Gaglioppo called 'the Pinot Noir of the South'?",
  "quiz.1.options.0": "It has the same DNA as Pinot Noir",
  "quiz.1.options.1": "Like Pinot Noir, it has a pale colour, high acidity and elegant rather than powerful character",
  "quiz.1.options.2": "It is grown on granite soils like Burgundy",
  "quiz.1.options.3": "It was imported from Burgundy in the 18th century",
  "quiz.1.explanation": "Gaglioppo shares Pinot Noir's paradox: it has a pale, translucent colour despite producing deeply flavoured wines with high acidity, delicate tannins and aromatic complexity.",
  "quiz.2.question": "What is the typical alcohol content of Greco di Bianco DOC?",
  "quiz.2.options.0": "12.5%",
  "quiz.2.options.1": "17% or above",
  "quiz.2.options.2": "15%",
  "quiz.2.options.3": "10.5%",
  "quiz.2.explanation": "Greco di Bianco is a passito sweet wine made from sun-dried Greco Bianco grapes — one of Calabria's rarest wines with typically 17%+ alcohol and intense apricot and honey flavours.",
  "quiz.3.question": "What is 'Nduja?",
  "quiz.3.options.0": "A Calabria dessert",
  "quiz.3.options.1": "A spicy, spreadable pork salami from Spilinga, Calabria",
  "quiz.3.options.2": "A type of pasta",
  "quiz.3.options.3": "A Calabrian cheese",
  "quiz.3.explanation": "'Nduja is Calabria's most famous food product — a fiery, spreadable salami made from pork and Calabrian chilli peppers, from the town of Spilinga. It has become globally celebrated."
})

# ─── L2M3L5 Sardinia ──────────────────────────────────────────────────────────
write("L2M3L5.json", {
  "title": "Sardinia (Sardegna)",
  "slides.0.title": "🏝️ Sardinia (Sardegna)",
  "slides.0.subtitle": "The Mediterranean's Second Largest Island",
  "slides.1.title": "📍 Sardinia Wine Region Map",
  "slides.2.title": "🏝️ The Mediterranean's Second Largest Island",
  "slides.3.title": "📜 500 Years of Spanish Rule — Sardinia's Heritage",
  "slides.4.title": "🧬 Cannonau Variety Science — Grenache in Sardinia",
  "slides.5.title": "💎 Vermentino di Gallura DOCG — Granite Terroir's White Treasure",
  "slides.6.title": "🌿 Carignano del Sulcis — Old Vine Miracle",
  "slides.7.title": "🍶 Vernaccia di Oristano — Sardinia's Sherry",
  "slides.8.title": "🍷 Cannonau — King of Sardinia",
  "slides.9.title": "⭐ Vermentino — Sardinia's White Star",
  "slides.10.title": "🌿 Carignano del Sulcis DOC",
  "slides.11.title": "🍇 Other Native Sardinian Varieties",
  "slides.12.title": "🍯 Sardinia's Sweet Wine Tradition",
  "slides.13.title": "🍽️ Sardinian Cuisine and Food Pairings",
  "slides.14.title": "🎓 Key Takeaways",
  "slides.15.title": "🌟 Sardinian Cuisine and Luxury Tourism Guide",
  "slides.16.title": "🧠 Sardinia Knowledge Check",
  "quiz.0.question": "Which international variety is Cannonau genetically identical to?",
  "quiz.0.options.0": "Syrah",
  "quiz.0.options.1": "Grenache (Garnacha)",
  "quiz.0.options.2": "Carignan",
  "quiz.0.options.3": "Monastrell (Mourvèdre)",
  "quiz.0.explanation": "Cannonau is the Sardinian name for Grenache/Garnacha. DNA studies suggest Sardinia may actually be the grape's original homeland — predating its cultivation in Spain and France.",
  "quiz.1.question": "What makes Vermentino di Gallura DOCG special?",
  "quiz.1.options.0": "It is Sardinia's only red wine DOCG",
  "quiz.1.options.1": "It is the only DOCG in Sardinia and southern Italy for a white wine — grown on ancient granite soils",
  "quiz.1.options.2": "It is made using the Metodo Classico",
  "quiz.1.options.3": "It must be aged for a minimum of 10 years",
  "quiz.1.explanation": "Vermentino di Gallura DOCG is noteworthy as the only DOCG in Sardinia and one of very few white wine DOCGs in southern Italy — grown on the ancient granite soils of northern Sardinia (Gallura).",
  "quiz.2.question": "What is distinctive about Carignano del Sulcis?",
  "quiz.2.options.0": "It is made from international varieties only",
  "quiz.2.options.1": "Many vines are ungrafted, pre-phylloxera, planted in sandy soils — some over 100 years old",
  "quiz.2.options.2": "It is always made as a sparkling wine",
  "quiz.2.options.3": "It can only be made as a sweet wine",
  "quiz.2.explanation": "The Sulcis area's sandy soils protected vines from phylloxera, so many Carignano del Sulcis vines are old, ungrafted (on their own roots) — producing extraordinarily concentrated wines.",
  "quiz.3.question": "What is Bottarga?",
  "quiz.3.options.0": "A Sardinian pasta dish",
  "quiz.3.options.1": "Cured, salted and dried mullet or tuna roe — Sardinia's 'Mediterranean caviar'",
  "quiz.3.options.2": "A sheep's milk cheese from Sardinia",
  "quiz.3.options.3": "A sweet pastry from Cagliari",
  "quiz.3.explanation": "Bottarga — cured, dried mullet roe — is one of Sardinia's most prized food products, used grated over pasta or eaten in thin slices. It pairs magnificently with Vermentino di Gallura."
})

# ─── L2M4L1 Northern Italian Classic Varieties ────────────────────────────────
write("L2M4L1.json", {
  "title": "Northern Italian Classic Varieties — Deep Study",
  "slides.0.title": "🍇 Northern Italian Classic Varieties — Deep Study",
  "slides.1.title": "🍷 Nebbiolo — Italy's Noble King",
  "slides.2.title": "🍇 Barbera — Italy's Everyday Hero",
  "slides.3.title": "🍇 Dolcetto — The Underrated Sweet One",
  "slides.4.title": "🍇 Corvina — The Soul of Amarone",
  "slides.5.title": "🍇 Sangiovese — King of Central Italy",
  "slides.6.title": "🍇 Aglianico — King of Southern Italy",
  "slides.7.title": "🎓 Key Takeaways",
  "slides.8.title": "🧠 Northern Italian Variety Deep Knowledge Check",
  "quiz.0.question": "Why does Nebbiolo perform brilliantly almost exclusively in Piemonte?",
  "quiz.0.options.0": "It can only grow in cold climates",
  "quiz.0.options.1": "It requires specific marl-calcareous soils, a very late-ripening season and Piemonte's particular fog (nebbia) to achieve full maturity",
  "quiz.0.options.2": "It is legally restricted to Piemonte",
  "quiz.0.options.3": "It is grafted onto rootstocks that only survive in Piemonte",
  "quiz.0.explanation": "Nebbiolo needs Piemonte's marl-calcareous Langhe soils and a specific microclimate to ripen its thick skin fully — even though it has been planted worldwide, it rarely achieves the same heights outside Piemonte.",
  "quiz.1.question": "What is Barbera's most distinctive characteristic?",
  "quiz.1.options.0": "Very high tannins",
  "quiz.1.options.1": "Naturally high acidity with low tannins — the most food-friendly Italian variety",
  "quiz.1.options.2": "Very low acidity",
  "quiz.1.options.3": "An intense floral bouquet",
  "quiz.1.explanation": "Barbera is defined by its naturally high acidity and low tannins — making it ideal with rich, acidic foods like tomato-based pasta. With barrel ageing, it develops considerable complexity.",
  "quiz.2.question": "Sangiovese Grosso is principally used in which DOCG?",
  "quiz.2.options.0": "Chianti Classico DOCG",
  "quiz.2.options.1": "Brunello di Montalcino DOCG",
  "quiz.2.options.2": "Vino Nobile di Montepulciano DOCG",
  "quiz.2.options.3": "Morellino di Scansano DOCG",
  "quiz.2.explanation": "Sangiovese Grosso (known locally as Brunello) is the variety used for Brunello di Montalcino DOCG — one of Italy's greatest and most age-worthy red wines.",
  "quiz.3.question": "Why is Aglianico called 'the Nebbiolo of the South'?",
  "quiz.3.options.0": "It is a light-coloured variety with floral aromas",
  "quiz.3.options.1": "Both are late-ripening, high-acid, high-tannin varieties with long ageing potential that only excel in their native region",
  "quiz.3.options.2": "It has the same DNA as Nebbiolo",
  "quiz.3.options.3": "Both are grown exclusively in the Alps",
  "quiz.3.explanation": "Aglianico and Nebbiolo share the same winemaking profile: late ripening, high acidity, high tannins and extraordinary ageing potential — both thriving in their specific volcanic (Aglianico) or marl-calcareous (Nebbiolo) soils."
})

# ─── L2M4L2 Central Italian Varieties ────────────────────────────────────────
write("L2M4L2.json", {
  "title": "Central Italian Varieties and Terroir",
  "slides.0.title": "🍇 Central Italian Varieties and Terroir",
  "slides.1.title": "🍾 Verdicchio — Italy's Chardonnay",
  "slides.2.title": "🍇 Montepulciano — The Confused Variety",
  "slides.3.title": "🍷 Sagrantino — King of Tannins",
  "slides.4.title": "🌿 Vermentino — Mediterranean Fragrance",
  "slides.5.title": "🍾 Trebbiano — Italy's Workhorse",
  "slides.6.title": "🧀 Pecorino — Not a Cheese",
  "slides.7.title": "🎓 Key Takeaways",
  "slides.8.title": "🧠 Central Italian Variety Deep Knowledge Check",
  "quiz.0.question": "What is Verdicchio's ageing potential?",
  "quiz.0.options.0": "Up to 3 years",
  "quiz.0.options.1": "10–15 years or more for top producers",
  "quiz.0.options.2": "5 years maximum",
  "quiz.0.options.3": "Verdicchio does not age well",
  "quiz.0.explanation": "Top-quality Verdicchio (especially Matelica DOCG Riserva) can age 10–20 years, developing extraordinary complexity — comparable to white Burgundy.",
  "quiz.1.question": "What is the primary variety of Vino Nobile di Montepulciano DOCG?",
  "quiz.1.options.0": "A variety called Montepulciano",
  "quiz.1.options.1": "Prugnolo Gentile (a clone of Sangiovese) — minimum 70%",
  "quiz.1.options.2": "Brunello (Sangiovese Grosso)",
  "quiz.1.options.3": "Aglianico",
  "quiz.1.explanation": "Despite its name, Vino Nobile di Montepulciano uses Prugnolo Gentile (a Sangiovese clone, minimum 70%) — not the 'Montepulciano' grape variety. This is one of Italian wine's most persistent confusions.",
  "quiz.2.question": "Why does Sagrantino have the world's highest tannin content?",
  "quiz.2.options.0": "The wine is always aged for very long periods",
  "quiz.2.options.1": "The grape has uniquely high concentrations of proanthocyanidins (condensed tannins) in its thick skins",
  "quiz.2.options.2": "Winemakers add tannin powder during production",
  "quiz.2.options.3": "It is always fermented with stems",
  "quiz.2.explanation": "Sagrantino's extraordinarily thick skins contain an exceptionally high concentration of proanthocyanidins (condensed tannins) — a genetic characteristic unique to this variety.",
  "quiz.3.question": "Why is Pecorino grape called Pecorino?",
  "quiz.3.options.0": "It smells like cheese",
  "quiz.3.options.1": "Sheep (pecora) used to graze on the grapes during harvest, and shepherds also brought the vines across regions",
  "quiz.3.options.2": "It was discovered by a cheesemaker",
  "quiz.3.options.3": "Its leaves look like sheep's wool",
  "quiz.3.explanation": "Pecorino grape gets its name from sheep (pecora in Italian) — the animals used to eat the ripe, sweet grapes. Migratory shepherds also helped spread the vine across central Italy."
})

# ─── L2M4L3 Southern Italian Native Varieties ────────────────────────────────
write("L2M4L3.json", {
  "title": "Southern Italy's Native Variety Treasury",
  "slides.0.title": "🍇 Southern Italy's Native Variety Treasury",
  "slides.1.title": "🍇 Primitivo — Zinfandel's Italian Twin",
  "slides.2.title": "🍷 Negroamaro — 'Doubly Black'",
  "slides.3.title": "🍷 Nero d'Avola — King of Sicily",
  "slides.4.title": "🌸 Frappato — Sicily's Elegance",
  "slides.5.title": "⭐ Fiano — Campania's White Star",
  "slides.6.title": "🏛️ Greco — Campania's Greek Heritage",
  "slides.7.title": "🌿 Falanghina — The Revived Ancient Variety",
  "slides.8.title": "🎓 Key Takeaways",
  "slides.9.title": "🧠 Southern Italian Variety Knowledge Check",
  "quiz.0.question": "Why is Primitivo called 'Primitivo'?",
  "quiz.0.options.0": "Because it produces very simple, 'primitive' wines",
  "quiz.0.options.1": "From 'primativo' — it ripens among the earliest of all Italian varieties",
  "quiz.0.options.2": "Because it was one of the first varieties planted in Italy",
  "quiz.0.options.3": "Because it was grown by primitive peoples",
  "quiz.0.explanation": "Primitivo comes from 'primativo' — meaning early-ripening. It is one of the earliest-ripening varieties in Italy, harvested in August in some areas.",
  "quiz.1.question": "What does the name Negroamaro mean?",
  "quiz.1.options.0": "Black grape from the sea",
  "quiz.1.options.1": "'Black' (nero) + 'bitter' (amaro) — describing the grape's deep colour and dry, bitter finish",
  "quiz.1.options.2": "Dark soil grape",
  "quiz.1.options.3": "Ancient black vine",
  "quiz.1.explanation": "Negroamaro literally means 'black-bitter': nero (Italian: black) for its deep, inky colour and amaro (Italian: bitter) for its characteristically dry, slightly bitter tannins.",
  "quiz.2.question": "What is the blend ratio for Cerasuolo di Vittoria DOCG?",
  "quiz.2.options.0": "100% Nero d'Avola",
  "quiz.2.options.1": "50–70% Nero d'Avola + 30–50% Frappato",
  "quiz.2.options.2": "80% Frappato + 20% Nero d'Avola",
  "quiz.2.options.3": "Equal parts Frappato and Cataratto",
  "quiz.2.explanation": "Cerasuolo di Vittoria DOCG (Sicily's only DOCG) requires 50–70% Nero d'Avola blended with 30–50% Frappato — combining power with elegance.",
  "quiz.3.question": "Why did ancient Romans call Fiano 'Vitis Apiana'?",
  "quiz.3.options.0": "Because it originated in the Apennine mountains",
  "quiz.3.options.1": "Because bees (api) were irresistibly attracted to its sweet, ripe berries at harvest",
  "quiz.3.options.2": "Because it was the favourite wine of the god Apollo",
  "quiz.3.options.3": "Because it was cultivated in the Apia region",
  "quiz.3.explanation": "The Romans called Fiano 'Vitis Apiana' — 'the vine of bees' — because bees were irresistibly attracted to the intensely aromatic, honeyed berries. Fiano di Avellino DOCG is a direct descendant."
})

# ─── L2M4L4 Italian Varieties on the International Stage ─────────────────────
write("L2M4L4.json", {
  "title": "Italian Varieties on the International Stage",
  "slides.0.title": "🌍 Italian Varieties on the International Stage",
  "slides.1.title": "🌐 Italian Varieties — The Global Picture",
  "slides.2.title": "🇺🇸 United States: New World Experiments with Italian Varieties",
  "slides.3.title": "🇦🇺 Australia: Experimentation and Sangiovese",
  "slides.4.title": "🇦🇷 Argentina: High-Altitude Barbera and Sangiovese",
  "slides.5.title": "🌎 Italian Varieties in Other Countries",
  "slides.6.title": "🌟 Global Success Story: Prosecco",
  "slides.7.title": "🎓 Key Takeaways",
  "slides.8.title": "🧠 White Variety Advanced Knowledge Check",
  "quiz.0.question": "Why are Italian varieties difficult to internationalise?",
  "quiz.0.options.0": "They are too expensive to grow",
  "quiz.0.options.1": "High acidity and tannins require specific terroir and cuisine to show their best; they can taste harsh without the right food context",
  "quiz.0.options.2": "Italy's wine laws prohibit export of cuttings",
  "quiz.0.options.3": "They cannot survive cold winters",
  "quiz.0.explanation": "Italian varieties evolved alongside Italian cuisine — their high acidity and tannins are assets at the dining table but can seem unbalanced as 'standalone' wines in markets without a complementary food culture.",
  "quiz.1.question": "In which Californian appellation is Sangiovese most successful?",
  "quiz.1.options.0": "Napa Valley",
  "quiz.1.options.1": "Atlas Peak (Napa) and Sonoma County",
  "quiz.1.options.2": "Central Valley",
  "quiz.1.options.3": "Paso Robles",
  "quiz.1.explanation": "Atlas Peak in the Napa Valley (known as California's 'Chianti zone') has achieved the best results with Sangiovese, though Sonoma also produces notable examples.",
  "quiz.2.question": "Argentina's Bonarda is actually which Italian variety?",
  "quiz.2.options.0": "Barbera",
  "quiz.2.options.1": "Dolcetto",
  "quiz.2.options.2": "Charbono (Douce Noire) — from Valle d'Aosta, not strictly 'Bonarda'",
  "quiz.2.options.3": "Freisa",
  "quiz.2.explanation": "Argentine 'Bonarda' is actually Douce Noire (Charbono), a variety from north-western Italy (Valle d'Aosta / Savoy) — unrelated to Piemonte's Bonarda Piemontese. It is Argentina's second most planted red variety.",
  "quiz.3.question": "Which of the following is NOT a key factor in Prosecco's global success?",
  "quiz.3.options.0": "Low price point and approachable style",
  "quiz.3.options.1": "Prosecco DOCG is the world's largest sparkling appellation by volume",
  "quiz.3.options.2": "Its use as a luxury product in high-end Cocktail culture",
  "quiz.3.options.3": "Its use as the base for the Aperol Spritz cocktail",
  "quiz.3.explanation": "Prosecco's global rise was driven by its accessible price, light fruity style and its role in the Aperol Spritz — not as a luxury product. The Spritz became the world's most popular cocktail, driving Prosecco demand globally."
})

# ─── L2M5L1 Italian Cuisine and Food Pairing Principles ──────────────────────
write("L2M5L1.json", {
  "title": "Italian Cuisine and Food Pairing Principles",
  "slides.0.title": "🍽️ Italian Cuisine and Food Pairing Principles",
  "slides.1.title": "🗺️ Italian Food Pairing Philosophy: Regionalism",
  "slides.2.title": "🍷 Six Core Italian Food Pairing Principles",
  "slides.3.title": "🍝 Pasta Sauce and Wine Pairing Guide",
  "slides.4.title": "🧀 Italian Cheese and Wine Quick Reference",
  "slides.5.title": "🎓 Key Takeaways",
  "slides.6.title": "🧠 Food Pairing Knowledge Check",
  "quiz.0.question": "What is the supreme principle of Italian food pairing?",
  "quiz.0.options.0": "Red wine with meat, white wine with fish",
  "quiz.0.options.1": "'What grows together, goes together' — regional pairing always first",
  "quiz.0.options.2": "Always choose the most expensive wine",
  "quiz.0.options.3": "Match the weight of food and wine",
  "quiz.0.explanation": "Italian food pairing begins with regional identity — the local wine always evolved alongside the local food. Pairing Barolo with Piedmontese cuisine, Chianti with Florentine steak, is always the starting point.",
  "quiz.1.question": "Why do tomato-based dishes need high-acid wines?",
  "quiz.1.options.0": "To complement the sweetness of the tomatoes",
  "quiz.1.options.1": "Because low-acid wine tastes flat and watery beside the tomato's natural acidity",
  "quiz.1.options.2": "To neutralise the tomato's acidity",
  "quiz.1.options.3": "Because tomato dishes are always very spicy",
  "quiz.1.explanation": "Tomatoes have significant natural acidity. A wine lower in acidity will taste flat and thin when compared with the tomato's sharpness — you need matching or higher acidity to keep the wine fresh.",
  "quiz.2.question": "Why do rich, fatty meats need high-tannin red wines?",
  "quiz.2.options.0": "Tannins enhance the sweetness of the fat",
  "quiz.2.options.1": "Tannins bind to proteins in the fat, cutting through richness and cleansing the palate",
  "quiz.2.options.2": "High-tannin wines taste smoother with fatty food",
  "quiz.2.options.3": "Fat-rich foods require wines with high alcohol",
  "quiz.2.explanation": "Tannins are astringent compounds that bind to fat molecules and proteins — literally cutting through richness and refreshing the palate. Without tannins, fatty food makes wine taste unpleasantly soft.",
  "quiz.3.question": "What is the correct rule for pairing wine with dessert?",
  "quiz.3.options.0": "Always serve dry red wine with dessert",
  "quiz.3.options.1": "The wine must be at least as sweet as — or sweeter than — the dessert",
  "quiz.3.options.2": "Champagne always pairs with any dessert",
  "quiz.3.options.3": "Dessert and wine should never be served together",
  "quiz.3.explanation": "The cardinal rule: when pairing wine with dessert, the wine must be at least as sweet as the dessert. If the dessert is sweeter, the wine tastes thin, bitter and acidic by comparison."
})

# ─── L2M5L2 Italian Cheese and Wine Pairing ──────────────────────────────────
write("L2M5L2.json", {
  "title": "Italian Cheese and Wine Pairing",
  "slides.0.title": "🧀 Italian Cheese and Wine Pairing",
  "slides.1.title": "🗺️ Overview of Italian Cheeses",
  "slides.2.title": "🥛 Fresh Cheese",
  "slides.3.title": "🧀 Semi-Soft Cheese",
  "slides.4.title": "🪨 Hard Cheese",
  "slides.5.title": "🔵 Blue Cheese",
  "slides.6.title": "⏳ Aged Cheese",
  "slides.7.title": "🎓 Key Takeaways",
  "slides.8.title": "🧠 Investment and Collecting Knowledge Check",
  "quiz.0.question": "Why does Burrata pair well with sparkling wine?",
  "quiz.0.options.0": "Sparkling wine's sweetness complements Burrata's richness",
  "quiz.0.options.1": "The bubbles and acidity cut through the cream, refreshing the palate",
  "quiz.0.options.2": "Sparkling wine enhances the salty flavour",
  "quiz.0.options.3": "Burrata's tangy flavour matches the yeasty notes of sparkling wine",
  "quiz.0.explanation": "Burrata is extremely rich and creamy. Sparkling wine's carbonation and crisp acidity provide contrast — cutting through the fat and leaving the palate fresh for the next bite.",
  "quiz.1.question": "What is the best pairing for 60+ months aged Parmigiano Reggiano?",
  "quiz.1.options.0": "Light fresh Pinot Grigio",
  "quiz.1.options.1": "Aged Barolo or Amarone — the tannins and richness match the crystalline, intense cheese",
  "quiz.1.options.2": "Sweet Moscato d'Asti",
  "quiz.1.options.3": "Young Barbera d'Asti",
  "quiz.1.explanation": "60+ month Parmigiano is extraordinarily concentrated and complex. Only a wine of equivalent stature — aged Barolo, Brunello or Amarone — can match its intensity without being overwhelmed.",
  "quiz.2.question": "Why does Gorgonzola Dolce pair with Moscato d'Asti?",
  "quiz.2.options.0": "Both are from Piemonte — regional pairing",
  "quiz.2.options.1": "The sweetness contrasts the blue mould's saltiness and bitterness, creating a classic 'sweet and salty' balance",
  "quiz.2.options.2": "Both have very low alcohol",
  "quiz.2.options.3": "Moscato's bubbles clean the palate",
  "quiz.2.explanation": "Sweet wines with blue cheeses is one of the world's great pairings — the wine's sweetness counterbalances the cheese's saltiness and pungency, while the wine's acidity prevents the pairing from becoming cloying.",
  "quiz.3.question": "Applying the regional pairing principle, what is the best wine for Pecorino Romano?",
  "quiz.3.options.0": "Pinot Grigio from Friuli",
  "quiz.3.options.1": "Cesanese del Piglio or Frascati — wines from Lazio, the same region as the cheese",
  "quiz.3.options.2": "Barolo from Piemonte",
  "quiz.3.options.3": "Prosecco from Veneto",
  "quiz.3.explanation": "Pecorino Romano is from Lazio (and Sardinia). The regional pairing principle suggests pairing it with local wines — Cesanese del Piglio for the red or Frascati for the white."
})

# ─── L2M5L3 Italian Seasonal Food Pairing ────────────────────────────────────
write("L2M5L3.json", {
  "title": "Italian Seasonal Food Pairing",
  "slides.0.title": "🌸 Italian Seasonal Food Pairing",
  "slides.1.title": "🍽️ Italy's Seasonal Food Culture",
  "slides.2.title": "🌸 Spring (Primavera) Pairings",
  "slides.3.title": "☀️ Summer (Estate) Pairings",
  "slides.4.title": "🍂 Autumn (Autunno) Pairings",
  "slides.5.title": "❄️ Winter (Inverno) Pairings",
  "slides.6.title": "🎓 Key Takeaways",
  "slides.7.title": "🧠 Auction Market Knowledge Check",
  "quiz.0.question": "Why does Italy emphasise seasonal eating (Stagionalità)?",
  "quiz.0.options.0": "For economic reasons — seasonal produce is cheaper",
  "quiz.0.options.1": "Because seasonal ingredients are at their peak flavour, and Italian food culture is built around celebrating this freshness",
  "quiz.0.options.2": "Because of religious dietary laws",
  "quiz.0.options.3": "Because imported produce is not available",
  "quiz.0.explanation": "Stagionalità (seasonality) is fundamental to Italian culinary identity — using ingredients at their natural peak not only maximises flavour but connects the meal to the land and the season.",
  "quiz.1.question": "Which of the following is NOT a typical Italian summer Rosato (rosé) recommendation?",
  "quiz.1.options.0": "Cerasuolo d'Abruzzo",
  "quiz.1.options.1": "Salice Salentino Rosato",
  "quiz.1.options.2": "Bardolino Chiaretto",
  "quiz.1.options.3": "Amarone della Valpolicella",
  "quiz.1.explanation": "Amarone della Valpolicella is a powerful, full-bodied red wine (minimum 17% alcohol) — the opposite of a light summer rosé. The other three are classic Italian summer rosés.",
  "quiz.2.question": "What is the white truffle (Tartufo Bianco) season, and what is the ideal wine pairing?",
  "quiz.2.options.0": "Spring — light white wine",
  "quiz.2.options.1": "Autumn (October–December) — aged Barolo, Barbaresco or aged white Burgundy",
  "quiz.2.options.2": "Summer — young Pinot Grigio",
  "quiz.2.options.3": "Winter — sweet Passito wine",
  "quiz.2.explanation": "White truffles (from Alba in Piemonte) are harvested October–December. Their extraordinary earthy, musky, garlicky intensity requires the complexity of aged Barolo, Barbaresco or equivalent greatness.",
  "quiz.3.question": "On what date is Vino Novello (new wine) released in Italy?",
  "quiz.3.options.0": "1 October",
  "quiz.3.options.1": "6 November",
  "quiz.3.options.2": "1 December",
  "quiz.3.options.3": "14 February",
  "quiz.3.explanation": "Italian Vino Novello is released on 6 November — slightly later than Beaujolais Nouveau (third Thursday of November). Made by carbonic maceration, it is light, fruity and meant to be drunk immediately."
})

print("Level 2 Module 3, 4, 5 EN overlays created successfully!")
