import json, pathlib

f = pathlib.Path("src/locales/en/lessons/bordeaux/l4-4.json")
data = json.loads(f.read_text(encoding="utf-8"))

data["slides.0.title"] = "Learning Objectives"
data["slides.1.title"] = "Chapter 1"
data["slides.1.subtitle"] = "Cost Map"
data["slides.2.title"] = "Chapter 1: Cost Map and Data Foundations"
data["slides.2.highlights.0.title"] = "ABC Cost Pools"
data["slides.2.highlights.0.content"] = "Break costs into activity pools for more precise unit economics calculation."
data["slides.2.highlights.1.title"] = "Data Pipeline"
data["slides.2.highlights.1.content"] = "ERP + WMS + finance system builds the cost dashboard."
data["slides.2.highlights.2.title"] = "Case: Cost Reduction"
data["slides.2.highlights.2.content"] = "After optimising barrel ageing management, cost per bottle dropped by €8."
data["slides.3.title"] = "Chapter 2"
data["slides.3.subtitle"] = "CAPEX"
data["slides.4.title"] = "Chapter 2: CAPEX Planning and Asset Lifespan"
data["slides.4.highlights.0.title"] = "Asset Classification"
data["slides.4.highlights.0.content"] = "Barrels, concrete tanks, solar and sorting line CAPEX and depreciation strategies."
data["slides.4.highlights.1.title"] = "Cash Flow Matching"
data["slides.4.highlights.1.content"] = "Depreciation affects tax; must be matched against maintenance costs and savings."
data["slides.4.highlights.2.title"] = "Financing Structure"
data["slides.4.highlights.2.content"] = "Blend of own funds, loans, grants and leasing."
data["slides.5.title"] = "Chapter 3"
data["slides.5.subtitle"] = "Break-Even"
data["slides.6.title"] = "Chapter 3: Unit Economics and Break-Even Analysis"
data["slides.6.highlights.0.title"] = "Contribution Margin"
data["slides.6.highlights.0.content"] = "ASP €18.5 vs variable cost €7.8 gives contribution margin of €10.7."
data["slides.6.highlights.1.title"] = "Break-Even Dashboard"
data["slides.6.highlights.1.content"] = "Switch between price or efficiency scenarios to compare break-even volumes."
data["slides.6.highlights.2.title"] = "Margin of Safety"
data["slides.6.highlights.2.content"] = "Push margin of safety to ≥20% to reduce market volatility risk."
data["slides.7.title"] = "Chapter 4"
data["slides.7.subtitle"] = "Sensitivity"
data["slides.8.title"] = "Chapter 4: Sensitivity and Scenario Analysis"
data["slides.8.highlights.0.title"] = "Sensitivity Ranking"
data["slides.8.highlights.0.content"] = "ASP, grape procurement cost and volume are the top three EBIT drivers."
data["slides.8.highlights.1.title"] = "Three Scenarios"
data["slides.8.highlights.1.content"] = "Conservative, base and expansion scenarios each have different strategic focus and cash flow."
data["slides.8.highlights.2.title"] = "Risk Hedging"
data["slides.8.highlights.2.content"] = "Insurance, FX and interest rate management protect the downside."
data["slides.9.title"] = "Chapter 5"
data["slides.9.subtitle"] = "Returns"
data["slides.10.title"] = "Chapter 5: Quality Investment and ROI Thresholds"
data["slides.10.highlights.0.title"] = "Project Comparison"
data["slides.10.highlights.0.content"] = "Quality upgrade, hospitality experience and sustainability retrofit compared for CapEx and returns."
data["slides.10.highlights.1.title"] = "ROI Dashboard"
data["slides.10.highlights.1.content"] = "Interactive dashboard shows IRR, NPV and intangible indicators."
data["slides.10.highlights.2.title"] = "Threshold Design"
data["slides.10.highlights.2.content"] = "IRR ≥15%, payback <6 years, with post-investment review."
data["slides.11.title"] = "Course Summary"
data["slides.12.title"] = "Post-Course Quiz"

f.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
print("Done. Updated 36 short text keys.")
