/**
 * Phase 2: Translate all Chinese text inside SVG files to English
 * Strategy: exact string replacement of Chinese text nodes
 */
const fs = require('fs');
const path = require('path');

// Map of Chinese text → English translation
// Key: exact text between > and < in SVG
const TRANSLATIONS = {
  // ── L2-1: Médoc AOC Hierarchy ──────────────────────────────────────────────
  'Médoc AOC 產區層級架構': 'Médoc AOC Classification Hierarchy',
  '最廣泛的波爾多通用產區 · 約 57,000 公頃 · 全區皆可使用': 'Broadest Bordeaux appellation · ~57,000 ha · applicable region-wide',
  '半島區域產區 · 約 15,000 公頃 · 更嚴格的品種與產量規範': 'Peninsula-level AOC · ~15,000 ha · stricter variety & yield rules',
  'Médoc AOC（北部）　　Haut-Médoc AOC（南部精華）': 'Médoc AOC (North)　　Haut-Médoc AOC (Southern Core)',
  '六大村莊級 AOC（Village Appellations）': 'Six Village AOCs (Village Appellations)',
  '最嚴格的產量規範 · 僅允許特定品種 · 約 6,000 公頃': 'Strictest yield controls · specific varieties only · ~6,000 ha',
  '1855 列級酒莊': '1855 Classified Growths',
  'Grands Crus Classés · 61 座': 'Grands Crus Classés · 61 Châteaux',
  '品質規範嚴格 ▲': 'Quality Rules Stricter ▲',
  '產區面積擴大 ▼': 'Appellation Area Expands ▼',
  '* 層級越高，AOC 規範越嚴格，但核准使用的地理範圍越小 · 品質標竿也越精確': '* Higher tiers = stricter AOC rules but smaller permitted areas · more precise quality benchmarks',

  // ── L2-1: 1855 Classification Overview ────────────────────────────────────
  '1855 列級酒莊分級制度': '1855 Classified Growths System',
  '1er Grand Cru Classé　　第一級列級酒莊': '1er Grand Cru Classé　　First Growth',
  'Château Margaux（Margaux）　Château Mouton Rothschild（Pauillac, 1973升一）　Château Haut-Brion（Pessac）': 'Château Margaux (Margaux)　Château Mouton Rothschild (Pauillac, elevated 1973)　Château Haut-Brion (Pessac)',
  '座': 'châteaux',
  '2ème Grand Cru Classé　　第二級列級酒莊': '2ème Grand Cru Classé　　Second Growth',
  '3ème Grand Cru Classé　　第三級列級酒莊': '3ème Grand Cru Classé　　Third Growth',
  '4ème Grand Cru Classé　　第四級列級酒莊': '4ème Grand Cru Classé　　Fourth Growth',
  '5ème Grand Cru Classé　　第五級列級酒莊': '5ème Grand Cru Classé　　Fifth Growth',
  '創立年份': 'Founded',
  '涵蓋產區': 'Appellations',
  '總莊數': 'Total',
  '61 座': '61 Châteaux',
  '唯一升級': 'Only Promotion',
  '* 分級基準為市場售價與歷史聲譽，1855年至今幾乎未變動，是全球最穩定的葡萄酒分級制度': '* Ranked by market price & historical reputation; virtually unchanged since 1855 — the world\'s most stable wine classification',

  // ── L2-1: Croupe Cross-Section ────────────────────────────────────────────
  'Médoc 砂礫丘（Croupe）剖面圖': 'Médoc Croupe (Gravel Ridge) Cross-Section',
  'Croupe Graveleuse Cross-Section · 排水 · 蓄熱 · 根系深扎': 'Croupe Graveleuse Cross-Section · Drainage · Heat Retention · Deep Rooting',
  '太陽': 'Sun',
  '熱輻射吸收': 'Heat Absorption',
  '砂礫丘（Croupe）　略高於周邊平原，自然排水極佳': 'Croupe (Gravel Ridge)　Slightly elevated above surroundings, excellent natural drainage',
  '表土層': 'Topsoil',
  '0 – 30 cm　細砂・少量黏土・透氣良好': '0–30 cm　Fine sand · small clay fraction · well-aerated',
  '🪨 砂礫層（核心）': '🪨 Gravel Layer (Core)',
  '30 – 150 cm　石英砂礫・鵝卵石・排水迅速・白天蓄熱夜間放熱': '30–150 cm　Quartz gravel · pebbles · fast drainage · absorbs heat by day, radiates at night',
  'Gunz砂礫（第四紀冰河期沖積）·  貧瘠環境迫使根系深扎': 'Günz gravel (Quaternary glacial alluvium) · poor soils force deep root penetration',
  '熱反射效應 → 加速 Cabernet Sauvignon 成熟': 'Heat-reflection effect → accelerates Cabernet Sauvignon ripening',
  '底土層': 'Subsoil',
  '150 – 300 cm　鐵質黏土・石灰岩基底・濕潤時可蓄水，乾旱時緩慢供水': '150–300 cm　Iron-rich clay · limestone base · retains water when wet, releases slowly in drought',
  '基岩層（石灰岩）': 'Bedrock (Limestone)',
  '礦物質來源 · 給予葡萄酒礦物感與複雜度': 'Mineral source · imparts minerality and complexity to the wine',
  '葡萄藤': 'Grapevine',
  '根系深扎': 'Deep Rooting',
  '至 3–4 公尺': 'Down to 3–4 m',
  '夜間': 'Night',
  '放熱': 'Heat Release',
  '降雨': 'Rainfall',
  '迅速': 'Rapid',
  '排出': 'Drainage',
  '* 砂礫丘（Croupe）的排水與蓄熱功能，是 Médoc 頂級葡萄酒誕生的核心條件': '* The Croupe\'s drainage and heat-retention properties are the essential conditions for producing top Médoc wines',
  '越靠近 Gironde 河且砂礫越深厚的 Croupe，釀出的酒款結構越雄偉、陳年潛力越強': 'Croupes closer to the Gironde and with deeper gravel produce wines of greater structure and ageing potential',

  // ── L2-2: Margaux Elegant Style ───────────────────────────────────────────
  'Margaux　優雅女王的風格密碼': 'Margaux　The Style Code of the Elegant Queen',
  'The "Feminine" Village of Médoc · 細砂礫 · 花香 · 絲滑單寧': 'The "Feminine" Village of Médoc · Fine Gravel · Floral Aromas · Silky Tannins',
  '🌹 風格特徵': '🌹 Style Profile',
  '香氣輪廓': 'Aroma Profile',
  '🌹 玫瑰 · 紫羅蘭 · 牡丹（花香）': '🌹 Rose · Violet · Peony (Floral)',
  '🍓 草莓 · 覆盆子 · 紅醋栗（紅果）': '🍓 Strawberry · Raspberry · Red Currant (Red Fruits)',
  '✏️ 鉛筆芯 · 雪松 · 香根草（成熟）': '✏️ Pencil Shavings · Cedar · Vetiver (Aged)',
  '🌿 薄荷 · 微草本氣息（清新）': '🌿 Mint · Subtle Herbaceous Note (Freshness)',
  '口感結構': 'Palate Structure',
  '• 單寧最細滑柔和（Médoc 中最優雅）': '• Finest, most silky tannins (most elegant in Médoc)',
  '• 中等酒體 · 清新酸度 · 長而絲滑的尾韻': '• Medium body · fresh acidity · long, silky finish',
  '• 年輕時即有魅力，陳年後更加複雜精妙': '• Charming when young, gains complexity with age',
  '土壤基礎': 'Soil Foundation',
  '細砂礫為主（Margaux 最細緻，排水極佳）': 'Predominantly fine gravel (finest in Médoc, excellent drainage)',
  '砂礫深度適中 · 優雅而非雄壯的風格基礎': 'Moderate gravel depth · foundation for elegance rather than power',
  '🏰 代表酒莊': '🏰 Key Châteaux',
  'Château Margaux　一級莊': 'Château Margaux　First Growth',
  '唯一 Margaux 村的一級莊 · 三個世紀的歷史': 'The only First Growth in Margaux village · three centuries of history',
  'Cab. Sauv. 75% · Merlot 20% · 陳年潛力 30–50 年': 'Cab. Sauv. 75% · Merlot 20% · Ageing potential 30–50 years',
  '均價 ~€600–1,500 · 副牌 Pavillon Rouge ~€80': 'Average price ~€600–1,500 · Second wine Pavillon Rouge ~€80',
  '二級莊（5 座）': 'Second Growths (5 châteaux)',
  '三級莊中的明星': 'Star of the Third Growths',
  'Château Palmer（常被評為二級水準）': 'Château Palmer (often rated at Second Growth level)',
  'Palmer 混釀 Cab. 50% / Merlot 40%，風格特別豐腴': 'Palmer blend: Cab. 50% / Merlot 40%, notably rich style',
  'Margaux AOC 產區基本資訊': 'Margaux AOC Basic Facts',
  '面積：1,455 公頃 · 列級酒莊：21 座': 'Area: 1,455 ha · Classified châteaux: 21',
  '主要品種：Cab. Sauv. 55–75% 為主': 'Dominant variety: Cab. Sauv. 55–75%',
  'Margaux 與其他三大名村最大的不同': 'What sets Margaux apart from the other three villages',
  '細砂礫 · 最優雅': 'Fine gravel · Most elegant',
  '花香·絲滑單寧': 'Floral · Silky tannins',
  '深厚砂礫 · 最強勁': 'Deep gravel · Most powerful',
  '黑果·鉛筆芯': 'Black fruit · Pencil shavings',
  '砂礫黏土均衡': 'Gravel-clay balance',
  '最平衡·均一': 'Most balanced · consistent',
  '黏土含量最高': 'Highest clay content',
  '最濃郁·單寧強': 'Most concentrated · firm tannins',
  '* 「Margaux」被稱為「波爾多的女王」，以細砂礫賦予的優雅花香與絲滑口感聞名於世': '* "Margaux" is known as the "Queen of Bordeaux", celebrated for the elegant floral aromas and silky texture imparted by its fine gravel soils',
  '五個公社（Margaux・Soussans・Cantenac・Labarde・Arsac）共同構成 Margaux AOC': 'Five communes (Margaux · Soussans · Cantenac · Labarde · Arsac) form the Margaux AOC',

  // ── L2-3: Three First Growths ──────────────────────────────────────────────
  'Pauillac 三大一級莊　風格特徵比較': 'Pauillac\'s Three First Growths　Style Comparison',
  '力量與永恆': 'Power & Eternity',
  'Pauillac 南部 · 黏土砂礫混合': 'Southern Pauillac · Clay-gravel mix',
  '🪨 風土特色': '🪨 Terroir',
  '砂礫層略含黏土 → 更強大的': 'Gravel with slight clay → greater',
  '結構與礦物深度': 'structure and mineral depth',
  '🍷 風格關鍵詞': '🍷 Style Keywords',
  '• 最強勁的單寧結構': '• Most powerful tannic structure',
  '• 深沈礦物感 · 黑色水果': '• Deep minerality · black fruits',
  '• 雪松 · 石墨 · 菸草盒': '• Cedar · graphite · cigar box',
  '• 完美封藏的年輕酒液': '• Tightly coiled when young',
  '⏳ 陳年潛力': '⏳ Ageing Potential',
  '頂級年份可陳年': 'Top vintages can age',
  '40 – 60 年以上': '40–60+ years',
  '🍇 品種比例': '🍇 Variety Breakdown',
  '💰 典型酒款均價': '💰 Typical Price Range',
  '~ €300 – 600 / 瓶': '~ €300–600 / bottle',
  'Le Fort de Latour（副牌）€50–80': 'Le Fort de Latour (2nd wine) €50–80',
  '優雅與精緻': 'Elegance & Refinement',
  'Pauillac 北部 · 細緻砂礫土壤': 'Northern Pauillac · fine gravel soils',
  '細砂礫 · 細膩質地 → 最精緻': 'Fine gravel · delicate texture → most refined',
  '的風格輪廓與香氣複雜度': 'style profile and aromatic complexity',
  '• 最優雅·絲滑質地': '• Most elegant · silky texture',
  '• 紅色果實·玫瑰花瓣': '• Red fruits · rose petals',
  '• 鉛筆芯·雪松·香料': '• Pencil shavings · cedar · spice',
  '• 細緻單寧·悠長尾韻': '• Fine tannins · lingering finish',
  '30 – 50 年以上': '30–50+ years',
  '~ €500 – 1,500 / 瓶': '~ €500–1,500 / bottle',
  'Carruades de Lafite（副牌）€80–120': 'Carruades de Lafite (2nd wine) €80–120',
  '華麗與藝術': 'Opulence & Art',
  'Pauillac 中部 · 深厚石英砂礫': 'Central Pauillac · deep quartz gravel',
  '砂礫最深厚 · 石英含量最高': 'Deepest gravel · highest quartz content',
  '→ 最飽滿濃郁的結構': '→ most full-bodied, concentrated structure',
  '• 最華麗飽滿的風格': '• Most opulent, full-bodied style',
  '• 黑醋栗·藍莓·可可': '• Blackcurrant · blueberry · cocoa',
  '• 烤橡木·香草·咖啡': '• Toasted oak · vanilla · coffee',
  '• 年份有獨特藝術標籤': '• Each vintage features a unique artist label',
  '25 – 45 年以上': '25–45+ years',
  '~ €300 – 800 / 瓶': '~ €300–800 / bottle',
  'Le Petit Mouton（副牌）€60–100': 'Le Petit Mouton (2nd wine) €60–100',
  '* 三大一級莊均位於 Pauillac 且主要以 Cabernet Sauvignon 為基底，但因地塊細微差異而形塑出截然不同的風格個性': '* All three First Growths are in Pauillac and Cabernet Sauvignon-dominant, yet subtle terroir differences create distinctly contrasting styles',
  'Mouton 於 1973 年由拿破崙三世曾孫 Baron Philippe 爭取下由二級升為一級莊（唯一一次升級案例）': 'Mouton was elevated from Second to First Growth in 1973 by Baron Philippe de Rothschild — the only reclassification in history',

  // ── L2-4: Saint-Julien Balanced Style ────────────────────────────────────
  'Saint-Julien　均衡典範': 'Saint-Julien　The Balanced Benchmark',
  'Médoc 的「均衡典範」· 砂礫與黏土完美配比 · 穩定高品質': 'Médoc\'s "Balanced Benchmark" · perfect gravel-clay ratio · consistently high quality',
  '⚖️ 為何稱「均衡典範」？': '⚖️ Why the "Balanced Benchmark"?',
  '砂礫 45%': 'Gravel 45%',
  '黏土 30%': 'Clay 30%',
  '完美平衡': 'Perfect Balance',
  '🍷 風格特徵': '🍷 Style Profile',
  '香氣': 'Aromas',
  '黑醋栗 · 黑莓 · 紫羅蘭': 'Blackcurrant · Blackberry · Violet',
  '雪松 · 香料 · 煙燻': 'Cedar · Spice · Smoke',
  '口感': 'Palate',
  '中至飽滿酒體 · 成熟圓潤單寧': 'Medium-to-full body · ripe, rounded tannins',
  '完美酸度 · 悠長尾韻': 'Perfect acidity · long finish',
  '陳年': 'Ageing',
  '頂級莊 15–30 年 · 普遍比 Pauillac': 'Classified estates 15–30 years · generally more approachable than Pauillac',
  '更早開放，比 Margaux 更耐久': 'earlier; more durable than Margaux',
  '🏰 主要列級酒莊': '🏰 Key Classified Estates',
  'Château Léoville Las Cases　二級': 'Château Léoville Las Cases　Second Growth',
  '被譽為「最偉大的二級莊」· 接近一級水準': 'Hailed as "the greatest Second Growth" · near First Growth quality',
  'Château Léoville Barton　二級': 'Château Léoville Barton　Second Growth',
  '家族自釀 · CP 值最高的名莊之一': 'Estate-bottled · one of the best value classified estates',
  'Château Ducru-Beaucaillou　二級': 'Château Ducru-Beaucaillou　Second Growth',
  '優雅而精緻 · 砂礫最深厚': 'Elegant and refined · deepest gravel in the commune',
  '另有：Gruaud Larose · Talbot（四級）': 'Also: Gruaud Larose · Talbot (Fourth Growth)',
  'Beychevelle · Branaire-Ducru（四級）': 'Beychevelle · Branaire-Ducru (Fourth Growth)',
  'Saint-Julien AOC 產區基本資訊': 'Saint-Julien AOC Facts',
  '面積': 'Area',
  '910 公頃': '910 ha',
  '列級莊': 'Classified Estates',
  '11 座（全部二~四級）': '11 (all Second to Fourth Growths)',
  '特點': 'Characteristic',
  '無一級莊，但品質最穩定均一': 'No First Growth, yet most consistently high quality overall',
  '均衡指標': 'Balance Index',
  '* Saint-Julien 雖無一級莊，卻擁有六座二級莊，整體品質均一度是 Médoc 四大名村中最高的': '* Despite having no First Growth, Saint-Julien holds six Second Growths; its overall quality consistency is the highest among Médoc\'s four main villages',
  '夾在 Pauillac（力量）與 Margaux（優雅）之間，Saint-Julien 完美融合了兩者的優點': 'Situated between Pauillac (power) and Margaux (elegance), Saint-Julien perfectly blends the strengths of both',

  // ── L2-5: Saint-Estèphe Clay Terroir ──────────────────────────────────────
  'Saint-Estèphe　北方堡壘的力量': 'Saint-Estèphe　Power of the Northern Fortress',
  'Médoc 最北、黏土最多 · 骨架最強 · 最需耐心等待': 'Northernmost Médoc · highest clay content · strongest structure · demands patience',
  '🪨 土壤特性': '🪨 Soil Character',
  'Médoc 中黏土比例最高': 'Highest clay proportion in Médoc',
  '土壤成分比較（相對含量）': 'Soil Composition Comparison (relative)',
  '黏土': 'Clay',
  '礫石': 'Gravel',
  'Pauillac（比較）': 'Pauillac (for comparison)',
  '黏土的作用': 'Role of Clay',
  '✓ 保水性強 → 乾旱年份穩定供水': '✓ Strong water retention → stable supply in drought years',
  '✓ 較低溫度 → 延緩成熟 → 更高酸度': '✓ Cooler temperatures → delayed ripening → higher acidity',
  '✓ 礦物質豐富 → 賦予深度礦物感': '✓ Mineral-rich → imparts deep mineral character',
  '⚠ 排水較差 → 雨季需注意淹水風險': '⚠ Poorer drainage → waterlogging risk in wet seasons',
  '🍷 風格與酒莊': '🍷 Style & Key Estates',
  '風格關鍵詞': 'Style Keywords',
  '• 單寧最強硬、骨架雄偉': '• Firmest tannins, imposing structure',
  '• 黑色水果 · 礦物感 · 菸草': '• Black fruits · minerality · tobacco',
  '• 高酸度 · 豐厚酒體': '• High acidity · full body',
  '• 需至少 10–15 年才開始展現魅力': '• Needs at least 10–15 years to begin showing its best',
  '代表酒莊': 'Key Estates',
  'Cos d\'Estournel　二級莊': 'Cos d\'Estournel　Second Growth',
  '最著名的 Saint-Estèphe · 東方式建築 · 豐厚濃郁': 'Most celebrated in Saint-Estèphe · Oriental architecture · rich and concentrated',
  'Château Montrose　二級莊': 'Château Montrose　Second Growth',
  '最傳統的 St-Estèphe 風格 · 強勁耐陳 · 高單寧': 'Most traditional St-Estèphe style · powerful, age-worthy · firm tannins',
  'Calon-Ségur（三級）· Lafon-Rochet（四級）': 'Calon-Ségur (Third Growth) · Lafon-Rochet (Fourth Growth)',
  'Médoc 南北風格差異示意（由南到北）': 'Médoc North–South Style Gradient (south to north)',
  '← 南部': '← South',
  '北部 →': 'North →',
  '最優雅': 'Most Elegant',
  '細砂礫': 'Fine Gravel',
  '最均衡': 'Most Balanced',
  '砂礫均衡': 'Balanced Gravel-Clay',
  '最強勁': 'Most Powerful',
  '深礫石': 'Deep Gravel',
  '最雄厚': 'Most Robust',
  '黏土最多': 'Highest Clay',
  '* 從 Margaux（南）到 Saint-Estèphe（北），土壤中黏土比例逐漸增加，酒款風格由優雅轉為雄渾': '* From Margaux (south) to Saint-Estèphe (north), clay content gradually increases and wine style shifts from elegant to robust',

  // ── L2-6: Crasse de Fer Blue Clay ────────────────────────────────────────
  'Pomerol 藍黏土（Crasse de Fer）示意圖': 'Pomerol Blue Clay (Crasse de Fer) Diagram',
  'Crasse de Fer：含鐵質藍黏土 · Pétrus 奇蹟的根源': 'Crasse de Fer: Iron-rich Blue Clay · The Secret Behind Pétrus',
  '藍黏土（Crasse de Fer）': 'Blue Clay (Crasse de Fer)',
  '黏土層': 'Clay Layer',
  '砂質土壤': 'Sandy Soil',
  '礫石土壤': 'Gravel Soil',
  'Pétrus 位置': 'Pétrus Location',
  '其他頂級酒莊': 'Other Top Estates',
  'Pomerol 高原（Plateau）': 'Pomerol Plateau',
  '表土層（0–30 cm）': 'Topsoil (0–30 cm)',
  '混合砂質表土 · 有機質豐富': 'Mixed sandy topsoil · organically rich',
  '黏土層（30–80 cm）': 'Clay Layer (30–80 cm)',
  '保水性強 · 提供充分水分 · Merlot 的最愛': 'Strong water retention · ample moisture supply · Merlot\'s ideal medium',
  '🔵 Crasse de Fer 含鐵藍黏土層（80–150 cm）': '🔵 Crasse de Fer Iron-rich Blue Clay (80–150 cm)',
  '鐵質氫氧化物 · 給予黏土特有的藍灰色澤': 'Iron hydroxides · responsible for the distinctive blue-grey colour',
  '保水能力極佳 · 乾燥年份仍可穩定供水 · 賦予 Pétrus 天鵝絨質地的根源': 'Exceptional water retention · reliable supply even in dry years · the source of Pétrus\'s velvety texture',
  '鐵質礦物結節': 'Iron Mineral Nodules',
  '底土砂礫層（150–250 cm）': 'Subsoil Gravel (150–250 cm)',
  '砂礫基底 · 好年份礦物感來源 · 排水輔助': 'Gravel base · source of minerality in great vintages · drainage support',
  '基岩（石灰岩）250 cm+': 'Bedrock (Limestone) 250 cm+',
  '礦物質庫 · 長期供應微量元素': 'Mineral reservoir · long-term supply of trace elements',
  '根系穿越': 'Root Penetration',
  '藍黏土層': 'Blue Clay Layer',
  '🔵 為什麼 Crasse de Fer 造就了 Pétrus？': '🔵 Why Does Crasse de Fer Make Pétrus?',
  '這層含鐵藍黏土恰好分布在 Pétrus 正下方，完美保水 · 調節根系水分供應 · 產生天鵝絨般的 Merlot 質地': 'This iron-rich blue clay lies directly beneath Pétrus, perfectly retaining water · regulating root moisture supply · creating Merlot of velvet-like texture',

  // ── L2-7: Saint-Émilion Three Terroir Zones ──────────────────────────────
  'Saint-Émilion 三大風土區': 'Saint-Émilion\'s Three Terroir Zones',
  'Three Terroir Zones · 高地 · 坡地 · 平原': 'Three Terroir Zones · Plateau · Slopes · Plain',
  '① 高地（Plateau）': '① Plateau (Plateau)',
  '石灰岩高原 Plateau Calcaire': 'Limestone Plateau · Plateau Calcaire',
  '🪨 土壤': '🪨 Soil',
  '淺層石灰岩 · 黏土覆蓋': 'Shallow limestone · clay cover',
  '礦物質豐富 · 排水良好': 'Mineral-rich · well-drained',
  '🍷 典型風格': '🍷 Typical Style',
  '• 精緻·礦物感強': '• Refined · strong minerality',
  '• 優雅·香料·果乾': '• Elegant · spice · dried fruit',
  '• 陳年後發展複雜度': '• Develops complexity with age',
  '• 適合長期窖藏': '• Suited to long cellaring',
  '🏰 代表酒莊': '🏰 Key Estates',
  '🍇 品種：Cab. Franc 主導': '🍇 Varieties: Cab. Franc dominant',
  '② 坡地（Côtes）': '② Slopes (Côtes)',
  '黏土-石灰岩坡面 Côtes Argilo-Calcaires': 'Clay-Limestone Slopes · Côtes Argilo-Calcaires',
  '黏土與石灰岩混合': 'Clay and limestone mixed',
  '自然坡度輔助排水': 'Natural slope aids drainage',
  '• 飽滿豐厚 · 果味濃郁': '• Full-bodied · richly fruited',
  '• 黑色水果 · 甘草 · 香料': '• Black fruits · liquorice · spice',
  '• 單寧成熟 · 口感圓潤': '• Ripe tannins · rounded palate',
  '• 均衡而多層次': '• Balanced and multi-layered',
  '🍇 品種：Merlot + Cab. Franc': '🍇 Varieties: Merlot + Cab. Franc',
  '③ 平原（Plaine）': '③ Plain (Plaine)',
  '砂礫平原 Plaine Sablonneuse-Graveleuse': 'Sandy-Gravel Plain · Plaine Sablonneuse-Graveleuse',
  '平坦地形 · 自然排水依賴土壤': 'Flat terrain · drainage depends on soil',
  '砂土與礫石 · 較貧瘠': 'Sand and gravel · relatively poor',
  '排水良好 · 保水性較低': 'Good drainage · lower water retention',
  '• 果味直接 · 清新易飲': '• Direct fruit · fresh and approachable',
  '• 紅色果實 · 花香': '• Red fruits · floral notes',
  '• 單寧較柔和': '• Softer tannins',
  '• 適合早期飲用': '• Best enjoyed young',
  'La Conseillante 附近': 'Near La Conseillante',
  'Saint-Émilion AOC 通用級': 'Saint-Émilion AOC (generic)',
  '各品質層級的 Grand Cru': 'Grand Cru across quality tiers',
  '🍇 品種：Merlot 主導': '🍇 Varieties: Merlot dominant',
  'Saint-Émilion 動態分級制度（每 10 年重新評審）': 'Saint-Émilion Dynamic Classification (revised every 10 years)',
  'A 級': 'Tier A',
  'Classés A（2 座）': 'Classés A (2 châteaux)',
  'B 級': 'Tier B',
  'Classés B（約 11–13 座）': 'Classés B (~11–13 châteaux)',
  '列級莊': 'Classified Growths',
  '（約 64–82 座）': '(~64–82 châteaux)',
  '通用': 'Generic',
  '* Château Ausone（高地）與 Château Cheval Blanc（坡地）為僅有的兩座 A 級莊，代表兩種截然不同的風土': '* Château Ausone (Plateau) and Château Cheval Blanc (Slopes) are the only two Tier A estates, representing two entirely different terroir types',
  'Saint-Émilion 分級每 10 年重新評審 · 是波爾多唯一的動態分級制度': 'Saint-Émilion\'s classification is revised every 10 years — the only dynamic classification in Bordeaux',

  // ── L2-8: Satellite Appellations ─────────────────────────────────────────
  'Médoc 衛星產區概覽': 'Médoc Satellite Appellations Overview',
  'Satellite Appellations of Médoc · 七個 AOC · 高 CP 值的隱藏寶庫': 'Satellite Appellations of Médoc · Seven AOCs · Hidden Value Gems',
  '🗺️ 位置': '🗺️ Location',
  'Haut-Médoc 中部內陸': 'Inland, central Haut-Médoc',
  '🍷 特色': '🍷 Character',
  '柔和易飲 · 礫石黏土': 'Soft and approachable · gravel-clay soils',
  '代表：Chasse-Spleen': 'Key estate: Chasse-Spleen',
  'Médoc 海拔最高區域': 'Highest elevation zone in Médoc',
  '石灰岩 · 清爽酸度': 'Limestone · crisp acidity',
  '代表：Clarke · Fourcas': 'Key estates: Clarke · Fourcas',
  '四大名村之外的精華區': 'Premium zone outside the four main villages',
  '包含 Château La Lagune': 'Includes Château La Lagune',
  '及 Château Cantemerle': 'and Château Cantemerle',
  '🗺️ 鄰接 Pomerol 北部': '🗺️ Adjacent to northern Pomerol',
  'Merlot 主導': 'Merlot dominant',
  '豐滿柔順 · 早熟': 'Plush and supple · early maturing',
  'Néac 同屬此 AOC': 'Néac is also within this AOC',
  '💰 €15–35 / 瓶': '💰 €15–35 / bottle',
  '🗺️ Libourne 西北': '🗺️ Northwest of Libourne',
  '石灰岩高台': 'Limestone terrace',
  '結構感強 · Cab. Franc 特色': 'Strong structure · Cab. Franc character',
  '被視為「性價比右岸」': 'Regarded as the "value Right Bank"',
  '💰 €12–40 / 瓶': '💰 €12–40 / bottle',
  '🗺️ Gironde 右岸北部': '🗺️ Northern Right Bank of the Gironde',
  '石灰岩黏土': 'Limestone clay',
  '清新果味 · 均衡易飲': 'Fresh fruit · balanced and easy-drinking',
  '近年品質迅速提升': 'Quality improving rapidly in recent years',
  '💰 €10–25 / 瓶': '💰 €10–25 / bottle',
  '🗺️ Gironde 右岸': '🗺️ Right Bank of the Gironde',
  '石灰岩黏土礫石': 'Limestone, clay and gravel',
  '可與 Saint-Émilion 比肩': 'Can rival Saint-Émilion in quality',
  '💰 €10–30 / 瓶': '💰 €10–30 / bottle',
  '衛星產區的價值定位': 'Value Proposition of Satellite Appellations',
  '品質': 'Quality',
  '七成名莊水準': '~70% of classified estate quality',
  '價格': 'Price',
  '三到四成名莊價格': '30–40% of classified estate prices',
  'CP 值': 'Value',
  '極高 ★★★★☆': 'Exceptional ★★★★☆',
  '→ 衛星產區是「預算有限愛酒人」的最佳入口，以親民價格體驗波爾多正統風土': '→ Satellite appellations are the ideal entry point for budget-conscious wine lovers, offering authentic Bordeaux terroir at accessible prices',
  '* 部分衛星產區（如 Fronsac、Côtes de Bourg）的頂級酒莊品質已達中等名莊水準，卻只需三分之一的價格': '* Some satellite estates (e.g. Fronsac, Côtes de Bourg) match mid-tier classified growth quality at one-third the price',

  // ── L2-9: Four Villages Radar Chart ──────────────────────────────────────
  'Médoc 四大名村風格對比': 'Médoc Four Villages Style Comparison',
  'Margaux · Pauillac · Saint-Julien · Saint-Estèphe　五維風格雷達圖': 'Margaux · Pauillac · Saint-Julien · Saint-Estèphe　Five-Axis Style Radar',
  '單寧強度': 'Tannin Intensity',
  '飽滿度': 'Body',
  '礦物感': 'Minerality',
  '優雅度': 'Elegance',
  '陳年潛力': 'Ageing Potential',
  '王者・強勁・陳年': 'King · Powerful · Age-worthy',
  '單寧95 飽滿90 陳年95': 'Tannin 95 · Body 90 · Ageing 95',
  '濃郁・堅實・力量': 'Concentrated · Firm · Powerful',
  '單寧90 飽滿85 陳年88': 'Tannin 90 · Body 85 · Ageing 88',
  '均衡・優雅・精緻': 'Balanced · Elegant · Refined',
  '單寧78 飽滿82 優雅85': 'Tannin 78 · Body 82 · Elegance 85',
  '優雅・細膩・花香': 'Elegant · Delicate · Floral',
  '單寧68 優雅98 礦物75': 'Tannin 68 · Elegance 98 · Minerality 75',
  '* 數值為風格相對指標，非絕對評分 · 各軸滿分 100': '* Values are relative style indicators, not absolute scores · max 100 per axis',

  // ── L3-1: Climate Change ──────────────────────────────────────────────────
  '氣候變遷對波爾多的影響': 'Impact of Climate Change on Bordeaux',
  'Climate Change Impact · 1960s–2020s 六十年的轉變': 'Climate Change Impact · 1960s–2020s Sixty Years of Change',
  '🌡️ 波爾多年均溫上升趨勢': '🌡️ Bordeaux Annual Temperature Rise Trend',
  '（較1961–1990基準期的偏差 °C）': '(Deviation from 1961–1990 baseline, °C)',
  '2003年': '2003',
  '極端熱浪': 'Extreme Heatwave',
  '📅 採收日期提前趨勢': '📅 Earlier Harvest Date Trend',
  '（Cabernet Sauvignon 採收起始日）': '(Cabernet Sauvignon harvest start date)',
  '↑ 60年間採收提前約 2–3 週': '↑ Harvest moved ~2–3 weeks earlier over 60 years',
  '🥵 挑戰': '🥵 Challenges',
  '酒精度過高（&gt;14.5%）': 'Excessive alcohol (&gt;14.5%)',
  '酸度下降，結構感失衡': 'Declining acidity, structural imbalance',
  '葡萄成熟節奏改變': 'Altered ripening rhythm',
  '乾旱與霜凍風險共存': 'Coexisting drought and frost risks',
  '🌱 應對策略': '🌱 Adaptation Strategies',
  '晚摘 → 早摘，保留酸度': 'Later picking → earlier picking to preserve acidity',
  '種植海拔更高的地塊': 'Planting at higher elevations',
  '引進 Touriga / Nero 品種試驗': 'Trialling Touriga / Nero varieties',
  '灌溉技術（部分 AOC 已允許）': 'Irrigation technology (permitted in some AOCs)',
  '🌟 潛在機遇': '🌟 Potential Opportunities',
  '涼爽年份品質更穩定': 'Cooler vintages show greater consistency',
  'Saint-Estèphe 等北部受益': 'Northern areas like Saint-Estèphe benefit',
  'Merlot 品質提升機會': 'Opportunity for improved Merlot quality',
  '早採 Cab.F. 展現新風格': 'Early-picked Cab. Franc reveals new styles',
  '⚡ 關鍵轉折年份': '⚡ Key Turning-Point Vintages',
  '完美均衡': 'Perfect Balance',
  '近代最偉大年份之一': 'One of the greatest modern vintages',
  '涼爽困難年': 'Cool, Difficult Year',
  '右岸表現明顯優於左岸': 'Right Bank clearly outperformed Left Bank',
  '熱而豐盛': 'Hot and Abundant',
  '左岸首選，結構宏大': 'Left Bank preferred, grand structure',
  '世紀年份': 'Vintage of the Century',
  '左右岸均衡，傳奇年份': 'Both banks excellent, legendary vintage',
  '高溫乾旱': 'Hot and Dry',
  '早採策略成功，明亮果味': 'Early-harvest strategy succeeded, bright fruit',
  '涼爽偉大年': 'Cool and Great',
  '優雅酸度，近年最佳之一': 'Elegant acidity, one of the best recent vintages',
  '* 數據基於波爾多氣象站長期觀測及頂級酒莊採收記錄整理 · 具體數值依產區略有差異': '* Data based on long-term Bordeaux meteorological observations and top château harvest records · specific figures vary by appellation',

  // ── L3-10: Food & Wine Pairing ────────────────────────────────────────────
  '波爾多葡萄酒餐酒搭配指南': 'Bordeaux Wine & Food Pairing Guide',
  'Food &amp; Wine Pairing · 讓每一口食物都為葡萄酒加分': 'Food &amp; Wine Pairing · Every bite should enhance the wine',
  '🏛️ 左岸紅酒': '🏛️ Left Bank Red',
  'Cab.S. 主導 · 強勁結構': 'Cab. Sauv.-dominant · powerful structure',
  '🥩 最佳肉類搭配': '🥩 Best Meat Pairings',
  '• 肋眼牛排 / 烤牛腰脊': '• Rib-eye steak / roast sirloin',
  '• 香草烤羊排（經典）': '• Herb-roasted rack of lamb (classic)',
  '• 鹿肉 / 野豬等野味': '• Venison / wild boar and other game',
  '• 紅酒燉牛肉（鏡面搭配）': '• Beef braised in red wine (mirror pairing)',
  '🧀 乳酪搭配': '🧀 Cheese Pairings',
  '陳年 Comté / Cheddar': 'Aged Comté / Cheddar',
  '❌ 避免搭配': '❌ Avoid Pairing With',
  '• 生魚片 / 海鮮': '• Raw fish / seafood',
  '• 甜點（單寧加澀）': '• Desserts (tannins turn bitter)',
  '• 辛辣料理（放大苦感）': '• Spicy dishes (amplifies bitterness)',
  '🌱 右岸紅酒': '🌱 Right Bank Red',
  'Merlot 主導 · 柔順圓潤': 'Merlot-dominant · soft and rounded',
  '• 烤鴨胸 / 油封鴨': '• Roast duck breast / duck confit',
  '• 煎小牛肉 / 豬里脊': '• Sautéed veal / pork tenderloin',
  '• 牛肉漢堡 / 肉丸': '• Beef burger / meatballs',
  '• 蘑菇燉雞腿（親和力高）': '• Mushroom-braised chicken thighs (highly versatile)',
  '🍄 蔬食搭配': '🍄 Vegetarian Pairings',
  '松露 / 牛肝菌燉飯': 'Truffle / porcini risotto',
  '烤根莖類蔬菜': 'Roasted root vegetables',
  '🌏 亞洲料理': '🌏 Asian Cuisine',
  '• 北京烤鴨（出色搭配）': '• Peking duck (outstanding pairing)',
  '• 紅燒肉 / 東坡肉': '• Red-braised pork belly',
  '• 日式壽喜燒': '• Japanese sukiyaki',
  '🍾 白酒 &amp; 甜酒': '🍾 White Wine &amp; Sweet Wine',
  '🐟 白酒 (Sauvignon Blanc)': '🐟 White Wine (Sauvignon Blanc)',
  '• 生蠔 / 海鮮塔': '• Oysters / seafood tower',
  '• 清蒸海鱸 / 鱈魚': '• Steamed sea bass / cod',
  '• 山羊乳酪沙拉': '• Goat\'s cheese salad',
  '• 白蘆筍 / 野菜前菜': '• White asparagus / wild greens starter',
  '🍯 Sauternes 貴腐甜酒': '🍯 Sauternes Noble Rot Sweet Wine',
  '• 鵝肝醬（天作之合！）': '• Foie gras (a match made in heaven!)',
  '• 藍紋乳酪（Roquefort）': '• Blue cheese (Roquefort)',
  '• 法式焦糖布蕾': '• French crème brûlée',
  '• 椰子蛋糕 / 杏桃塔': '• Coconut cake / apricot tart',
  '💡 特殊搭配法': '💡 Special Pairing Trick',
  '甜配鹹：甜酒 + 鵝肝 = 傳奇': 'Sweet with savoury: sweet wine + foie gras = legendary',
  '🎯 四大餐酒搭配原則': '🎯 Four Core Pairing Principles',
  '⚖️ 重量配重量': '⚖️ Match Weight with Weight',
  '濃郁紅酒配厚重肉食': 'Full-bodied red with hearty meat',
  '清爽白酒配輕盈海鮮': 'Crisp white with delicate seafood',
  '避免輕重失衡': 'Avoid mismatching weight',
  '🔴 單寧 × 蛋白質': '🔴 Tannin × Protein',
  '肉類蛋白質中和單寧': 'Meat protein softens tannins',
  '使口感更柔順': 'Creates a smoother mouthfeel',
  '牛排 + 左岸红酒 = 完美': 'Steak + Left Bank red = perfect',
  '🌿 酸度 × 油脂': '🌿 Acidity × Fat',
  '高酸葡萄酒切割油脂': 'High-acid wine cuts through fat',
  '清新感增添食慾': 'Freshness enhances appetite',
  'Sauv. Blanc + 魚排 = 清爽': 'Sauv. Blanc + fish fillet = refreshing',
  '🍯 甜酒配對等甜': '🍯 Match Sweet with Sweet',
  '甜酒需配同等甜度食物': 'Sweet wine needs equally sweet food',
  '否則甜酒顯苦澀': 'Otherwise the wine tastes bitter',
  '例外：甜酒 + 鹹食 = 驚喜': 'Exception: sweet wine + salty food = surprise',
  '🌏 亞洲料理配波爾多的特別建議': '🌏 Special Advice: Bordeaux with Asian Cuisine',
  '廣東料理': 'Cantonese Cuisine',
  '清蒸魚 → 白酒': 'Steamed fish → white wine',
  '燒鵝 → 右岸紅': 'Roast goose → Right Bank red',
  '叉燒 → 右岸紅': 'Char siu BBQ pork → Right Bank red',
  '日本料理': 'Japanese Cuisine',
  '壽喜燒 → 右岸紅': 'Sukiyaki → Right Bank red',
  '牛排鐵板 → 左岸紅': 'Teppanyaki steak → Left Bank red',
  '壽司 → 白酒': 'Sushi → white wine',
  '台灣料理': 'Taiwanese Cuisine',
  '三杯雞 → 右岸紅（注意辣）': 'Three-cup chicken → Right Bank red (note: spicy)',
  '蚵仔煎 → 偏甜白酒': 'Oyster omelette → off-dry white wine',
  '東坡肉 → 成熟右岸紅': 'Dongpo pork → mature Right Bank red',
  '⚠️ 挑戰配對': '⚠️ Challenging Pairings',
  '麻辣料理 → 果味豐富右岸': 'Sichuan spicy → fruit-forward Right Bank',
  '醋漬食物 → 避免左岸': 'Pickled / vinegar dishes → avoid Left Bank',
  '重鹽食物 → 選高酸度酒': 'Heavily salted food → choose high-acidity wine',
  '💡 記憶口訣：「重配重、輕配輕、酸切油、甜配甜、單寧愛蛋白質」': '💡 Mnemonic: "heavy with heavy, light with light, acid cuts fat, sweet with sweet, tannin loves protein"',

  // ── L3-11: History Timeline ───────────────────────────────────────────────
  '波爾多 2000 年葡萄酒發展史': '2,000 Years of Bordeaux Wine History',
  'Bordeaux Winemaking History · 橫跨六大時期的文化與貿易演進': 'Bordeaux Winemaking History · Six Eras of Culture and Trade',
  '🏛️ 羅馬與修道院時期': '🏛️ Roman & Monastic Period',
  '公元 1–11 世紀': 'AD 1st–11th Century',
  '• 羅馬人引入高盧品種 (Vitis biturica)': '• Romans introduced the Gallic variety (Vitis biturica)',
  '• 教會接管生產，確保彌撒用酒': '• Church took over production to ensure wine for Mass',
  '• 起初以清淡紅酒（Clairet）為主': '• Production initially focused on light red wine (Clairet)',
  '🇬🇧 英國統治黃金 300 年': '🇬🇧 Three Centuries of English Rule (Golden Era)',
  '1152–1453 年': '1152–1453',
  '• 埃莉諾公主聯姻亨利二世，開啟英國大門': '• Eleanor of Aquitaine\'s marriage to Henry II opened English markets',
  '• 減免關稅，英法貿易極度繁榮': '• Reduced tariffs fuelled booming Anglo-French trade',
  '• 奠定波爾多「出口導向」的商業基因': '• Established Bordeaux\'s export-oriented commercial identity',
  '🇳🇱 荷蘭治水與Médoc崛起': '🇳🇱 Dutch Drainage & Rise of Médoc',
  '17 世紀': '17th Century',
  '• 荷蘭工程師排乾 Médoc 沼澤濕地': '• Dutch engineers drained the Médoc marshlands',
  '• 引入二氧化硫（防腐）與橡木桶運輸': '• Introduced sulphur dioxide (preservation) and oak barrel transport',
  '• 從此波爾多以深色、能陳年的烈酒聞名': '• Bordeaux became renowned for dark, age-worthy wines',
  '🎖️ 1855 巴黎世博會分級': '🎖️ 1855 Paris Exposition Classification',
  '1855 年': '1855',
  '• 拿破崙三世下令，依據過往價格排名': '• Napoleon III ordered a ranking based on historical prices',
  '• 確認 61 家列級名莊 (Grand Cru Classé)': '• Confirmed 61 classified estates (Grand Cru Classé)',
  '• 確立現代波爾多奢侈品牌的最高標竿': '• Established the ultimate benchmark for modern Bordeaux luxury brands',
  '🐛 根瘤蚜蟲災與重建': '🐛 Phylloxera Disaster & Reconstruction',
  '19 世紀末 (約 1870-1900)': 'Late 19th Century (c. 1870–1900)',
  '• 蟲害摧毀全法葡萄園，釀酒業瀕臨滅絕': '• Blight destroyed vineyards across France, threatening the industry',
  '• 嫁接美國抗病砧木拯救了產業': '• Grafting onto American disease-resistant rootstocks saved the industry',
  '• 促成波爾多品種選擇的重新洗牌 (CS/Merlot)': '• Led to reshuffling of variety selection in Bordeaux (CS/Merlot)',
  '🔬 現代科學革命與全球化': '🔬 Modern Scientific Revolution & Globalisation',
  '20 世紀中葉迄今': 'Mid-20th Century to Present',
  '• Emile Peynaud 開創現代發酵科學': '• Emile Peynaud pioneered modern fermentation science',
  '• 溫控不鏽鋼槽、光學篩拔技術普及': '• Temperature-controlled stainless steel tanks and optical sorting became widespread',
  '• 中國市場崛起與全球資本投資': '• Rise of the Chinese market and global capital investment',
  '💡 「波爾多不是一天建成的，它是地理優越、商業敏銳與一千多年貿易歷史共同形塑的全球葡萄酒之都。」': '💡 "Bordeaux was not built in a day — it is shaped by geographic advantage, commercial acumen, and over a millennium of trade history, forming the world\'s wine capital."',

  // ── L3-12: Vintage Quality Chart ─────────────────────────────────────────
  '波爾多頂級年份品質概覽': 'Bordeaux Vintage Quality Overview',
  'Bordeaux Vintage Quality · 2000–2023 重要年份評分與特徵': 'Bordeaux Vintage Quality · 2000–2023 Key Vintages, Scores & Characteristics',
  '年份 →': 'Vintage →',
  '傳奇年份 (99分)': 'Legendary Vintage (99 pts)',
  '頂級年份 (95–98分)': 'Outstanding Vintage (95–98 pts)',
  '優秀年份 (90–94分)': 'Excellent Vintage (90–94 pts)',
  '一般年份 (&lt;90分)': 'Average Vintage (&lt;90 pts)',
  '📌 年份解讀要點': '📌 Key Vintage Insights',
  '左岸佳年': 'Best for Left Bank',
  '炎熱乾燥利於 Cab.S. 成熟：2000、2005、2009、2015、2016、2022': 'Hot, dry years favour Cab. Sauv. ripening: 2000, 2005, 2009, 2015, 2016, 2022',
  '右岸佳年': 'Best for Right Bank',
  '涼爽均衡利於 Merlot：2012（右岸優）、2010、2016、2023': 'Cool, balanced years favour Merlot: 2012 (Right Bank), 2010, 2016, 2023',

  // ── L3-2: Three Core Soils ────────────────────────────────────────────────
  '波爾多三大核心土壤科學與風土表達': 'Bordeaux\'s Three Core Soils: Science & Terroir Expression',
  '卡本內蘇維濃 (CS)': 'Cabernet Sauvignon (CS)',
  '深厚礫石層 (Gravel)': 'Deep Gravel Layer',
  '左岸 (梅多克 / 格拉夫)': 'Left Bank (Médoc / Graves)',
  '🌡️ 物理特性：排水極佳，白天吸熱夜間釋放': '🌡️ Physical: Excellent drainage, absorbs heat by day, releases at night',
  '🧬 根系表現：深深扎根尋找地下水': '🧬 Roots: Deep penetration in search of groundwater',
  '🍷 酒款風格：單寧強勁，結構宏大，適合陳年': '🍷 Wine Style: Powerful tannins, grand structure, age-worthy',
  '梅洛 (Merlot)': 'Merlot',
  '根系較淺，橫向發展': 'Shallower roots, lateral spread',
  '藍黏土 (Blue Clay)': 'Blue Clay',
  '右岸 (波美侯 核心)': 'Right Bank (Pomerol Core)',
  '💧 物理特性：保水力與冷卻力極強，富含鐵質': '💧 Physical: Exceptional water retention and cooling capacity, iron-rich',
  '🧬 根系表現：如海綿般儲水，旱季不缺水': '🧬 Roots: Sponge-like water storage, drought-resilient',
  '🍷 酒款風格：酒體豐滿柔順，質地絲滑如絨': '🍷 Wine Style: Full-bodied and supple, velvety texture',
  '卡本內弗朗 &amp; 梅洛': 'Cabernet Franc &amp; Merlot',
  '石灰岩台地 (Limestone)': 'Limestone Plateau',
  '右岸 (聖愛美倫 高地)': 'Right Bank (Saint-Émilion Plateau)',
  '🪨 物理特性：高鈣強鹼性，像天然毛細管調控水分': '🪨 Physical: High calcium, strongly alkaline, acts like a natural capillary for moisture',
  '🧬 根系表現：穿透岩縫尋找深層孔隙中的養分': '🧬 Roots: Penetrates fissures seeking nutrients in deep pores',
  '🍷 酒款風格：酸度明亮，香氣優雅，帶有礦石感': '🍷 Wine Style: Bright acidity, elegant aromatics, mineral finish',
  '沒有最好的土壤，只有最適合該品種的「風土協同效應」': 'There is no "best" soil — only the most synergistic terroir match for each variety',

  // ── L3-3: Extreme Vintages & Climate Risk ─────────────────────────────────
  '波爾多歷史極端年份與氣候風險': 'Bordeaux Extreme Vintages & Climate Risks Throughout History',
  'Extreme Vintages · 從歷史災難中學習，掌握應對氣候風險的策略': 'Extreme Vintages · Learning from Historical Disasters to Master Climate Risk Strategies',
  '❄️ 世紀大霜凍': '❄️ Frost of the Century',
  '摧毀大量老藤': 'Destroyed vast numbers of old vines',
  '逼迫波爾多重植與現代化': 'Forced Bordeaux to replant and modernise',
  '📉 春季晚霜': '📉 Late Spring Frost',
  '4月21日極寒': 'Extreme cold on 21 April',
  '產量大減，但倖存果實極佳': 'Yields decimated, but surviving fruit exceptional',
  '🔥 歷史性熱浪': '🔥 Historic Heatwave',
  '夏季高溫逾 40°C': 'Summer temperatures exceeding 40°C',
  '打破氣候觀念，葡萄烤焦': 'Shattered climate assumptions; grapes scorched',
  '🌧️ 降雨與灰黴病': '🌧️ Rainfall & Grey Rot',
  '近乎無夏的冷濕年': 'Nearly summerless cold, wet year',
  '最困難年份之一，考驗選果': 'One of the most challenging vintages; rigorous sorting essential',
  '⚔️ 氣候變遷考驗': '⚔️ Climate Change Test',
  '暖冬早萌芽 + 4月黑霜': 'Warm winter early budbreak + black frost in April',
  '產量大傷，啟用直升機防霜': 'Yields severely hit; helicopters deployed for frost protection',
  '🛡️ 現代波爾多的氣候風險應對與防禦策略': '🛡️ Modern Bordeaux Climate Risk Response & Defence Strategies',
  '💨 物理防禦裝備': '💨 Physical Defence Equipment',
  '防霜蠟燭 / 防風扇 / 直升機': 'Frost candles / wind machines / helicopters',
  '物理攪動空氣，防止冷空氣沉降': 'Physically agitate air to prevent cold air from settling',
  '🌱 農業技術調整': '🌱 Agronomic Adjustments',
  '延後修剪 / 葉幕管理': 'Delayed pruning / canopy management',
  '改變微氣候，保護葡萄與延遲發芽': 'Modifying the microclimate to protect grapes and delay budbreak',
  '💡 品種與科技投資': '💡 Variety Selection & Technology Investment',
  '試驗晚熟品種 / 光學選果': 'Trialling late-ripening varieties / optical sorting',
  '利用科技提升容錯率，對抗極端年份': 'Using technology to increase resilience against extreme vintages',
  '💡 「偉大的酒莊不是在完美年份展現水準，而是在極端年份展現生存與釀酒的智慧。」': '💡 "Great châteaux are defined not by what they achieve in perfect vintages, but by the wisdom and resilience they show in extreme ones."',

  // ── L3-4: Vineyard Cycle & Sustainability ────────────────────────────────
  '波爾多葡萄園管理與永續農業三大體系': 'Bordeaux Vineyard Management & Three Sustainability Systems',
  '全年': 'Annual',
  '週期': 'Cycle',
  '冬季 (Winter)': 'Winter',
  '剪枝 (Pruning)': 'Pruning',
  '決定來年產量結構': 'Determines next year\'s yield structure',
  '春季 (Spring)': 'Spring',
  '萌芽防霜凍': 'Budbreak & Frost Protection',
  '除芽與新梢管理': 'Bud removal & shoot management',
  '夏季 (Summer)': 'Summer',
  '摘葉通風 (Canopy)': 'Leaf removal & Canopy Management',
  '綠色採收控產': 'Green harvest (crop thinning)',
  '秋季 (Autumn)': 'Autumn',
  '監測完美成熟度': 'Monitoring for perfect ripeness',
  '採收時機與物流': 'Harvest timing & logistics',
  '波爾多三大永續農業哲學': 'Bordeaux\'s Three Sustainability Philosophies',
  'HVE (高環境價值)': 'HVE (High Environmental Value)',
  '國家級標準。著重生物多樣性、植物保護': 'National standard. Focused on biodiversity and plant protection.',
  '大幅減少化療，重視 IPM 綜合防治管理。': 'Substantially reduces chemical treatments; prioritises Integrated Pest Management (IPM).',
  'Organic (有機農業 - AB 인증)': 'Organic (Organic Farming – AB Certification)',
  '禁用人工合成化學肥料與系統性農藥。': 'Prohibits synthetic chemical fertilisers and systemic pesticides.',
  '只允許使用天然物質，如銅(波爾多液)與硫防霉。': 'Only natural substances permitted, such as copper (Bordeaux mixture) and sulphur for mildew.',
  'Biodynamic (生物動力法)': 'Biodynamic (Biodynamic Farming)',
  '將葡萄園視為獨立生態生命體。': 'Treats the vineyard as a self-contained ecological organism.',
  '依循日月星辰曆法，使用「500/501」等配方製劑。': 'Follows a lunar-solar calendar; uses preparations such as "500/501".',
  '💡 從科學管理到生態哲學：好酒，永遠誕生於健康的葡萄園中。': '💡 From scientific management to ecological philosophy: great wine is always born in a healthy vineyard.',

  // ── L3-5: Winemaking Process ──────────────────────────────────────────────
  '波爾多紅酒釀造完整流程': 'Complete Bordeaux Red Wine Winemaking Process',
  'Red Wine Winemaking · 從葡萄園到酒杯的蛻變之旅': 'Red Wine Winemaking · The Transformation from Vineyard to Glass',
  'STEP 1 · 採收 Harvest': 'STEP 1 · Harvest',
  '手工採摘或機械採收，依品種成熟度決定時機': 'Hand-picked or machine-harvested; timing determined by varietal ripeness',
  'Cabernet Sauvignon：9月底–10月初 · Merlot：9月中旬': 'Cabernet Sauvignon: late Sep–early Oct · Merlot: mid-September',
  'STEP 2 · 篩選去梗 Sorting &amp; Destemming': 'STEP 2 · Sorting &amp; Destemming',
  '光學分選台去除劣質果粒，去梗機分離果實與梗': 'Optical sorting table removes substandard berries; destemmer separates fruit from stems',
  '目的：避免青澀草味，提升果味純淨度': 'Purpose: eliminate green herbaceous notes; improve fruit purity',
  'STEP 3 · 破皮冷浸漬 Cold Maceration': 'STEP 3 · Cold Maceration',
  '5-10°C 低溫浸漬 3-5 天，萃取果香與花青素': '5–10°C cold soak for 3–5 days, extracting fruit aromatics and anthocyanins',
  '頂級酒莊常用，可強化色素但保留清新果香': 'Common at top châteaux; intensifies colour while preserving fresh fruit',
  'STEP 4 · 酒精發酵 Alcoholic Fermentation': 'STEP 4 · Alcoholic Fermentation',
  '酵母將糖轉化為酒精，溫度 25-32°C，持續 10-21 天': 'Yeast converts sugar to alcohol; 25–32°C, lasting 10–21 days',
  '淋皮（Pump Over）或踩皮（Punch Down）萃取色素與單寧': 'Pump-over or punch-down to extract colour and tannins',
  '殘糖至 &lt;2g/L 視為發酵完成': 'Fermentation deemed complete at residual sugar &lt;2 g/L',
  'STEP 5 · 乳酸發酵 Malolactic Fermentation': 'STEP 5 · Malolactic Fermentation',
  '蘋果酸轉化乳酸，軟化酸度，增加圓潤口感': 'Malic acid converts to lactic acid; softens acidity, adds roundness',
  '18-22°C · 持續 2-4 週 · 幾乎所有波爾多紅酒必做': '18–22°C · 2–4 weeks · carried out in virtually all Bordeaux reds',
  'STEP 6 · 橡木桶陳釀 Oak Aging': 'STEP 6 · Oak Ageing',
  '法國橡木桶（225L Barrique），12–24 個月陳釀': 'French oak barriques (225 L), 12–24 months ageing',
  '新桶比例：一級莊 80–100%，其他依風格調整': 'New barrel ratio: First Growths 80–100%; others adjusted to style',
  '目的：增加結構、香草/雪松香氣及緩慢微氧化': 'Purpose: build structure, add vanilla/cedar aromas, allow slow micro-oxygenation',
  'STEP 7 · 調配 Assemblage': 'STEP 7 · Assemblage (Blending)',
  '調配不同品種、地塊、酒齡，創造平衡風格': 'Blending different varieties, plots, and vintages to create a balanced style',
  '波爾多傳統：Cab.S. + Merlot + Cab.F. ± Petit Verdot': 'Bordeaux tradition: Cab.S. + Merlot + Cab.F. ± Petit Verdot',
  'STEP 8 · 澄清裝瓶 Fining &amp; Bottling': 'STEP 8 · Fining &amp; Bottling',
  '蛋清下膠去除懸浮物，輕微過濾後裝瓶': 'Egg-white fining to remove suspended matter; light filtration then bottling',
  '裝瓶後仍需瓶中陳年 1-2 年後上市（En Primeur 例外）': 'Post-bottling: 1–2 further years before release (En Primeur excepted)',
  '⏱ 典型時間軸（釀造週期）': '⏱ Typical Timeline (Production Cycle)',
  '採收': 'Harvest',
  '9–10月': 'Sep–Oct',
  '冷浸漬': 'Cold Soak',
  '+5天': '+5 days',
  '酒精發酵': 'Alc. Fermentation',
  '+10–21天': '+10–21 days',
  '乳酸發酵': 'Malolactic',
  '+2–4週': '+2–4 wks',
  '橡木桶': 'Oak Ageing',
  '12–24月': '12–24 mo',
  '調配': 'Assemblage',
  '陳釀中期': 'Mid-ageing',
  '裝瓶上市': 'Bottling & Release',
  '採收後2–3年': '2–3 yrs after harvest',
  '🔑 關鍵概念': '🔑 Key Concepts',
  '自由淌汁 (Free-run juice)': 'Free-run juice',
  '發酵後自然流出的酒，品質最高，單寧細膩': 'Wine that flows freely after fermentation; highest quality, fine tannins',
  '約佔總量 70-80%': 'Roughly 70–80% of total volume',
  '榨汁酒 (Press wine)': 'Press wine',
  '壓榨殘渣得到，單寧豐厚，': 'Obtained by pressing the marc; rich in tannins;',
  '可依需求加入混調增加結構': 'may be blended in to add structure',
  '二軍酒 (Second Wine)': 'Second Wine',
  '品質未達正牌標準的批次，': 'Batches that do not meet grand vin standards;',
  '以酒莊副牌名義出售，往往也極具性價比': 'sold under the château\'s second-label name, often outstanding value',
  '* 以上為波爾多頂級紅酒（Grand Vin）典型流程 · 各酒莊細節略有差異': '* The above represents the typical process for top Bordeaux red wine (Grand Vin) · details vary by château',

  // ── L3-6: Left vs Right Bank Assemblage ───────────────────────────────────
  '波爾多調配藝術：左岸 vs 右岸': 'The Art of Bordeaux Assemblage: Left Bank vs Right Bank',
  'Assemblage · 波爾多混釀的哲學與風格差異': 'Assemblage · The Philosophy and Style Contrast of Bordeaux Blending',
  '🏛️ 左岸 Left Bank': '🏛️ Left Bank',
  '左岸': 'Left Bank',
  '主導品種 · 55–75%': 'Dominant variety · 55–75%',
  '柔化骨架 · 15–35%': 'Softens structure · 15–35%',
  '增添優雅 · 3–15%': 'Adds elegance · 3–15%',
  '深色調 · 1–5%': 'Depth of colour · 1–5%',
  '🍷 風格特徵': '🍷 Style Profile',
  '結構強勁 · 單寧緊實 · 雪松黑醋栗香氣': 'Powerful structure · firm tannins · cedar and blackcurrant aromas',
  '需陳年 10–30 年方顯精彩 · 典型代表：Lafite / Latour': 'Needs 10–30 years to shine · Icons: Lafite / Latour',
  '🌱 右岸 Right Bank': '🌱 Right Bank',
  '右岸': 'Right Bank',
  '花香結構 · 0–40%': 'Floral structure · 0–40%',
  '少量補強 · 0–10%': 'Minor addition · 0–10%',
  '豐潤柔順 · 絲滑單寧 · 紅果李子松露香氣': 'Plush and supple · silky tannins · red fruit, plum and truffle aromas',
  '早熟易飲 · 適飲期 5–20 年 · 典型代表：Pétrus / Cheval Blanc': 'Early-maturing · drinking window 5–20 years · Icons: Pétrus / Cheval Blanc',
  '← 左岸   右岸 →': '← Left Bank   Right Bank →',
  '左岸 vs 右岸 風格對比矩陣': 'Left Bank vs Right Bank Style Comparison Matrix',
  '比較項目': 'Comparison',
  '左岸（Médoc）': 'Left Bank (Médoc)',
  '右岸（Pomerol/St-Émilion）': 'Right Bank (Pomerol/St-Émilion)',
  '主要土壤': 'Main Soil',
  '礫石（Graves）排水性佳': 'Gravel (Graves) — excellent drainage',
  '黏土、藍黏土（Crasse de Fer）': 'Clay, blue clay (Crasse de Fer)',
  '葡萄品種': 'Varieties',
  'Cabernet Sauvignon 主導': 'Cabernet Sauvignon dominant',
  'Merlot 主導': 'Merlot dominant',
  '酒體結構': 'Body & Structure',
  '高單寧、高酸度、強骨架': 'High tannins, high acidity, firm backbone',
  '柔順、圓潤、絲滑單寧': 'Soft, rounded, silky tannins',
  '最佳適飲期': 'Drinking Window',
  '10–30 年後': '10–30+ years',
  '5–20 年後（較早熟）': '5–20 years (earlier-maturing)',
  '主要香氣': 'Key Aromas',
  '黑醋栗・雪松・菸草・礦石': 'Blackcurrant · cedar · tobacco · mineral',
  '李子・松露・巧克力・紫羅蘭': 'Plum · truffle · chocolate · violet',
  '* 以上為一般規律，頂級酒莊往往超越產區典型，如 Cheval Blanc（右岸）的 Cab.Franc 比例達 40%，風格近乎左岸': '* The above are general patterns; top estates often transcend appellation norms — e.g. Cheval Blanc (Right Bank) uses ~40% Cab.Franc, approaching Left Bank style',

  // ── L3-9: Commercial Ecosystem & En Primeur ───────────────────────────────
  '波爾多葡萄酒商業生態圈系統': 'The Bordeaux Wine Commercial Ecosystem',
  'The Bordeaux Wine Business Ecosystem · 價值鏈與「波爾多市場（La Place de Bordeaux）」運作機制': 'The Bordeaux Wine Business Ecosystem · Value Chain & La Place de Bordeaux Operating Mechanism',
  '🏰 酒莊 (Châteaux)': '🏰 Châteaux (Producers)',
  '生產者': 'Producers',
  '• 專注葡萄種植與釀造': '• Focused on viticulture and winemaking',
  '• 制定品牌與定價策略': '• Sets brand and pricing strategy',
  '• 產量分配管理': '• Manages allocation',
  '🤝 經紀人 (Courtiers)': '🤝 Brokers (Courtiers)',
  '中介與保證人': 'Intermediaries & Guarantors',
  '• 連接酒莊與酒商': '• Connects châteaux with négociants',
  '• 價格談判與資訊傳遞': '• Price negotiation and information flow',
  '• 收取 2% 固定佣金': '• Charges a fixed 2% commission',
  '🏢 酒商 (Négociants)': '🏢 Merchants (Négociants)',
  '批發與出口商': 'Wholesalers & Exporters',
  '• 承擔庫存與資金風險': '• Bears inventory and financial risk',
  '• 全球分銷網絡': '• Global distribution network',
  '• 推廣與物流管理': '• Marketing and logistics management',
  'La Place de Bordeaux (波爾多市場/交易廣場)': 'La Place de Bordeaux (Bordeaux Exchange)',
  '💰 期酒制度 (En Primeur) 運作流程': '💰 En Primeur System: How It Works',
  '提前銷售還在橡木桶中陳釀的葡萄酒，創造「金融+商品」雙重期貨屬性': 'Selling wine still ageing in barrel — creating a dual "financial + commodity" futures dynamic',
  '採收與發釀': 'Harvest & Fermentation',
  '年份 N 的 9-10 月': 'Vintage N, September–October',
  '葡萄酒進入橡木桶': 'Wine enters oak barrels',
  '期酒品鑑週': 'En Primeur Tasting Week',
  '年份 N+1 的 4 月': 'Vintage N+1, April',
  '酒評家打分與定價': 'Critics score; châteaux set prices',
  '市場發售款': 'Market Release',
  '年份 N+1 的 5-6 月': 'Vintage N+1, May–June',
  '酒商/藏家支付定金': 'Merchants/collectors pay deposit',
  '裝瓶與交付': 'Bottling & Delivery',
  '年份 N+2 的 春季': 'Vintage N+2, Spring',
  '實體酒送達消費者': 'Physical bottles delivered to consumers',
  '酒莊優勢 (資金面)': 'Château Advantage (Cash Flow)',
  '提早18個月獲得現金流，降低倉儲與庫存壓力': 'Cash flow 18 months early; reduces storage and inventory pressure',
  '買家優勢 (投資面)': 'Buyer Advantage (Investment)',
  '以低於裝瓶後的價格(通常便宜15-30%)確保買到稀有配額': 'Secures rare allocations below post-bottling prices (typically 15–30% cheaper)',
  '💡 現代趨勢：部分頂級酒莊（如 Latour）正逐步減少期酒釋放比例，轉向於適飲期再從酒窖發售（Ex-Château）以提升利潤控制權。': '💡 Modern trend: some top châteaux (e.g. Latour) are gradually reducing En Primeur releases, shifting to direct Ex-Château sales at peak drinking maturity to regain pricing control.',

  // ── L4-1: Micro-Plot Analysis ─────────────────────────────────────────────
  '高階風土：微地塊精準分析與管理': 'Advanced Terroir: Precision Micro-Plot Analysis & Management',
  'Micro-Terroir Analysis · 從巨觀氣候到葡萄藤根系的四大層次解剖': 'Micro-Terroir Analysis · Four Levels from Macro-Climate to Vine Roots',
  '精準管理核心四維度 (Four Pillars of Precision Viticulture)': 'Four Pillars of Precision Viticulture',
  '⛰️ 1. 看地形': '⛰️ 1. Topography',
  '坡向、海拔、日照': 'Aspect, elevation, sun exposure',
  '影響微氣候與熱量累積': 'Affects microclimate and heat accumulation',
  '防止霜害冷空氣沉降': 'Prevents cold air settlement causing frost',
  '決定表層水流方向': 'Determines surface water flow direction',
  '🪨 2. 看土壤': '🪨 2. Soil Profile',
  '剖面、結構、礦物': 'Profile, structure, mineral content',
  '影響根系深度與養分': 'Affects root depth and nutrient uptake',
  '決定生長期的熱慣性': 'Determines thermal inertia during the growing season',
  '黏土/砂礫/石灰岩分區': 'Zoning of clay / gravel / limestone',
  '💧 3. 看水分': '💧 3. Water Dynamics',
  '排水力與水分壓力': 'Drainage capacity and water stress',
  '輕微缺水 (Water Stress)': 'Mild water stress (Water Stress)',
  '促使停止莖葉生長': 'Halts vegetative growth',
  '集中養分於果實成熟': 'Concentrates energy on fruit ripening',
  '🍇 4. 看釀造': '🍇 4. Plot-by-Plot Vinification',
  '地塊分離，分別處理': 'Separate plots, separately vinified',
  '依成熟度分批採收': 'Batch harvesting by ripeness level',
  '不同批次入小槽控溫': 'Different batches in small temperature-controlled tanks',
  '陳年後再精準混釀': 'Precision blending after ageing',
  '剖面透視：一塊完美頂級園土壤的隱藏結構': 'Cross-Section: The Hidden Structure of a Perfect Grand Cru Soil Profile',
  '表土層 (Topsoil) - 有機質、微生物豐富，積熱快速': 'Topsoil — organically rich, microbially active, heats quickly',
  '深砂礫層 (Deep Gravel)': 'Deep Gravel Layer',
  '出色排水性，白天蓄熱夜間釋放': 'Excellent drainage; absorbs heat by day, releases it at night',
  '黏土/石灰岩底土 (Clay &amp; Limestone Subsoil)': 'Clay &amp; Limestone Subsoil',
  '深層保水效果，極端乾旱時為根系提供水分與礦物': 'Deep moisture retention; supplies roots with water and minerals in extreme drought',
  '微地塊管理的紅利': 'Benefits of Micro-Plot Management',
  '完全成熟：單寧順滑無生青味': 'Full ripeness: smooth tannins, no green notes',
  '避開腐爛：低窪地提早採收': 'Avoid rot: harvest low-lying plots earlier',
  '豐富層次：將各坡度原酒混合': 'Layered complexity: blend wines from different slopes',
  '高價正牌：選取底土最佳區域': 'Premium Grand Vin: select from the finest subsoil zones',
  '💡 總結：微地塊管理就是對葡萄園進行「MRI斷層掃描」，不放過任何一處細微風土。': '💡 Summary: Micro-plot management is the MRI scan of the vineyard — no subtle terroir detail goes unexamined.',

  // ── L4-2: Advanced Winemaking Science ────────────────────────────────────
  '進階釀造科學：精準控制的三大核心': 'Advanced Winemaking Science: Three Pillars of Precision',
  '從傳統經驗法則到科學化品質工程 (From Empirical to Precision Enology)': 'From Empirical Tradition to Precision Quality Engineering',
  '1. 酵母代謝調控': '1. Yeast Metabolism Control',
  '氮源管理 (YAN)': 'Nitrogen Management (YAN)',
  '• 充足: 生成果香酯類': '• Adequate: generates fruity esters',
  '• 匱乏: 產生H2S(還原臭)': '• Deficient: produces H₂S (reductive off-odour)',
  '溫度曲線控制': 'Temperature Profile Control',
  '• 低溫(15℃): 保留揮發芳香': '• Low temp (15°C): preserves volatile aromatics',
  '• 高溫(28℃): 加速單寧萃取': '• High temp (28°C): accelerates tannin extraction',
  '目標：純淨香氣': 'Goal: Clean, pure aromatics',
  '2. 氧氣管理 (Ox Management)': '2. Oxygen Management',
  '發酵期 (Macro-ox)': 'Fermentation (Macro-oxygenation)',
  '• 需氧: 酵母細胞壁合成': '• Oxygen needed: yeast cell wall synthesis',
  '• 手段: 開放循環打水(Pump-over)': '• Method: open-circuit pump-over',
  '熟成期 (Micro-ox)': 'Ageing (Micro-oxygenation)',
  '• 微氧: 聚合單寧與花青素': '• Micro-oxygen: polymerises tannins and anthocyanins',
  '• 控氧: 惰性氣體保護/微氧機': '• Oxygen control: inert gas blanketing / micro-ox unit',
  '目標：顏色穩定與抗氧化': 'Goal: Colour stability and oxidation resistance',
  '3. 穩定化技術': '3. Stabilisation Techniques',
  '冷穩定 (Tartaric Auth)': 'Cold Stabilisation (Tartrate)',
  '• 防: 酒石酸結晶(鑽石)': '• Prevents: tartrate crystals ("wine diamonds")',
  '• 法: 降溫處理 / 電滲析微濾': '• Method: cold treatment / electrodialysis / microfiltration',
  '蛋白質與微生穩定': 'Protein & Microbiological Stabilisation',
  '• 防: 蛋白質混濁 / 酒香酵母(Brett)': '• Prevents: protein haze / Brettanomyces (Brett)',
  '• 法: 皂土澄清 / 精準SO2添加': '• Method: bentonite fining / precise SO₂ addition',
  '目標：長久如新': 'Goal: Freshness preserved long-term',
  '品質可預測 ｜ 風格可複製 ｜ 缺陷可追溯': 'Predictable Quality ｜ Reproducible Style ｜ Traceable Faults',

  // ── L4-3: French vs American Oak ─────────────────────────────────────────
  '橡木桶科學：法國橡木 vs 美國橡木': 'The Science of Oak Barrels: French Oak vs American Oak',
  'Oak Barrel Science · 木質、烘烤與風味萃取的完整解析': 'Oak Barrel Science · Complete Analysis of Wood, Toast & Flavour Extraction',
  '🌳 法國橡木 French Oak': '🌳 French Oak',
  'Quercus petraea · Allier / Vosges / Tronçais 森林': 'Quercus petraea · Allier / Vosges / Tronçais forests',
  '木紋緊密': 'Tight grain',
  '氣孔少，氧化緩慢': 'Fewer pores, slow oxygenation',
  '單寧細膩': 'Fine tannins',
  '萃取量少但質量高': 'Lower extraction but higher quality',
  '香氣貢獻': 'Aroma Contribution',
  '香草、丁香、雪松、': 'Vanilla, clove, cedar,',
  '煙燻、礦石': 'smoke, mineral',
  '製作工藝': 'Cooperage Craft',
  '手工劈裂（非鋸切）': 'Hand-split (not sawn)',
  '戶外風乾 2–4 年': 'Outdoor air-dried 2–4 years',
  '💰 成本與使用': '💰 Cost & Usage',
  '每桶 €800–1,500 · 波爾多頂級莊 80–100% 使用': '€800–1,500 per barrel · Bordeaux top estates use 80–100%',
  '新桶比例高 = 更多風味萃取，但過多會掩蓋果味': 'Higher new-barrel ratio = more flavour extraction, but excess can mask fruit',
  '🌲 美國橡木 American Oak': '🌲 American Oak',
  'Quercus alba · Missouri / Appalachian 森林': 'Quercus alba · Missouri / Appalachian forests',
  '木紋寬疏': 'Wide grain',
  '氣孔多，氧化較快': 'More pores, faster oxygenation',
  '單寧粗獷': 'Bolder tannins',
  '萃取量多，影響更明顯': 'Higher extraction, more pronounced influence',
  '椰子、香草（強烈）、': 'Coconut, vanilla (intense),',
  '奶油、甜香料': 'cream, sweet spice',
  '可機鋸，成本較低': 'Machine-sawn, lower cost',
  '烘乾較快，風乾 1–2 年': 'Faster drying, air-dried 1–2 years',
  '每桶 €300–600 · 較少用於波爾多，多見於Rioja': '€300–600 per barrel · less common in Bordeaux; widely used in Rioja',
  '部分酒莊用於二軍酒或追求特殊風格的實驗款': 'Some estates use it for second wines or experimental special styles',
  '🔥 烘烤程度（Toasting Level）的影響': '🔥 Effect of Toast Level',
  '輕度 Light': 'Light Toast',
  '保留更多木質單寧': 'Retains more woody tannins',
  '中度 Medium': 'Medium Toast',
  '香草、烤麵包、平衡': 'Vanilla, toasted bread, balance',
  '中重度 Med+': 'Medium+ Toast',
  '波爾多最常用，烤堅果香': 'Most common in Bordeaux, toasted nut aroma',
  '重度 Heavy': 'Heavy Toast',
  '咖啡、巧克力、煙燻，掩蓋果味': 'Coffee, chocolate, smoke — can overpower fruit',
  '🏆 波爾多名莊橡木桶策略': '🏆 Bordeaux Classified Estate Oak Strategy',
  '一級莊策略': 'First Growth Strategy',
  '100% 全新法國橡木桶 · 陳釀 18–24 個月 · 多家桶廠混用（如 Seguin Moreau, Taransaud）': '100% new French oak · 18–24 months ageing · multiple coopers (e.g. Seguin Moreau, Taransaud)',
  '→ 結果：豐富結構感、複雜香氣，與強勁的 Cab.S. 充分融合': '→ Result: rich structure, complex aromatics, seamlessly integrated with powerful Cab.S.',
  '中型莊策略': 'Mid-Tier Estate Strategy',
  '30–60% 新桶 · 其餘用 1–2 年舊桶 · 陳釀 12–18 個月': '30–60% new barrels · remainder 1–2 year-old barrels · 12–18 months ageing',
  '→ 平衡成本與風味，避免橡木味壓過果味': '→ Balances cost and flavour; prevents oak from dominating fruit',
  '* 近年趨勢：頂級莊逐漸降低新桶比例（70→60%），強調地塊個性而非木味': '* Recent trend: top estates gradually reducing new-barrel ratio (70→60%), prioritising plot identity over oak influence',

  // ── L4-4: Financial & ROI Model ──────────────────────────────────────────
  '酒莊經營基礎財務模型：從成本到投報': 'Château Financial Model Fundamentals: From Costs to ROI',
  '一瓶頂級酒的成本解構 (Cost Map)': 'Cost Breakdown of One Bottle of Fine Wine',
  '農務成本': 'Viticulture Costs',
  '釀造/人工': 'Winemaking / Labour',
  '橡木桶/設備': 'Oak Barrels / Equipment',
  '包裝行銷': 'Packaging & Marketing',
  '固定與變動成本 (OPEX)': 'Fixed & Variable Costs (OPEX)',
  '資本開支 (CAPEX) 與 投報評估': 'Capital Expenditure (CAPEX) & ROI Assessment',
  '購買高階光學篩選機 (€80,000)': 'Purchasing a high-end optical sorter (€80,000)',
  '→ 節省了多少人工挑選成本？': '→ How much manual sorting cost does it save?',
  '→ 提升了多少葡萄酒良率與升級正牌酒的機率？': '→ How much does it improve yield quality and the likelihood of upgrading to Grand Vin?',
  'ROI (投資回報率) = (預期收益 - 投資成本) / 投資成本': 'ROI = (Expected Gain - Investment Cost) / Investment Cost',
  '損益兩平點 (Break-Even) 與 敏感度': 'Break-Even Point & Sensitivity Analysis',
  '盈虧平衡點': 'Break-Even Point',
  '(例如: 年銷 50,000 瓶)': '(e.g. annual sales of 50,000 bottles)',
  '固定成本': 'Fixed Costs',
  '總成本': 'Total Costs',
  '總營收': 'Total Revenue',
  '高品質 + 嚴密的財務管控 = 可持續成長的頂級酒莊營運模型': 'High Quality + Rigorous Financial Control = A Sustainable Fine Château Operating Model',

  // ── L4-5: Brand Pyramid ───────────────────────────────────────────────────
  '品牌策略與國際市場拓展': 'Brand Strategy & International Market Expansion',
  '旗艦款': 'Icon Wine',
  '進階珍藏': 'Premium Reserve',
  '經典入門款': 'Classic Entry',
  '副牌 / 大眾通路款': 'Second Wine / Volume Range',
  '建立品牌最高天花板 (Icon)': 'Establishes the brand\'s quality ceiling (Icon)',
  '展示最高品質與風土極限': 'Showcases peak quality and terroir limits',
  '推升毛利的核心區間': 'Core segment driving gross margin',
  '品牌基本盤 (現金流主力)': 'Brand foundation (primary cash-flow engine)',
  '年輕藤/降級酒液有效變現': 'Young-vine / declassified juice monetised efficiently',
  '全球通路與在地化佈局': 'Global Distribution & Localisation',
  '文化適配 (Localization)': 'Cultural Adaptation (Localisation)',
  '北美大包裝、亞洲禮盒文化': 'Large formats for North America; gift-box culture in Asia',
  '通路分配 (Distribution)': 'Channel Distribution',
  '高階進餐廳、平價走超市': 'Premium tier into restaurants; entry tier into supermarkets',
  '數據型直客 (DTC)': 'Data-Driven DTC',
  '善用CRM計算LTV / 獲客成本': 'Leverage CRM to calculate LTV / customer acquisition cost',
  '品牌體驗與教育': 'Brand Experience & Education',
  '酒莊觀光、大師班體驗行銷': 'Château tourism, masterclasses and experiential marketing',
  '穩固的定價金字塔 ＋ 精準的通路適配 ＝ 可規模化的國際品牌': 'A solid pricing pyramid + precise channel alignment = a scalable international brand',

  // ── L4-6: AOC / PDO IP Protection ────────────────────────────────────────
  '法規與原產地：AOC/PDO 產權防護網': 'Regulations & Origin: The AOC/PDO Intellectual Property Shield',
  'AOC / PDO 原產地保護體系': 'AOC / PDO Protected Designation of Origin System',
  '合規管理與風險緩解機制 (Compliance &amp; Mitigation)': 'Compliance Management &amp; Risk Mitigation Mechanism',
  '產權證書': 'Title Deed',
  '界定風土': 'Defines Terroir',
  '歷史傳承': 'Historical Heritage',
  '專屬命名權': 'Exclusive Naming Rights',
  '生產規範': 'Production Rules',
  '品種工藝限制': 'Variety & Technique Restrictions',
  '侵權監測': 'Infringement Monitoring',
  '仿冒防護': 'Anti-Counterfeiting',
  '國際海關註冊': 'International Customs Registration',
  '救濟路徑': 'Remedies',
  '國際框架': 'International Framework',
  'EU 認證': 'EU Certification',
  '里斯本協定': 'Lisbon Agreement',
  'TRIPS 協議': 'TRIPS Agreement',
  'INao 國內審查': 'INAO Domestic Review',
  'WIPO 國際註冊': 'WIPO International Registration',
  '⚖️ 核心概念：原產地保護就像頂級房地產的「產權證書」': '⚖️ Core Concept: Protected designation is the "title deed" of premium real estate',
  '無產權證書，任何人皆可聲稱擁有；有生產規範，才能確保這片風土的文化遺產價值不會被稀釋。': 'Without a title deed, anyone can claim ownership; production rules ensure the cultural heritage of this terroir is never diluted.',

  // ── L4-7: Risk Management Matrix ─────────────────────────────────────────
  '酒莊全方位風險管理與保險防護矩陣': 'Château Comprehensive Risk Management & Insurance Matrix',
  '氣候與農務': 'Climate & Agricultural',
  '• 霜凍 / 冰雹': '• Frost / Hail',
  '• 乾旱 / 熱浪': '• Drought / Heatwave',
  '• 疾病蟲害': '• Disease & Pests',
  '產量保險險種': 'Yield Insurance Products',
  '營運與資產': 'Operations & Assets',
  '• 火災 / 竊盜': '• Fire / Theft',
  '• 污染 / 設備故障': '• Contamination / Equipment Failure',
  '• 供應鏈中斷': '• Supply Chain Disruption',
  '財產與責任險': 'Property & Liability Insurance',
  '市場與地緣政策': 'Market & Geopolitical',
  '• 關稅與貿易戰': '• Tariffs & Trade Wars',
  '• 匯率波動': '• Currency Fluctuation',
  '• 名譽受損 / 公關': '• Reputational Damage / PR Crisis',
  '避險與危機應變': 'Hedging & Crisis Response',
  '主動防護網 (Risk Mitigation)': 'Proactive Defence Network (Risk Mitigation)',
  '防霜風扇 / 冰雹網 / 消防安檢 / 網路備案': 'Frost fans / hail nets / fire inspections / IT backup',
  '主動降低出險機率，優化保費支出與企業韌性': 'Proactively reduces incident probability, optimising insurance costs and business resilience',
  '風險管理不只是買保險，而是為酒莊資產做「全方位健康體檢」': 'Risk management is not merely about buying insurance — it is a comprehensive health check for all château assets',

  // ── L4-8: ESG & Carbon Pathway ────────────────────────────────────────────
  '酒莊 ESG 永續經營與碳盤查路徑': 'Château ESG Sustainability & Carbon Footprint Pathway',
  'Environment(環境)': 'Environment',
  '碳排放管理 / 節水': 'Carbon management / water conservation',
  '土壤健康 / 生物多樣性': 'Soil health / biodiversity',
  'Social(社會)': 'Social',
  '勞工安全 / 居住權': 'Worker safety / housing rights',
  '在地社區回饋 / 供應鏈': 'Local community engagement / supply chain',
  'Governance(治理)': 'Governance',
  '透明公開 / 財報合規': 'Transparency / financial compliance',
  '道德經營 / 長期資本': 'Ethical management / long-term capital',
  '溫室氣體盤查 (GHG Protocol) 分類架構': 'GHG Inventory (GHG Protocol) Classification Framework',
  '範疇一 Scope 1': 'Scope 1',
  '直接排放 (5-10%)': 'Direct Emissions (5–10%)',
  '莊園柴油車/鍋爐': 'Estate diesel vehicles / boilers',
  '範疇二 Scope 2': 'Scope 2',
  '間接能源 (10-15%)': 'Indirect Energy (10–15%)',
  '購買的台電/外購電': 'Purchased grid electricity',
  '範疇三 Scope 3 (價值鏈上下游)': 'Scope 3 (Value Chain)',
  '最大隱性碳排來源 (70-85%)': 'Largest hidden emission source (70–85%)',
  '玻璃瓶/包裝': 'Glass bottles / packaging',
  '國際物流運輸': 'International freight & logistics',
  '商務旅行/通勤': 'Business travel / commuting',
  '永續不僅是環保，更是延長企業壽命、提升品牌全球競爭力的護城河': 'Sustainability is not merely about the environment — it is a moat that extends business longevity and strengthens global brand competitiveness',
  '推動玻璃瓶輕量化與轉用綠電，是目前投資報酬率最高的減碳捷徑。': 'Lightweighting glass bottles and switching to renewable electricity are currently the most cost-effective carbon reduction strategies.',
};

// Also handle font-family attribute (change to English fonts)
const OLD_FONT = "'Microsoft YaHei','PingFang TC','Noto Sans CJK TC',sans-serif";
const NEW_FONT = "'Segoe UI','Helvetica Neue','Arial',sans-serif";

const SVG_DIR = 'public/images';

function translateSVG(content) {
  let out = content;
  
  // Replace font-family
  out = out.split(OLD_FONT).join(NEW_FONT);
  
  // Replace text content: only inside > ... < (text nodes)
  for (const [zh, en] of Object.entries(TRANSLATIONS)) {
    // Direct replacement inside text nodes
    out = out.split('>' + zh + '<').join('>' + en + '<');
    // Also handle cases where the text is used in attribute values (like title=)
    out = out.split('"' + zh + '"').join('"' + en + '"');
  }
  
  return out;
}

let processed = 0;
let skipped = 0;

function processDir(dir) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      processDir(fullPath);
    } else if (entry.name.endsWith('.svg') && !/[\u4e00-\u9fff]/.test(entry.name)) {
      // Only process SVG files that have English names (already renamed)
      const orig = fs.readFileSync(fullPath, 'utf8');
      if (!/[\u4e00-\u9fff]/.test(orig)) {
        skipped++;
        return;
      }
      const translated = translateSVG(orig);
      if (translated !== orig) {
        fs.writeFileSync(fullPath, translated, 'utf8');
        const remaining = (translated.match(/[\u4e00-\u9fff]/g) || []).length;
        console.log(`  ✓ ${fullPath} (remaining CJK chars: ${remaining})`);
        processed++;
      }
    }
  }
}

console.log('\n=== Translating SVG text content ===');
processDir(SVG_DIR);
console.log(`\nProcessed: ${processed} files, Skipped: ${skipped} (already English)`);
console.log('\n✅ Phase 2 complete.');
