import json, pathlib

f = pathlib.Path("src/locales/en/lessons/bordeaux/l4-6.json")
data = json.loads(f.read_text(encoding="utf-8"))

data["slides.0.title"] = "Learning Objectives"
data["slides.1.title"] = "Chapter 1"
data["slides.1.subtitle"] = "Legal Framework"
data["slides.2.title"] = "Chapter 1: The Legal System for Origin Protection"
data["slides.2.highlights.0.title"] = "PDO / PGI / TSG"
data["slides.2.highlights.0.content"] = "The EU three-tier geographical indication protection system explained."
data["slides.2.highlights.1.title"] = "AOC → AOP Evolution"
data["slides.2.highlights.1.content"] = "France's institutional integration from 1935 to 2009."
data["slides.2.highlights.2.title"] = "International Agreements"
data["slides.2.highlights.2.content"] = "Lisbon Agreement, TRIPS and FTAs form a multi-layer protection network."
data["slides.3.title"] = "Chapter 2"
data["slides.3.subtitle"] = "Certification Standards"
data["slides.4.title"] = "Chapter 2: AOC/AOP Certification Process and Standards"
data["slides.4.highlights.0.title"] = "Six-Stage Process"
data["slides.4.highlights.0.content"] = "Application → delimitation → specifications → review → approval → monitoring."
data["slides.4.highlights.1.title"] = "Cahier des Charges"
data["slides.4.highlights.1.content"] = "Varieties, planting density, yields and winemaking all strictly defined."
data["slides.4.highlights.2.title"] = "Ongoing Audits"
data["slides.4.highlights.2.content"] = "Annual declarations and random checks ensure standards compliance."
data["slides.5.title"] = "Chapter 3"
data["slides.5.subtitle"] = "Infringement Protection"
data["slides.6.title"] = "Chapter 3: Infringement Monitoring and Legal Remedies"
data["slides.6.highlights.0.title"] = "Infringement Types"
data["slides.6.highlights.0.content"] = "Direct counterfeiting, suggestive use, dilution and online/domain infringement."
data["slides.6.highlights.1.title"] = "Monitoring Systems"
data["slides.6.highlights.1.content"] = "Market surveillance, customs recordal and AI digital monitoring."
data["slides.6.highlights.2.title"] = "Remedy Pathways"
data["slides.6.highlights.2.content"] = "Administrative, civil and criminal tracks — choose based on the situation."
data["slides.7.title"] = "Chapter 4"
data["slides.7.subtitle"] = "Compliance Strategy"
data["slides.8.title"] = "Chapter 4: Compliance Management and Risk Mitigation"
data["slides.8.highlights.0.title"] = "Four-Tier Framework"
data["slides.8.highlights.0.content"] = "Strategic, managerial, operational and oversight layers with clear responsibilities."
data["slides.8.highlights.1.title"] = "Risk Matrix"
data["slides.8.highlights.1.content"] = "Assess likelihood and impact to prioritise high-risk items."
data["slides.8.highlights.2.title"] = "Compliance Technology"
data["slides.8.highlights.2.content"] = "Blockchain, regulatory databases and AI alert tools enable compliance."
data["slides.9.title"] = "Chapter 5"
data["slides.9.subtitle"] = "Future Trends"
data["slides.10.title"] = "Chapter 5: Sustainability and Future Regulatory Trends"
data["slides.10.highlights.0.title"] = "Green Deal"
data["slides.10.highlights.0.content"] = "Halving pesticides, expanding organic area and mandatory carbon footprint disclosure."
data["slides.10.highlights.1.title"] = "e-Label Pilot"
data["slides.10.highlights.1.content"] = "QR Code dynamic labels replace part of printed back-label content."
data["slides.10.highlights.2.title"] = "Climate Adaptation"
data["slides.10.highlights.2.content"] = "Heat-tolerant varieties, irrigation rules and harvest flexibility evolving in regulations."
data["slides.11.title"] = "Course Summary"
data["slides.12.title"] = "Post-Course Quiz"

f.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
print("Done. Updated 36 short text keys.")
