import json

path = r"c:\Users\Chungshu\Desktop\教學網站製作20260220\Bordeaux Wine Learning\src\locales\en\lessons\bordeaux\l3-13-part1.json"

with open(path, encoding="utf-8") as f:
    data = json.load(f)

def tr(val, pairs):
    val = val.replace("[ZH] ", "").replace("[ZH]", "")
    for zh, en in pairs:
        val = val.replace(zh, en)
    return val

# ── slides.18.content ─────────────────────────────────────────────────────────
r18 = [
    ("AI品質控制系統｜光譜分析 × 電子感官",
     "AI Quality Control System | Spectral Analysis × Electronic Sensory"),
    ("NIR 30秒完成22項檢測 × 效率提升180倍 × 電子鼻/舌準確率97.8%",
     "NIR 30 s for 22 parameters × 180× efficiency gain × electronic nose/tongue accuracy 97.8%"),
    ("🌈 NIR近紅外光譜", "🌈 NIR Near-Infrared Spectroscopy"),
    ("30秒 × 22項參數同測", "30 s × 22 parameters simultaneously"),
    ("生產線即時在線分析", "Real-time on-line production line analysis"),
    ("無需開瓶非破壞檢測", "Non-destructive, no uncorking required"),
    ("R²=0.98 極高精度", "R²=0.98 extremely high precision"),
    ("Margaux裝瓶前2024：", "Margaux pre-bottling 2024:"),
    ("15罐×3天→15分鐘（效率×180）",
     "15 tanks × 3 days → 15 minutes (efficiency ×180)"),
    ("攔截罐#12揮發酸超標", "Intercepted tank #12 volatile acidity exceedance"),
    ("調配後即時驗證 ✓", "Immediate post-blending verification ✓"),
    ("節省€45,000/年", "Saves €45,000/year"),
    ("🔍 拉曼光譜防偽", "🔍 Raman Spectroscopy Anti-Counterfeiting"),
    ("分子指紋識別", "Molecular fingerprint identification"),
    ("無需開瓶 × 2分鐘完成", "No uncorking × 2-minute analysis"),
    ("200+特徵峰比對", "200+ characteristic peak comparison"),
    ("準確率 98.5%", "Accuracy 98.5%"),
    ("Pomerol 1982假酒鑑定：", "Pomerol 1982 counterfeit detection:"),
    ("與真品相似度僅67%", "Similarity to authentic wine only 67%"),
    ("（正常應&gt;95%）", "(authentic should be &gt;95%)"),
    ("126瓶可疑中發現38瓶假", "38 counterfeits found among 126 suspicious bottles"),
    ("保護品牌€1.7M/年", "Brand protection €1.7M/year"),
    ("🧬 GC-MS香氣指紋", "🧬 GC-MS Aroma Fingerprint"),
    ("300+種香氣化合物定量", "Quantification of 300+ aroma compounds"),
    ("建立酒款風味檔案", "Building wine style profiles"),
    ("缺陷溯源 × 陳年監測", "Defect traceability × ageing monitoring"),
    ("風格相似度量化", "Style similarity quantification"),
    ("Saint-Julien風格控制：", "Saint-Julien style control:"),
    ("吡嗪22→15 ng/L（修正）", "Pyrazine 22→15 ng/L (corrected)"),
    ("風格相似度72→96%", "Style similarity 72→96%"),
    ("預售比2023年+15%", "Pre-release sales +15% vs 2023"),
    ("「典型某某莊風格」", '"Authentic [château] style"'),
    ("👃 電子鼻 — TCA軟木塞檢測",
     "👃 Electronic Nose — TCA Cork Taint Detection"),
    ("裝瓶線 3秒/瓶 自動檢測", "Bottling line 3 s/bottle automated detection"),
    ("靈敏度 2 ng/L（人類感官閾值）",
     "Sensitivity 2 ng/L (human sensory threshold)"),
    ("系統可靠度：97.8%", "System reliability: 97.8%"),
    ("TCA陽性→移出→換塞→重測", "TCA positive → remove → replace cork → retest"),
    ("<span style=\"color:#553c9a;font-weight:700\">💡 Pauillac 50,000瓶裝瓶（2024）：</span>",
     "<span style=\"color:#553c9a;font-weight:700\">💡 Pauillac 50,000-bottle run (2024):</span>"),
    ("傳統人工：417小時 × 感官疲勞",
     "Traditional manual: 417 hours × sensory fatigue"),
    ("電子鼻：42小時 × 100%逐瓶檢測",
     "Electronic nose: 42 hours × 100% bottle-by-bottle detection"),
    ("檢出1,847瓶(3.69%) TCA污染",
     "Detected 1,847 bottles (3.69%) TCA contamination"),
    ("<span style=\"color:#c53030;font-weight:700\">→ 避免損失 €277,050 × ROI 32.6倍</span>",
     "<span style=\"color:#c53030;font-weight:700\">→ Loss avoided €277,050 × ROI 32.6×</span>"),
    ("👅 電子舌 — 味覺精準量化",
     "👅 Electronic Tongue — Precise Taste Quantification"),
    ("五種基本味覺精確測定", "Precise measurement of five basic tastes"),
    ("單寧強度/酒體/澀感量化",
     "Tannin intensity / body / astringency quantification"),
    ("平衡指數計算", "Balance index calculation"),
    ("預測準確度：98.5%", "Prediction accuracy: 98.5%"),
    ("<span style=\"color:#c05621;font-weight:700\">💡 Margaux三級莊調配（2024）：</span>",
     "<span style=\"color:#c05621;font-weight:700\">💡 Margaux third growth blending (2024):</span>"),
    ("18基酒 × AI計算10,000種組合",
     "18 base wines × AI calculates 10,000 combinations"),
    ("預測評分92 → 實際品鑑 <span style=\"font-weight:700\">93分</span>",
     "Predicted score 92 → actual tasting <span style=\"font-weight:700\">93 pts</span>"),
    ("風格相似度：94%（過去10年平均）",
     "Style similarity: 94% (10-year average)"),
    ("<span style=\"color:#c53030;font-weight:700\">→ 決策時間 3週→5天，節省76%</span>",
     "<span style=\"color:#c53030;font-weight:700\">→ Decision time 3 weeks→5 days, saving 76%</span>"),
    ("<div style=\"opacity:.85\">NIR效率提升</div>",
     "<div style=\"opacity:.85\">NIR efficiency gain</div>"),
    ("<div style=\"opacity:.85\">假酒識別準確率</div>",
     "<div style=\"opacity:.85\">Counterfeit detection accuracy</div>"),
    ("<div style=\"opacity:.85\">電子鼻攔截損失</div>",
     "<div style=\"opacity:.85\">E-nose loss prevented</div>"),
    ("<div style=\"opacity:.85\">電子舌節省調配時間</div>",
     "<div style=\"opacity:.85\">E-tongue blending time saved</div>"),
]
data["slides.18.content"] = tr(data["slides.18.content"], r18)

# ── slides.19.content ─────────────────────────────────────────────────────────
r19 = [
    ("AI輔助調配系統｜智能算法 × 虛擬實驗室",
     "AI-Assisted Blending System | Smart Algorithms × Virtual Laboratory"),
    ("從2.1億種組合到45分鐘決策·預測準確98%·「AI擔保陳年」",
     'From 210 million combinations to 45-minute decision · 98% prediction accuracy · "AI-guaranteed ageing"'),
    ("多目標優化引擎", "Multi-objective Optimisation Engine"),
    (">Pauillac案例<", ">Pauillac case<"),
    (">理論組合<", ">Theoretical combos<"),
    (">2.1億種<", ">210 million<"),
    ("64種基酒×185,000L", "64 base wines × 185,000 L"),
    (">AI計算<", ">AI calculation<"),
    (">500萬方案<", ">5 million plans<"),
    ("🏆 預測96分→實際95.5",
     "🏆 Predicted 96 pts→actual 95.5"),
    ("誤差僅0.5分", "Error only 0.5 pts"),
    ("💰 +€600,000收益", "💰 +€600,000 revenue"),
    ("利用率65%→73%", "Utilisation 65%→73%"),
    ("約束條件智能處理", "Intelligent Constraint Handling"),
    ("亞洲訂製款：12硬約束＋8軟約束",
     "Asia custom blend: 12 hard constraints + 8 soft constraints"),
    (">Merlot比例<", ">Merlot ratio<"),
    (">≥60%要求<", ">≥60% required<"),
    (">成本控制<", ">Cost control<"),
    (">≤€22上限<", ">≤€22 limit<"),
    (">毛利率<", ">Gross margin<"),
    (">翌年+15,000瓶<", ">+15,000 bottles next year<"),
    ("✅ 23分鐘求解·評分88.5分·開創「訂製化調配」新模式",
     '✅ Solved in 23 min · 88.5 pts · pioneering "customised blending" model'),
    ("機器學習調配引擎", "Machine Learning Blending Engine"),
    (">Margaux驚喜<", ">Margaux surprise<"),
    ("挖掘25年數據：發現人類忽視的隱藏模式",
     "Mining 25 years of data: discovering patterns humans missed"),
    ("🔍 反直覺推薦：地塊#11比例 3% → 22%",
     "🔍 Counter-intuitive recommendation: Plot #11 ratio 3% → 22%"),
    ("「違背30年經驗！」→ 釀酒師決定盲品對比",
     '"Defies 30 years of experience!" → winemaker decided to blind taste'),
    (">傳統配方<", ">Traditional formula<"),
    (">AI配方<", ">AI formula<"),
    ("Wine Advocate 95分（10年最高）｜期酒+25%｜+€12/瓶",
     "Wine Advocate 95 pts (10-year high) | en primeur +25% | +€12/bottle"),
    ("虛擬調配實驗室", "Virtual Blending Laboratory"),
    (">零風險<", ">Zero risk<"),
    ("Pessac-Léognan白酒穩定性預警",
     "Pessac-Léognan white wine stability warning"),
    (">虛擬模擬<", ">Virtual simulation<"),
    ("傳統需1-2個月", "Traditional: 1–2 months"),
    ("⚠️ 警報發現", "⚠️ Alert detected"),
    ("蛋白質沉澱", "Protein precipitation"),
    ("風險68%", "Risk 68%"),
    ("✅ 澄清預處理", "✅ Clarification pre-treatment"),
    ("成本僅€180", "Cost only €180"),
    ("風險降至5%", "Risk reduced to 5%"),
    ("❌ 若無預警", "❌ Without warning"),
    ("10,000L混濁", "10,000 L haze"),
    ("損失€120,000", "Loss €120,000"),
    ("50年陳年潛力預測", "50-year Ageing Potential Forecast"),
    ("3個配方AI陳年預測對比", "AI ageing forecast comparison of 3 blends"),
    (">方案A<", ">Blend A<"),
    ("89分·封閉25年", "89 pts · closed for 25 years"),
    (">方案B ✓<", ">Blend B ✓<"),
    ("91分·30年巔峰", "91 pts · peak at 30 years"),
    (">方案C ✗<", ">Blend C ✗<"),
    ("30年後不適飲", "Undrinkable after 30 years"),
    ("限量6,660瓶｜首批3,000瓶2週售罄",
     "Limited to 6,660 bottles | first 3,000 bottles sold out in 2 weeks"),
    ("每瓶附AI陳年曲線｜「AI擔保陳年承諾」",
     'Each bottle includes AI ageing curve | "AI-guaranteed ageing pledge"'),
    ("<div style=\"opacity:.85\">決策時間節省</div>",
     "<div style=\"opacity:.85\">Decision time saved</div>"),
    ("從6週→3天", "From 6 weeks→3 days"),
    ("<div style=\"opacity:.85\">預測準確度</div>",
     "<div style=\"opacity:.85\">Prediction accuracy</div>"),
    ("<div style=\"opacity:.85\">500萬方案分析</div>",
     "<div style=\"opacity:.85\">5 million plans analysed</div>"),
    ("<div style=\"opacity:.85\">虛擬實驗室</div>",
     "<div style=\"opacity:.85\">Virtual laboratory</div>"),
    ("<div style=\"opacity:.85\">每次避免損失</div>",
     "<div style=\"opacity:.85\">Loss avoided per use</div>"),
    ("<div style=\"opacity:.85\">WA評分提升</div>",
     "<div style=\"opacity:.85\">WA score improvement</div>"),
    ("<div style=\"opacity:.85\">AI發現隱藏配方</div>",
     "<div style=\"opacity:.85\">AI discovered hidden blend</div>"),
]
data["slides.19.content"] = tr(data["slides.19.content"], r19)

with open(path, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Saved l3-13-part1.json (slides.18 + slides.19 updated)")
