import json

path = r"c:\Users\Chungshu\Desktop\教學網站製作20260220\Bordeaux Wine Learning\src\locales\en\lessons\bordeaux\l3-13-part1.json"

with open(path, encoding="utf-8") as f:
    data = json.load(f)

def tr(val, pairs):
    val = val.replace("[ZH] ", "").replace("[ZH]", "")
    for zh, en in pairs:
        val = val.replace(zh, en)
    return val

# ── slides.10.content ─────────────────────────────────────────────────────────
r10 = [
    ("多源數據整合分析（一）｜多維度數據收集",
     "Multi-Source Data Integration Analysis (I) | Multi-Dimensional Data Collection"),
    ("現代酒莊每天生成海量數據 × 內部生產 + 外部環境 = 完整圖像",
     "Modern châteaux generate massive data daily × internal production + external environment = complete picture"),
    ("🏭 內部生產數據", "🏭 Internal Production Data"),
    ("🌿 葡萄園管理數據", "🌿 Vineyard Management Data"),
    ("農事操作記錄 × 修剪/疏果/採收", "Farm operation records × pruning / thinning / harvest"),
    ("投入品使用 × 肥料/農藥/水量", "Input usage × fertiliser / agrochemicals / water"),
    ("各地塊產量與品質分級", "Yield and quality grading by plot"),
    ("人工與材料成本核算", "Labour and materials cost accounting"),
    ("<span style=\"color:#2b6cb0;font-weight:700\">💡 Château Margaux：</span>",
     "<span style=\"color:#2b6cb0;font-weight:700\">💡 Château Margaux:</span>"),
    ("每地塊每15分鐘記錄土壤濕度", "Soil moisture recorded every 15 minutes per plot"),
    ("工人平板記錄每次修剪與位置", "Workers use tablets to record each pruning action and location"),
    ("每箱葡萄QR碼追蹤來源地塊", "Every crate QR-code-traced back to source plot"),
    ("<span style=\"color:#c53030;font-weight:700\">→ 一季累積超過 50萬筆 田間數據</span>",
     "<span style=\"color:#c53030;font-weight:700\">→ Over 500,000 field data entries accumulated per season</span>"),
    ("🍷 釀造工藝數據", "🍷 Winemaking Process Data"),
    ("發酵參數 × 溫度/密度/pH曲線", "Fermentation parameters × temperature / density / pH curves"),
    ("工藝流程時間與操作記錄", "Process timing and operation logs"),
    ("化學分析與感官評估數據", "Chemical analyses and sensory evaluation data"),
    ("橡木桶陳年詳細追蹤", "Detailed oak barrel ageing tracking"),
    ("<span style=\"color:#2b6cb0;font-weight:700\">💡 一桶Pauillac紅酒的數據足跡：</span>",
     "<span style=\"color:#2b6cb0;font-weight:700\">💡 Data footprint of one barrel of Pauillac red wine:</span>"),
    ("發酵期 288個溫度點（12天）", "Fermentation: 288 temperature readings (12 days)"),
    ("蘋果酸乳酸發酵 54次化學分析", "MLF: 54 chemical analyses"),
    ("橡木桶陳年 36次記錄（18月）", "Oak ageing: 36 records (18 months)"),
    ("<span style=\"color:#c53030;font-weight:700\">→ 一桶酒超過 400個 追蹤數據點</span>",
     "<span style=\"color:#c53030;font-weight:700\">→ Over 400 tracking data points per barrel</span>"),
    ("🌐 外部環境數據", "🌐 External Environmental Data"),
    ("🌤️ 氣象數據整合", "🌤️ Weather Data Integration"),
    ("歷史氣象 × 30年以上數據庫", "Historical weather × 30+ year database"),
    ("即時監測 × 多站位數據", "Real-time monitoring × multi-station data"),
    ("衛星遙感 × 區域氣象信息", "Satellite remote sensing × regional weather information"),
    ("預測數據 × 7–15天天氣預報", "Forecast data × 7–15 day weather outlook"),
    ("<span style=\"color:#276749;font-weight:700\">💡 Saint-Émilion產區氣象網：</span>",
     "<span style=\"color:#276749;font-weight:700\">💡 Saint-Émilion appellation weather network:</span>"),
    ("5個地面站每10分鐘記錄氣象", "5 ground stations record weather every 10 minutes"),
    ("衛星每週2次提供植被指數", "Satellite provides vegetation index twice weekly"),
    ("區域模型提供10天微氣候預測", "Regional model provides 10-day microclimate forecast"),
    ("<span style=\"color:#c53030;font-weight:700\">→ 年度累積 260萬筆 氣象數據</span>",
     "<span style=\"color:#c53030;font-weight:700\">→ 2.6 million weather data entries accumulated annually</span>"),
    ("📈 市場信息數據", "📈 Market Information Data"),
    ("價格趨勢 × 國際/國內市場", "Price trends × international / domestic markets"),
    ("消費者偏好與行為數據", "Consumer preference and behaviour data"),
    ("競爭對手產品與策略分析", "Competitor product and strategy analysis"),
    ("進出口量與貿易流向", "Import/export volumes and trade flows"),
    ("<span style=\"color:#276749;font-weight:700\">💡 波爾多列級莊市場監測：</span>",
     "<span style=\"color:#276749;font-weight:700\">💡 Bordeaux classified growth market monitoring:</span>"),
    ("追蹤全球12大市場拍賣價（每週）", "Track auction prices in 12 major global markets (weekly)"),
    ("分析社媒品牌提及與消費評論", "Analyse social-media brand mentions and consumer reviews"),
    ("監控50家競爭對手定價策略", "Monitor pricing strategies of 50 competitors"),
    ("<span style=\"color:#c53030;font-weight:700\">→ 整合海關數據追蹤新興市場</span>",
     "<span style=\"color:#c53030;font-weight:700\">→ Integrate customs data to track emerging markets</span>"),
    ("<div style=\"opacity:.85\">田間管理數據/季</div>",
     "<div style=\"opacity:.85\">field data/season</div>"),
    ("<div style=\"opacity:.85\">追蹤數據點/桶</div>",
     "<div style=\"opacity:.85\">tracking data points/barrel</div>"),
    ("<div style=\"opacity:.85\">氣象數據/年</div>",
     "<div style=\"opacity:.85\">weather data/year</div>"),
    ("<div style=\"opacity:.85\">全球市場監測</div>",
     "<div style=\"opacity:.85\">global markets monitored</div>"),
]
data["slides.10.content"] = tr(data["slides.10.content"], r10)

# ── slides.11.content ─────────────────────────────────────────────────────────
r11 = [
    ("多源數據整合分析（二）｜數據處理與清洗",
     "Multi-Source Data Integration Analysis (II) | Data Processing and Cleaning"),
    ("原始數據如同剛採收的葡萄 × 清洗去除「爛果」× 特徵工程提取「精華」",
     'Raw data is like freshly harvested grapes × cleaning removes "bad fruit" × feature engineering extracts the "essence"'),
    ("💾 數據預處理", "💾 Data Pre-processing"),
    ("🧹 數據清洗", "🧹 Data Cleaning"),
    ("異常值檢測與識別處理", "Outlier detection and treatment"),
    ("缺失值統計補全", "Missing value imputation"),
    ("跨來源格式標準化", "Cross-source format standardisation"),
    ("不同頻率數據時間對齊", "Time alignment for data at different frequencies"),
    ("<span style=\"color:#553c9a;font-weight:700\">💡 2023年夏季氣象數據案例：</span>",
     "<span style=\"color:#553c9a;font-weight:700\">💡 Summer 2023 weather data case:</span>"),
    ("問題：3天氣象缺失 + −999°C異常讀數",
     "Issue: 3 days of missing weather + −999°C anomalous readings"),
    ("解法：線性插值補全 + 範圍過濾 + ISO 8601統一",
     "Fix: linear interpolation + range filter + ISO 8601 standardisation"),
    ("<span style=\"color:#c53030;font-weight:700\">→ 數據完整度 73% ➜ 98%</span>",
     "<span style=\"color:#c53030;font-weight:700\">→ Data completeness 73% ➜ 98%</span>"),
    ("⚙️ 特徵工程", "⚙️ Feature Engineering"),
    ("變數轉換與數學運算", "Variable transformation and mathematical processing"),
    ("特徵選擇（最佳影響因子）", "Feature selection (top influencing factors)"),
    ("維度降維 × 提高處理效率", "Dimensionality reduction × improved processing efficiency"),
    ("領域知識構建新特徵", "Domain knowledge for constructing new features"),
    ("<span style=\"color:#553c9a;font-weight:700\">💡 構建「成熟度指數」：</span>",
     '<span style="color:#553c9a;font-weight:700">💡 Building the "Ripeness Index":</span>'),
    ("積溫度日(GDD) = Σ(日均溫 − 10°C)",
     "Growing Degree Days (GDD) = Σ(daily avg temp − 10°C)"),
    ("糖酸比 = 葡萄糖度 / 總酸度",
     "Sugar-acid ratio = grape sugar / total acidity"),
    ("水分脅迫指數 = (降雨 − 蒸散) / 持水量",
     "Water stress index = (rainfall − evapotranspiration) / field capacity"),
    ("<span style=\"color:#c53030;font-weight:700\">→ 預測準確度提升 35%</span>",
     "<span style=\"color:#c53030;font-weight:700\">→ Prediction accuracy improved by 35%</span>"),
    ("🔍 探索性分析", "🔍 Exploratory Analysis"),
    ("📊 統計描述分析", "📊 Statistical Descriptive Analysis"),
    ("分布特徵 × 規律分析", "Distribution characteristics × pattern analysis"),
    ("相關性 × 線性/非線性關係", "Correlations × linear/non-linear relationships"),
    ("趨勢分析 × 時間序列", "Trend analysis × time series"),
    ("群組分析 × 自然分群", "Cluster analysis × natural groupings"),
    ("<span style=\"color:#c05621;font-weight:700\">💡 2010–2025波爾多研究：</span>",
     "<span style=\"color:#c05621;font-weight:700\">💡 2010–2025 Bordeaux research:</span>"),
    ("7–8月夜間溫度 × 酒質：<span style=\"color:#276749;font-weight:700\">+0.78 正相關</span>",
     "Jul–Aug night temperature × wine quality: <span style=\"color:#276749;font-weight:700\">+0.78 positive correlation</span>"),
    ("成熟期降雨 × 品質：<span style=\"color:#c53030;font-weight:700\">−0.65 負相關</span>",
     "Harvest-period rainfall × quality: <span style=\"color:#c53030;font-weight:700\">−0.65 negative correlation</span>"),
    ("<span style=\"color:#c53030;font-weight:700\">→ 8月10–20日決定年份品質 60%！</span>",
     "<span style=\"color:#c53030;font-weight:700\">→ 10–20 Aug determines 60% of vintage quality!</span>"),
    ("📈 視覺化分析", "📈 Visual Analytics"),
    ("時間序列圖 × 趨勢展示", "Time-series charts × trend visualisation"),
    ("散點圖矩陣 × 多變數關係", "Scatter plot matrix × multivariate relationships"),
    ("熱力圖 × 相關性與地理分布", "Heat maps × correlations and geographic distribution"),
    ("箱線圖 × 組間比較", "Box plots × between-group comparisons"),
    ("<span style=\"color:#c05621;font-weight:700\">💡 Pomerol地塊品質熱力圖：</span>",
     "<span style=\"color:#c05621;font-weight:700\">💡 Pomerol plot quality heat map:</span>"),
    ("50個地塊 × 10年品質評分分析", "50 plots × 10 years of quality score analysis"),
    ("東南坡：穩定度高（標準差 1.2分）", "South-east slope: high stability (std dev 1.2 pts)"),
    ("北側低窪：波動大（標準差 3.8分）", "North lowland: high variability (std dev 3.8 pts)"),
    ("<span style=\"color:#c53030;font-weight:700\">→ 指導優質年份混釀比例決策</span>",
     "<span style=\"color:#c53030;font-weight:700\">→ Guides blending ratio decisions for top vintages</span>"),
    (">原始數據<", ">Raw Data<"),
    (">清洗補全<", ">Clean &amp; Fill<"),
    (">格式統一<", ">Standardise<"),
    (">特徵工程<", ">Feature Engineering<"),
    (">探索分析<", ">Exploratory Analysis<"),
    (">模型輸入 ✓<", ">Model Input ✓<"),
    ("<div style=\"opacity:.8\">數據完整度提升</div>",
     "<div style=\"opacity:.8\">Data completeness gain</div>"),
    ("<div style=\"opacity:.8\">預測準確度</div>",
     "<div style=\"opacity:.8\">Prediction accuracy</div>"),
    ("<div style=\"opacity:.8\">夜間溫度×酒質相關</div>",
     "<div style=\"opacity:.8\">Night temp × quality correlation</div>"),
    ("<div style=\"opacity:.8\">年份品質由8月決定</div>",
     "<div style=\"opacity:.8\">Vintage quality determined by Aug</div>"),
]
data["slides.11.content"] = tr(data["slides.11.content"], r11)

with open(path, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Saved l3-13-part1.json (slides.10 + slides.11 updated)")
