"""
Translate [ZH]-prefixed locale keys in l4-9.json, l4-10.json, l4-11.json
and translate Chinese strings within HTML content blocks.
"""
import json, re, os

BASE = os.path.join(os.path.dirname(__file__), '..', 'src', 'locales', 'en', 'lessons', 'bordeaux')

# ──────────────────────────────────────────────
# l4-9.json  – Sensory Science
# ──────────────────────────────────────────────
def translate_l4_9():
    path = os.path.join(BASE, 'l4-9.json')
    with open(path, encoding='utf-8') as f:
        data = json.load(f)

    # Short key translations
    short = {
        "slides.0.title": "Learning Objectives",
        "slides.1.subtitle": "Sensory Science",
        "slides.1.title": "Chapter 1",
        "slides.2.highlights.0.content": "~400 receptor types, ppt-level detection, spatial encoding patterns.",
        "slides.2.highlights.0.title": "Olfactory Mechanism",
        "slides.2.highlights.1.content": "Perceived intensity drops 50% within 60 seconds; requires interval and reset.",
        "slides.2.highlights.1.title": "Rapid Adaptation",
        "slides.2.highlights.2.content": "TAS2R38 causes up to 10× variation in bitterness sensitivity.",
        "slides.2.highlights.2.title": "Genetic Differences",
        "slides.2.title": "Chapter 1: Sensory Science Foundations and Neural Mechanisms",
        "slides.3.subtitle": "Calibration Protocol",
        "slides.3.title": "Chapter 2",
        "slides.4.highlights.0.content": "Visual 30s → Olfactory 90s → Gustatory 60s → Conclusion 30s.",
        "slides.4.highlights.0.title": "SAT Protocol",
        "slides.4.highlights.1.content": "Statistical significance requires accuracy > 60% (n=20).",
        "slides.4.highlights.1.title": "Triangle Test",
        "slides.4.highlights.2.content": "ICC > 0.75, SD < 5 pts, test-retest r > 0.85.",
        "slides.4.highlights.2.title": "Consistency Metrics",
        "slides.4.title": "Chapter 2: Standardised Tasting Protocol and Calibration",
        "slides.5.subtitle": "Fault Identification",
        "slides.5.title": "Chapter 3",
        "slides.6.highlights.0.content": "2–4 ng/L (ppt level), up to 10× individual variation.",
        "slides.6.highlights.0.title": "TCA Threshold",
        "slides.6.highlights.1.content": "Some regard concentrations <400 μg/L as adding complexity.",
        "slides.6.highlights.1.title": "Brett Controversy",
        "slides.6.highlights.2.content": "Mild cases dissipate with decanting; severe mercaptans are irreversible.",
        "slides.6.highlights.2.title": "Reduction Dynamics",
        "slides.6.title": "Chapter 3: Wine Fault Identification and Quantification",
        "slides.7.subtitle": "Typicity Matrix",
        "slides.7.title": "Chapter 4",
        "slides.8.highlights.0.content": "Triple verification: varietal, regional, and stylistic typicity.",
        "slides.8.highlights.0.title": "Three-Level Typicity",
        "slides.8.highlights.1.content": "Pyrazine (green pepper) + high tannins + cedar.",
        "slides.8.highlights.1.title": "Cab Markers",
        "slides.8.highlights.2.content": "Colour → Aroma → Climate → Winemaking → Confidence.",
        "slides.8.highlights.2.title": "Decision Tree",
        "slides.8.title": "Chapter 4: Typicity Matrix and Blind Tasting Strategy",
        "slides.9.subtitle": "Competition Strategy",
        "slides.9.title": "Chapter 5",
        "slides.10.highlights.0.content": "Scan 2 min → Deep analysis 3 min → Confirm 1 min.",
        "slides.10.highlights.0.title": "Three-Round Strategy",
        "slides.10.highlights.1.content": "R深+ B雪松Oak A中+ T高↑ = Cab Pauillac。",  # keep as-is (notation example)
        "slides.10.highlights.1.title": "Shorthand Notation",
        "slides.10.highlights.2.content": "Variety → Climate → Region → Winemaking → Ageing → Competition.",
        "slides.10.highlights.2.title": "12-Week Plan",
        "slides.10.title": "Chapter 5: Advanced Blind Tasting Techniques and Competition Strategies",
        "slides.11.content": "<p>From neurophysiological mechanisms to competition strategies, this course establishes a systematic sensory evaluation framework. Mastering the calibration protocol (ICC > 0.75), fault quantification (TCA detection threshold 2 ng/L), the typicity matrix (varietal/regional/stylistic triple verification), and time management (three-round tasting method) enables reproducible expert-level blind tasting performance.</p>",
        "slides.11.title": "Course Summary",
        "slides.12.title": "Post-lesson Quiz",
    }
    for k, v in short.items():
        if k in data:
            data[k] = v

    # HTML content block translations — replace Chinese strings within HTML
    html_replacements = [
        # slides.2.content  — table headers & widget labels
        ('[ZH] ', ''),
        # Table 1 headers
        ('<th>階段</th><th>機制</th><th>關鍵要素</th><th>葡萄酒應用</th>',
         '<th>Stage</th><th>Mechanism</th><th>Key Elements</th><th>Wine Application</th>'),
        # Table 1 rows
        ('<td>1. 揮發物釋放</td><td>分子從酒液揮發至鼻腔</td><td>溫度、搖杯、酒精濃度</td><td>適溫提升香氣釋放</td>',
         '<td>1. Volatile Release</td><td>Molecules volatilise from wine into the nasal cavity</td><td>Temperature, swirling, alcohol concentration</td><td>Optimal temperature enhances aroma release</td>'),
        ('<td>2. 受體結合</td><td>氣味分 子與嗅覺受體蛋白結合</td><td>~400 種受體 (人類)</td><td>複雜香氣需多受體共同識別</td>',
         '<td>2. Receptor Binding</td><td>Odour molecules bind to olfactory receptor proteins</td><td>~400 receptor types (human)</td><td>Complex aromas require multiple receptors</td>'),
        ('<td>3. 訊號轉換</td><td>G 蛋白偶聯受體 GPCR (G Protein-Coupled Receptor) 放大訊號</td><td>cAMP (cyclic Adenosine Monophosphate) 二級訊使</td><td>極低濃度可被偵測 (ppt 級)</td>',
         '<td>3. Signal Transduction</td><td>GPCR (G Protein-Coupled Receptor) amplifies signal</td><td>cAMP (cyclic Adenosine Monophosphate) second messenger</td><td>Detectable at extremely low concentrations (ppt level)</td>'),
        ('<td>4. 嗅 球處理</td><td>訊號彙集至嗅球 glomeruli</td><td>空間編碼模式</td><td>不同香氣產 生獨特編碼</td>',
         '<td>4. Olfactory Bulb Processing</td><td>Signals converge at olfactory bulb glomeruli</td><td>Spatial encoding patterns</td><td>Different aromas generate unique encodings</td>'),
        ('<td>5. 大腦整合</td><td>前嗅皮質、杏仁核、海馬體</td><td>記憶、情緒連結</td><td>香氣觸發產區/品種聯想</td>',
         '<td>5. Brain Integration</td><td>Piriform cortex, amygdala, hippocampus</td><td>Memory and emotional connections</td><td>Aromas trigger regional/varietal associations</td>'),
        # Table 2 headers
        ('<th>基本味覺</th><th>受體類型</th><th>敏感區域</th><th>葡萄酒中來源</th><th>閾 值</th>',
         '<th>Basic Taste</th><th>Receptor Type</th><th>Sensitive Region</th><th>Source in Wine</th><th>Threshold</th>'),
        # Table 2 rows
        ('<td> 甜味</td><td>T1R2+T1R3</td><td>舌尖、軟顎</td><td>殘糖、甘油</td><td>0.5~1% (葡 萄糖)</td>',
         '<td>Sweetness</td><td>T1R2+T1R3</td><td>Tip of tongue, soft palate</td><td>Residual sugar, glycerol</td><td>0.5–1% (glucose)</td>'),
        ('<td>酸味</td><td>H⁺ 離子通道</td><td>舌側</td><td>酒石酸、蘋果酸</td><td>pH 3.0 可感</td>',
         '<td>Acidity</td><td>H⁺ ion channels</td><td>Sides of tongue</td><td>Tartaric acid, malic acid</td><td>Detectable at pH 3.0</td>'),
        ('<td>苦味</td><td>T2R (25 種)</td><td>舌根</td><td>單寧、種子多酚</td><td>極低 (演化保護機制)</td>',
         '<td>Bitterness</td><td>T2R (25 types)</td><td>Back of tongue</td><td>Tannins, seed polyphenols</td><td>Very low (evolutionary protection mechanism)</td>'),
        ('<td>鹹味</td><td>Na⁺ 通道</td><td>舌前側</td><td>礦物質 (微量)</td><td>0.05% NaCl</td>',
         '<td>Saltiness</td><td>Na⁺ channels</td><td>Front of tongue</td><td>Minerals (trace)</td><td>0.05% NaCl</td>'),
        ('<td>鮮味</td><td>T1R1+T1R3</td><td>全舌</td><td>氨基酸 (陳年)</td><td>0.01% MSG (Monosodium Glutamate)</td>',
         '<td>Umami</td><td>T1R1+T1R3</td><td>Whole tongue</td><td>Amino acids (aged wines)</td><td>0.01% MSG (Monosodium Glutamate)</td>'),
        # Sensory adaptation widget headers  
        ('<h3>感官適應與疲勞</h3>', '<h3>Sensory Adaptation and Fatigue</h3>'),
        ('<label for="adapt-olfactory">嗅覺適應</label>', '<label for="adapt-olfactory">Olfactory Adaptation</label>'),
        ('<label for="adapt-gustatory">味覺疲勞</label>', '<label for="adapt-gustatory">Gustatory Fatigue</label>'),
        ('<label for="adapt-cross">跨感官影響</label>', '<label for="adapt-cross">Cross-modal Effects</label>'),
        ('<h4>嗅覺適應 (Olfactory Adaptation)</h4>', '<h4>Olfactory Adaptation</h4>'),
        ('<li><strong>快速適應</strong>: 持續暴露於同一香 氣 30~60 秒後，感知強度下降 50~70%。</li>',
         '<li><strong>Rapid Adaptation</strong>: Continuous exposure to the same aroma for 30–60 seconds reduces perceived intensity by 50–70%.</li>'),
        ('<li><strong>受體飽 和</strong>: 嗅覺受體去敏化，需 3~5 分鐘恢復。</li>',
         '<li><strong>Receptor Saturation</strong>: Olfactory receptors desensitise; 3–5 minutes needed for recovery.</li>'),
        ('<li><strong>盲品應對</strong>:', '<li><strong>Blind Tasting Response</strong>:'),
        ('<li>每款 酒間隔 2~3 分鐘，中間聞咖啡豆或自己手臂 (重置嗅覺)。</li>',
         '<li>Allow 2–3 minutes between each wine; sniff coffee beans or the back of your wrist (reset olfaction).</li>'),
        ('<li>避免連續品評同一品種 (如連續 5 款 Cabernet)。</li>',
         '<li>Avoid tasting the same variety consecutively (e.g. 5 Cabernets in a row).</li>'),
        ('<li>開場先聞中性樣品 (水、酒精溶液) 校準基準。</li>',
         '<li>Begin with a neutral sample (water, alcohol solution) to calibrate the baseline.</li>'),
        ('<p class="note">嗅覺疲勞是品評最大敵人，專業面板每天品評不超過 40~50 款。</p>',
         '<p class="note">Olfactory fatigue is the greatest enemy of tasting; professional panels evaluate no more than 40–50 wines per day.</p>'),
        ('<h4>味覺疲勞 Gustatory Fatigue</h4>', '<h4>Gustatory Fatigue</h4>'),
        ('<li><strong>酸疲勞</strong>: 連續品評高酸酒後，敏感度下降，建議用清水漱口。</li>',
         '<li><strong>Acid Fatigue</strong>: Sensitivity decreases after tasting multiple high-acid wines; rinse with plain water.</li>'),
        ('<li><strong>單寧累積</strong>: 單寧與唾液蛋白結合產生澀感，需間隔並食用中性食物 (麵包)。</li>',
         '<li><strong>Tannin Accumulation</strong>: Tannins bind with salivary proteins causing astringency; take breaks and eat neutral foods (bread).</li>'),
        ('<li><strong>酒精麻痺</strong>: 高酒精度酒款麻痺味蕾，品評順序應從低到高 ABV (Alcohol by Volume)。</li>',
         '<li><strong>Alcohol Anaesthesia</strong>: High-ABV wines numb the palate; taste in ascending ABV order.</li>'),
        ('<li><strong>甜味飽和</strong>: 甜酒後品干型酒會顯得過酸，需調整 順序 (干→甜)。</li>',
         '<li><strong>Sweetness Saturation</strong>: Dry wines taste excessively acidic after sweet wines; always taste dry before sweet.</li>'),
        ('<p class="note">標準品評順序: 氣泡→白 (干→甜)→紅 (輕→重)→加烈甜酒。</p>',
         '<p class="note">Standard tasting sequence: Sparkling → White (dry → sweet) → Red (light → full) → Fortified sweet.</p>'),
        ('<h4>跨感 官影響 Cross-modal Effects</h4>', '<h4>Cross-modal Effects</h4>'),
        ('<li><strong>顏色偏誤</strong>: 深色酒被評為更濃郁 (視覺影響味覺)，盲品需用黑色杯或紅光 。</li>',
         '<li><strong>Colour Bias</strong>: Darker wines are perceived as more concentrated; use black glasses or red lighting for blind tasting.</li>'),
        ('<li><strong>溫度影響</strong>: 低溫抑制甜味感知 (+30%)、增強酸味 (+20%)，高溫反之。</li>',
         '<li><strong>Temperature Effect</strong>: Low temperature suppresses sweetness (+30%) and enhances acidity (+20%); high temperature does the opposite.</li>'),
        ('<li><strong>音響效應</strong>: 高頻聲音增強甜味感知，低頻增強苦味 (避免吵雜環境)。</li>',
         '<li><strong>Sonic Effect</strong>: High-frequency sounds enhance sweet perception; low frequency enhances bitterness (avoid noisy environments).</li>'),
        ('<li><strong>期望效應</strong>: 已知品牌/價格會提升評分 15~20% (盲品消除偏誤)。</li>',
         '<li><strong>Expectation Effect</strong>: Knowing the brand/price raises scores by 15–20% (blind tasting eliminates this bias).</li>'),
        ('<p class="note">專業品評室需控制: 白光 (5000K)、20~22°C、無香氛、安靜環境。</p>',
         '<p class="note">Professional tasting rooms require: white light (5000K), 20–22°C, fragrance-free, quiet environment.</p>'),
        ('<h3>感官記憶與訓練</h3>', '<h3>Sensory Memory and Training</h3>'),
        ('<li><strong>短期感官記憶</strong>: 僅保留 3~7 個香氣特徵，需立即記錄。</li>',
         '<li><strong>Short-term Sensory Memory</strong>: Retains only 3–7 aroma characteristics; record immediately.</li>'),
        ('<li><strong>長期記憶建立</strong>: 重複暴露 (10+ 次) 建立穩定香氣-詞彙連結。</li>',
         '<li><strong>Long-term Memory Formation</strong>: Repeated exposure (10+ times) builds stable aroma–vocabulary associations.</li>'),
        ('<li><strong>標準樣品庫</strong>: 使用 Le Nez du Vin 等香氣套組訓練識別準確度。</li>',
         '<li><strong>Reference Sample Library</strong>: Use aroma kits such as Le Nez du Vin to train identification accuracy.</li>'),
        ('<li><strong>盲品訓練</strong>: 每週至少 2 次盲品 (3~5 款)，記錄錯誤模式並校正。</li>',
         '<li><strong>Blind Tasting Practice</strong>: At least 2 blind tasting sessions per week (3–5 wines); log error patterns and correct them.</li>'),
        ('<h3>個體差異與基因影響</h3>', '<h3>Individual Variation and Genetic Influence</h3>'),
        ('<th>變異因素</th><th>影響</th><th>人群占比</th><th>品評調整</th>',
         '<th>Variable Factor</th><th>Effect</th><th>Population %</th><th>Tasting Adjustment</th>'),
        ('<td>TAS2R38 基因</td><td>苦味敏感度差異 10 倍</td><td>25% 超級品嚐者</td><td>苦味評分需校準</td>',
         '<td>TAS2R38 gene</td><td>10× variation in bitterness sensitivity</td><td>25% supertasters</td><td>Bitterness scores must be calibrated</td>'),
        ('<td>OR7D4 基因</td><td>雄烯酮 (androstenone) 無法感知</td><td>~30% 嗅盲</td><td>避免作為主要描述詞</td>',
         '<td>OR7D4 gene</td><td>Cannot perceive androstenone</td><td>~30% anosmic</td><td>Avoid as a primary descriptor</td>'),
        ('<td>年齡</td><td>60 歲後嗅覺受體減少 50%</td><td>老化影響</td><td>定期重新校準</td>',
         '<td>Age</td><td>Olfactory receptors decrease 50% after age 60</td><td>Ageing effect</td><td>Recalibrate regularly</td>'),
        ('<td>性別</td><td>女性平均嗅覺敏感度高 10~15%</td><td>生理差異</td><td>面板性別平衡</td>',
         '<td>Sex</td><td>Women average 10–15% higher olfactory sensitivity</td><td>Physiological difference</td><td>Balance panel by sex</td>'),
        ('<h3>嗅覺受體與神經傳導</h3>', '<h3>Olfactory Receptors and Neural Transmission</h3>'),
        ('<h3>味覺受體分布與感知</h3>', '<h3>Taste Receptor Distribution and Perception</h3>'),

        # slides.4.content — SAT protocol
        ('<h3>SAT (Systematic Approach to Tasting) 結構化流程</h3>',
         '<h3>SAT (Systematic Approach to Tasting) Structured Protocol</h3>'),
        ('<li><strong>視覺評估 (30 秒)</strong>: 澄清度、濃度、顏色、黏度、氣泡 (若有)。</li>',
         '<li><strong>Visual Assessment (30 s)</strong>: Clarity, intensity, colour, viscosity, bubbles (if present).</li>'),
        ('<li><strong>嗅覺評估 (90 秒)</strong>: 狀態、強度、發展 階段、香氣特徵 (3 層次)。</li>',
         '<li><strong>Olfactory Assessment (90 s)</strong>: Condition, intensity, development stage, aroma characteristics (3 tiers).</li>'),
        ('<li><strong>味覺評估 (60 秒)</strong>: 甜度、酸度、單寧、酒精、酒體、風味強度、餘韻。</li>',
         '<li><strong>Gustatory Assessment (60 s)</strong>: Sweetness, acidity, tannins, alcohol, body, flavour intensity, finish.</li>'),
        ('<li><strong>結論 (30 秒)</strong>: 品質評級、發展潛力、典型性、產區/品種推論。</li>',
         '<li><strong>Conclusion (30 s)</strong>: Quality rating, development potential, typicity, region/variety inference.</li>'),
        ('<h3>系統化品評表 (SAT)</h3>', '<h3>Systematic Tasting Sheet (SAT)</h3>'),
        ('<th>評估項目</th><th>評分尺度</th><th>關鍵指標</th><th>典型描述詞</th>',
         '<th>Assessment Item</th><th>Scale</th><th>Key Indicators</th><th>Typical Descriptors</th>'),
        ('<td>外觀濃度</td><td>淡 / 中 / 深</td><td>色素密度、透光性</td><td>Pale, Medium, Deep</td>',
         '<td>Appearance Intensity</td><td>Pale / Medium / Deep</td><td>Pigment density, light transmission</td><td>Pale, Medium, Deep</td>'),
        ('<td>香氣強度</td><td>淡 / 中- / 中 / 中+ / 濃</td><td>初聞 (不搖杯) 可感程度</td><td>Light, Pronounced</td>',
         '<td>Aroma Intensity</td><td>Light / Med– / Med / Med+ / Pronounced</td><td>Detectable without swirling</td><td>Light, Pronounced</td>'),
        ('<td>酸度</td><td>低 / 中- / 中 / 中+ / 高</td><td>唾液分泌、舌側刺激</td><td>Low, High</td>',
         '<td>Acidity</td><td>Low / Med– / Med / Med+ / High</td><td>Salivation, lateral tongue stimulation</td><td>Low, High</td>'),
        ('<td>單寧</td><td>低 / 中- / 中 / 中+ / 高</td><td>澀感強度、質地</td><td>Fine-grained, Grippy</td>',
         '<td>Tannins</td><td>Low / Med– / Med / Med+ / High</td><td>Astringency intensity, texture</td><td>Fine-grained, Grippy</td>'),
        ('<td>酒體</td><td>淡 / 中- / 中 / 中+ / 飽滿</td><td>口腔重量感、黏度</td><td>Light, Full-bodied</td>',
         '<td>Body</td><td>Light / Med– / Med / Med+ / Full</td><td>Weight in mouth, viscosity</td><td>Light, Full-bodied</td>'),
        ('<td>餘韻</td><td>短 / 中- / 中 / 中+ / 長</td><td>吞嚥後持續時間 (秒)</td><td>Short (<3s), Long (>8s)</td>',
         '<td>Finish</td><td>Short / Med– / Med / Med+ / Long</td><td>Duration after swallowing (seconds)</td><td>Short (<3s), Long (>8s)</td>'),
        ('<td>品質</td><td>差 / 可接受 /  良好 / 優 / 傑出</td><td>平衡、複雜度、餘韻</td><td>Acceptable, Outstanding</td>',
         '<td>Quality</td><td>Poor / Acceptable / Good / Very Good / Outstanding</td><td>Balance, complexity, finish</td><td>Acceptable, Outstanding</td>'),
        ('<h3>校準訓練方法</h3>', '<h3>Calibration Training Methods</h3>'),
        ('<label for="calib-triangle">三 角測試</label>', '<label for="calib-triangle">Triangle Test</label>'),
        ('<label for="calib-reference">標準樣品</label>', '<label for="calib-reference">Reference Standards</label>'),
        ('<label for="calib-consensus">共識會議</label>', '<label for="calib-consensus">Consensus Discussion</label>'),
        ('<h4>三角測試 (Triangle Test)</h4>', '<h4>Triangle Test</h4>'),
        ('<p><strong>目的</strong>: 測試品評者區分細微差異的能力。</p>',
         '<p><strong>Purpose</strong>: Test evaluators\' ability to distinguish subtle differences.</p>'),
        ('<p><strong>流程</strong>:</p>', '<p><strong>Protocol</strong>:</p>'),
        ('<li>提供 3 杯酒: 2 杯相同 (A)、1 杯不同 (B)。</li>',
         '<li>Provide 3 glasses: 2 identical (A) and 1 different (B).</li>'),
        ('<li>品評者需識別哪一杯與其他兩杯不同。</li>',
         '<li>Evaluator must identify which glass differs from the other two.</li>'),
        ('<li>隨機猜測正確率 33%，統計顯 著需 > 60% (n=20)。</li>',
         '<li>Random chance = 33%; statistical significance requires > 60% correct (n=20).</li>'),
        ('<p><strong>應用案例</strong>:</p>', '<p><strong>Applications</strong>:</p>'),
        ('<li>測試是否能區分同產區不同地塊 (Pauillac vs St-Julien)。</li>',
         '<li>Test ability to distinguish plots within the same appellation (Pauillac vs St-Julien).</li>'),
        ('<li>測試是否能區 分不同橡木桶處理 (法國桶 vs 美國桶)。</li>',
         '<li>Test ability to distinguish different oak treatments (French vs American oak).</li>'),
        ('<li>測試缺陷閾值 (如 TCA 2 ng/L vs 4 ng/L)。</li>',
         '<li>Test fault thresholds (e.g. TCA 2 ng/L vs 4 ng/L).</li>'),
        ('<p class="note">訓練建議: 每月 1 次三角測試，追蹤正確率趨勢。</p>',
         '<p class="note">Training tip: conduct a triangle test monthly and track accuracy trends.</p>'),
        ('<h4>標準樣品校準 (Reference Standards)</h4>', '<h4>Reference Standards Calibration</h4>'),
        ('<p><strong>目的</strong>: 建立共同的評分基準。</p>',
         '<p><strong>Purpose</strong>: Establish a shared scoring baseline.</p>'),
        ('<li>準備已知品質等級的樣品 (Good, Very Good, Outstanding)。</li>',
         '<li>Prepare samples of known quality levels (Good, Very Good, Outstanding).</li>'),
        ('<li>全體品評者獨立評分。</li>', '<li>All evaluators score independently.</li>'),
        ('<li>比對評分與標準答案，識別系統性偏差。</li>',
         '<li>Compare scores to the reference answers to identify systematic bias.</li>'),
        ('<li>調整個人評分尺度 (如某人系統性低估 5 分)。</li>',
         '<li>Adjust individual scoring scale (e.g. if someone systematically underscores by 5 pts).</li>'),
        ('<p><strong>標準樣品庫示例</strong>:</p>', '<p><strong>Reference Sample Examples</strong>:</p>'),
        ('<th>品質等級</th><th>參考酒款</th><th>關鍵特徵</th>',
         '<th>Quality Level</th><th>Reference Wine</th><th>Key Characteristics</th>'),
        ('<td>Acceptable (65~69)</td><td>基本 AC Bordeaux</td><td>無缺陷但缺乏複雜度</td>',
         '<td>Acceptable (65–69)</td><td>Basic AC Bordeaux</td><td>Fault-free but lacking complexity</td>'),
        ('<td>Good (70~79)</td><td>村莊級 Burgundy</td><td>正確、平衡、典型</td>',
         '<td>Good (70–79)</td><td>Village-level Burgundy</td><td>Correct, balanced, typical</td>'),
        ('<td>Very Good (80~89)</td><td>Cru Bourgeois Médoc</td><td>複雜、平衡、餘韻中+</td>',
         '<td>Very Good (80–89)</td><td>Cru Bourgeois Médoc</td><td>Complex, balanced, finish Med+</td>'),
        ('<td>Outstanding (90~100)</td><td>Grand Cru Classé</td><td>卓越複雜度與陳年潛力</td>',
         '<td>Outstanding (90–100)</td><td>Grand Cru Classé</td><td>Exceptional complexity and ageing potential</td>'),
        ('<p class="note">每 季度重新校準一次，使用新年份樣品。</p>',
         '<p class="note">Recalibrate quarterly using new vintage samples.</p>'),
        ('<h4>共識會議 (Consensus Discussion)</h4>', '<h4>Consensus Discussion</h4>'),
        ('<p><strong>目的</strong>: 統一描述詞使用 與評分標準。</p>',
         '<p><strong>Purpose</strong>: Unify descriptor usage and scoring standards.</p>'),
        ('<li>品評者獨立評估同一酒款並打分。</li>',
         '<li>Evaluators independently assess and score the same wine.</li>'),
        ('<li>公開所有評分，計算標準差 (SD)。</li>',
         '<li>Reveal all scores; calculate standard deviation (SD).</li>'),
        ('<li>若 SD > 5 分，進行討論:', '<li>If SD > 5 pts, hold a discussion:'),
        ('<li>高分者說明為何 給高分 (複雜度、平衡、餘韻)。</li>',
         '<li>Higher scorers explain why they scored high (complexity, balance, finish).</li>'),
        ('<li>低分者說明扣分原因 (缺陷、不平衡)。</li>',
         '<li>Lower scorers explain their deductions (faults, imbalance).</li>'),
        ('<li>重新品評並修正評分，達成共識 (SD < 3)。</li>',
         '<li>Re-taste and revise scores to reach consensus (SD < 3).</li>'),
        ('<p><strong>常見分歧來源</strong>:</p>', '<p><strong>Common Sources of Disagreement</strong>:</p>'),
        ('<li><strong>描述詞歧義</strong>: "Earthy" 可能指正面礦物感或負面霉味。</li>',
         '<li><strong>Descriptor Ambiguity</strong>: "Earthy" may refer to positive mineral character or negative mouldy notes.</li>'),
        ('<li><strong>個人偏好</strong>: 高酸愛好者vs高酒精愛好者。</li>',
         '<li><strong>Personal Preference</strong>: High-acid lovers vs high-alcohol lovers.</li>'),
        ('<li><strong>經驗差距</strong>: 新手與專家對 "複雜度" 理解不同。</li>',
         '<li><strong>Experience Gap</strong>: Novices and experts have different understandings of "complexity".</li>'),
        ('<p class="note">共識會議不是要求完全一致，而是縮小無謂分歧。</p>',
         '<p class="note">Consensus discussion aims not for perfect uniformity, but to reduce unnecessary disagreement.</p>'),
        ('<h3>評分一致性指標</h3>', '<h3>Scoring Consistency Metrics</h3>'),
        ('<th>指標</th><th>計算方式</th><th>合格標準</th><th>應用</th>',
         '<th>Metric</th><th>Calculation</th><th>Acceptable Standard</th><th>Application</th>'),
        ('<td>組內相關係數 (ICC)</td><td>品評者間評分相關性</td><td>ICC > 0.75</td><td>面板整體信度</td>',
         '<td>Intraclass Correlation (ICC)</td><td>Score correlation between evaluators</td><td>ICC > 0.75</td><td>Overall panel reliability</td>'),
        ('<td>標準差 (SD)</td><td>同酒款評分離散程度</td><td>SD < 5 分</td><td>單一酒款共識</td>',
         '<td>Standard Deviation (SD)</td><td>Score dispersion for same wine</td><td>SD < 5 pts</td><td>Single wine consensus</td>'),
        ('<td>重測信度</td><td>同品評者 2 週後重測相關</td><td>r > 0.85</td><td>個人穩定性</td>',
         '<td>Test-retest Reliability</td><td>Same evaluator retests after 2 weeks</td><td>r > 0.85</td><td>Individual stability</td>'),
        ('<td>敏感度 (d\')</td><td>區分能力 (信號偵測理論)</td><td>d\' > 1.5</td><td>品評者篩選</td>',
         '<td>Sensitivity (d\')</td><td>Discrimination ability (signal detection theory)</td><td>d\' > 1.5</td><td>Evaluator screening</td>'),
        ('<h3>盲品環境標準化</h3>', '<h3>Blind Tasting Environment Standardisation</h3>'),
        ('<li><strong>酒杯</strong>: ISO 標準杯 (INAO 杯)， 容量 210 ml，倒 50 ml。</li>',
         '<li><strong>Glasses</strong>: ISO standard glass (INAO glass), 210 ml capacity, pour 50 ml.</li>'),
        ('<li><strong>溫度</strong>: 白酒 10~12°C，紅酒 16~18°C，±2°C 控制。</li>',
         '<li><strong>Temperature</strong>: White wines 10–12°C, red wines 16–18°C, ±2°C control.</li>'),
        ('<li><strong>順序</strong>: 隨機化避免順序效應，使用拉丁方格設計。</li>',
         '<li><strong>Order</strong>: Randomise to avoid order effects; use a Latin square design.</li>'),
        ('<li><strong>編碼</strong>: 三位數隨機碼，避免誘導性編號 (如 1, 2, 3)。</li>',
         '<li><strong>Coding</strong>: Three-digit random codes; avoid leading numbers (e.g. 1, 2, 3).</li>'),
        ('<li><strong>時間</strong>: 上午 10~12 點最佳 (感官敏銳度高峰)。</li>',
         '<li><strong>Timing</strong>: 10 am–12 pm is optimal (peak sensory acuity).</li>'),

        # slides.6.content — Wine faults
        ('<h3>常見葡萄酒缺陷分類</h3>', '<h3>Common Wine Fault Classification</h3>'),
        ('<th>缺陷類型</th><th>化學來源</th><th>感官特徵</th><th>閾值</th><th>來源</th>',
         '<th>Fault Type</th><th>Chemical Source</th><th>Sensory Character</th><th>Threshold</th><th>Origin</th>'),
        ('<td>軟木塞污染</td><td>TCA (三氯苯甲醚)</td><td>潮濕紙板、霉味、果味壓抑</td><td>2~4 ng/L</td><td>受污染軟木塞</td>',
         '<td>Cork Taint</td><td>TCA (2,4,6-trichloroanisole)</td><td>Damp cardboard, mould, suppressed fruit</td><td>2–4 ng/L</td><td>Contaminated corks</td>'),
        ('<td>揮發酸</td><td>乙酸 (VA)</td><td>醋味、指甲油去光水</td><td>0.7 g/L (紅)、0.6 g/L (白)</td><td>醋酸菌、Brettanomyces</td>',
         '<td>Volatile Acidity</td><td>Acetic acid (VA)</td><td>Vinegar, nail polish remover</td><td>0.7 g/L (red), 0.6 g/L (white)</td><td>Acetobacter, Brettanomyces</td>'),
        ('<td>Brett 污染</td><td>4-EP, 4-EG</td><td>馬廄、OK 繃、煙燻培根</td><td>400~600 μg/L</td><td>Brettanomyces 酵母</td>',
         '<td>Brett Contamination</td><td>4-EP, 4-EG</td><td>Stable, plasters, smoky bacon</td><td>400–600 μg/L</td><td>Brettanomyces yeast</td>'),
        ('<td>還原味</td><td>H₂S, 硫醇</td><td>臭雞蛋、燒焦橡膠、大蒜</td><td>1~10 μg/L</td><td>缺氧發酵、酵母壓力</td>',
         '<td>Reduction</td><td>H₂S, mercaptans</td><td>Rotten egg, burnt rubber, garlic</td><td>1–10 μg/L</td><td>Anaerobic fermentation, yeast stress</td>'),
        ('<td>氧化</td><td>乙醛</td><td>蘋果醋、焦糖、失去果味</td><td>100~125 mg/L</td><td>過度氧氣接觸</td>',
         '<td>Oxidation</td><td>Acetaldehyde</td><td>Apple cider vinegar, caramel, loss of fruit</td><td>100–125 mg/L</td><td>Excessive oxygen exposure</td>'),
        ('<td>光照劣變</td><td>硫醇 (光誘導)</td><td>濕羊毛、煮高麗菜</td><td>極低</td><td>UV 光暴露 (透明 瓶)</td>',
         '<td>Light Strike</td><td>Mercaptans (light-induced)</td><td>Wet wool, cooked cabbage</td><td>Very low</td><td>UV exposure (clear bottles)</td>'),
        ('<td>熱傷害</td><td>美拉德產物</td><td>煮水果、 焦糖化、平板</td><td>N/A</td><td>高溫儲存 (>25°C)</td>',
         '<td>Heat Damage</td><td>Maillard products</td><td>Stewed fruit, caramelisation, flat</td><td>N/A</td><td>High-temperature storage (>25°C)</td>'),
        ('<h3>缺陷識別訓練套組</h3>', '<h3>Fault Identification Training Kit</h3>'),
        ('<label for="fault-tca">TCA</label>', '<label for="fault-tca">TCA</label>'),
        ('<label for="fault-brett">Brett</label>', '<label for="fault-brett">Brett</label>'),
        ('<label for="fault-reduction">還原</label>', '<label for="fault-reduction">Reduction</label>'),
        ('<label for="fault-oxidation">氧化</label>', '<label for="fault-oxidation">Oxidation</label>'),
        ('<h4>TCA (軟木塞污染)</h4>', '<h4>TCA (Cork Taint)</h4>'),
        ('<p><strong>化學本質</strong>: 2,4,6-三氯苯甲醚，極低閾值 (2~4 ng/L = ppt 級)。</p>',
         '<p><strong>Chemistry</strong>: 2,4,6-trichloroanisole; extremely low threshold (2–4 ng/L = ppt level).</p>'),
        ('<p><strong>感官描述</strong>:</p>', '<p><strong>Sensory Description</strong>:</p>'),
        ('<li>輕度 (2~5 ng/L): 果味壓抑、略顯乏味，易誤判為「封閉」。</li>',
         '<li>Mild (2–5 ng/L): Suppressed fruit, slightly dull; easily mistaken for "closed".</li>'),
        ('<li>中度 (5~15 ng/L): 明顯潮濕紙板、地窖味、霉味。</li>',
         '<li>Moderate (5–15 ng/L): Clear damp cardboard, cellar, musty notes.</li>'),
        ('<li> 重度 (>15 ng/L): 強烈霉味主導，酒款完全毀壞。</li>',
         '<li>Severe (>15 ng/L): Overpowering mould; wine completely ruined.</li>'),
        ('<p><strong>訓練方法</strong>:</p>', '<p><strong>Training Method</strong>:</p>'),
        ('<li>購買 TCA 標準溶液 (如 WineFaults 套組)。</li>',
         '<li>Purchase TCA standard solution (e.g. WineFaults kit).</li>'),
        ('<li> 在中性白酒中添加 2、5、10、20 ng/L 濃度。</li>',
         '<li>Add 2, 5, 10, 20 ng/L concentrations to neutral white wine.</li>'),
        ('<li>盲品排序，建立個人閾值曲線。</li>',
         '<li>Blind-taste and rank to establish personal threshold curve.</li>'),
        ('<li>對比未污染樣品，感受果味壓抑程度 。</li>',
         '<li>Compare with uncontaminated sample; feel the degree of fruit suppression.</li>'),
        ('<p><strong>誤判陷阱</strong>: 輕度 TCA 常被誤認為「酒款太年輕需醒酒」。</p>',
         '<p><strong>Misidentification Trap</strong>: Mild TCA is often mistaken for "wine too young, needs decanting".</p>'),
        ('<p class="note"> 統計: 天然軟木塞污染率 2~5%，螺旋蓋可避免 TCA。</p>',
         '<p class="note">Stat: Natural cork taint rate 2–5%; screwcaps eliminate TCA.</p>'),
        ('<p><strong>化學本質</strong>: 4-乙基苯酚 (4-EP) 與 4-乙基愈創木酚 (4-EG)。</p>',
         '<p><strong>Chemistry</strong>: 4-ethylphenol (4-EP) and 4-ethylguaiacol (4-EG).</p>'),
        ('<li>低濃度 (<400 μg/L): 煙燻、皮革、「野性」，部分人認為增加複雜度。</li>',
         '<li>Low concentration (<400 μg/L): Smoky, leather, "wild"; some consider it adds complexity.</li>'),
        ('<li>中濃度 (400~800 μg/L): 馬廄、汗味、OK 繃。</li>',
         '<li>Moderate concentration (400–800 μg/L): Stable, sweat, plasters.</li>'),
        ('<li>高濃度 (>800 μg/L): 糞便味、腐敗，完全掩蓋果味。</li>',
         '<li>High concentration (>800 μg/L): Faecal, putrid; completely masks fruit.</li>'),
        ('<p><strong>產區爭議</strong>:</p>', '<p><strong>Regional Controversy</strong>:</p>'),
        ('<li><strong>舊 世界</strong>: 部分 Rhône、Burgundy 生產者認為低度 Brett 是 terroir 一部分。</li>',
         '<li><strong>Old World</strong>: Some Rhône and Burgundy producers consider low-level Brett part of terroir.</li>'),
        ('<li><strong>新世界</strong>: 多數酒莊視為缺陷，嚴格控制 (目標 <200 μg/L)。</li>',
         '<li><strong>New World</strong>: Most wineries treat it as a fault; strict control (target <200 μg/L).</li>'),
        ('<li>對比「乾淨」Syrah vs 有 Brett 的 Côte-Rôtie。</li>',
         '<li>Compare "clean" Syrah vs Brett-affected Côte-Rôtie.</li>'),
        ('<li>使用 4-EP 標準品，添加 200、500、1000 μg/L。</li>',
         '<li>Use 4-EP standard, adding 200, 500, 1000 μg/L.</li>'),
        ('<li>學習區分「正面煙燻」(橡木桶) vs「負面 Brett」。</li>',
         '<li>Learn to distinguish "positive smoke" (oak) from "negative Brett".</li>'),
        ('<p class="note">個人閾值差異大，需建立自己的接受度標準。</p>',
         '<p class="note">Individual threshold varies widely; establish your own acceptance standard.</p>'),
        ('<h4>還原味 (Reduction)</h4>', '<h4>Reduction</h4>'),
        ('<p><strong>化學本質</strong>: 硫化氫 (H₂S)、甲硫醇 、二甲基硫等硫醇化合物。</p>',
         '<p><strong>Chemistry</strong>: Hydrogen sulphide (H₂S), methanethiol, dimethyl sulphide and other mercaptans.</p>'),
        ('<li>輕度: 火柴、火藥、燧石 (部分 Chablis 的正面特徵)。</li>',
         '<li>Mild: Match-strike, gunpowder, flint (a positive character in some Chablis).</li>'),
        ('<li>中度: 臭雞蛋、燒焦橡膠、腐爛洋蔥。</li>',
         '<li>Moderate: Rotten egg, burnt rubber, rotting onion.</li>'),
        ('<li>重度: 下水道、糞便、完全無法飲用。</li>',
         '<li>Severe: Sewage, faecal; completely undrinkable.</li>'),
        ('<p><strong>動態變化</strong>:</p>', '<p><strong>Dynamic Behaviour</strong>:</p>'),
        ('<li><strong>揮發性</strong>: 輕度還原味可透過醒酒或搖杯消 散。</li>',
         '<li><strong>Volatile</strong>: Mild reduction can dissipate through decanting or swirling.</li>'),
        ('<li><strong>不可逆</strong>: 重度還原 (硫醇) 醒酒無效，需銅片處理 (專業)。</li>',
         '<li><strong>Irreversible</strong>: Severe reduction (mercaptans) cannot be fixed by decanting; requires copper treatment (professional).</li>'),
        ('<p><strong>盲品應對</strong>:</p>', '<p><strong>Blind Tasting Response</strong>:</p>'),
        ('<li>初聞有還原味 → 搖杯 30 秒 → 重新聞。</li>',
         '<li>Initial reductive note → swirl 30 seconds → re-nose.</li>'),
        ('<li>若消失: 記錄為「輕度還原 ( 可醒酒)」，不視為嚴重缺陷。</li>',
         '<li>If gone: note as "mild reduction (decanatable)", not a serious fault.</li>'),
        ('<li>若持續: 記錄為「中/重度 還原」，扣品質分。</li>',
         '<li>If persistent: note as "moderate/severe reduction"; deduct quality points.</li>'),
        ('<p class="note">訓練: 硫化氫溶液 (化學實驗室級)，濃度梯度 1~100 μg/L。</p>',
         '<p class="note">Training: hydrogen sulphide solution (laboratory grade), concentration gradient 1–100 μg/L.</p>'),
        ('<h4>氧化 (Oxidation)</h4>', '<h4>Oxidation</h4>'),
        ('<p><strong>化學本質</strong>: 乙醛 累積、酚類氧化、顏色轉棕。</p>',
         '<p><strong>Chemistry</strong>: Acetaldehyde accumulation, phenolic oxidation, colour browning.</p>'),
        ('<li><strong>白酒</strong>: 蘋果醋、焦糖、蜂蜜、失去新鮮度，顏色轉金黃/棕色。</li>',
         '<li><strong>White wine</strong>: Apple cider vinegar, caramel, honey, loss of freshness; colour turns golden/brown.</li>'),
        ('<li><strong>紅酒</strong>: 煮水果、無花果乾、皮革，單寧軟化，顏色轉磚紅/棕色。</li>',
         '<li><strong>Red wine</strong>: Stewed fruit, dried figs, leather; tannins soften; colour turns brick/brown.</li>'),
        ('<p><strong>正常 vs 缺陷</strong>:</p>', '<p><strong>Normal vs Fault</strong>:</p>'),
        ('<td>正常氧化陳年</td><td>Sherry, Tawny Port, Vin Jaune (刻意氧化風格)</td>',
         '<td>Normal oxidative ageing</td><td>Sherry, Tawny Port, Vin Jaune (intentionally oxidative style)</td>'),
        ('<td>微氧化</td><td>紅酒陳年產生複雜度 (控制氧化)</td>',
         '<td>Micro-oxygenation</td><td>Develops complexity in red wine ageing (controlled oxidation)</td>'),
        ('<td>過度氧化</td><td>封瓶不良、軟木塞乾裂、儲存不當導致失去果味</td>',
         '<td>Excessive oxidation</td><td>Poor sealing, dried cork, improper storage leads to loss of fruit</td>'),
        ('<li>若酒款應為新鮮風格 (如 Sauvignon Blanc) 卻呈現氧化特徵 → 缺陷。</li>',
         '<li>If the wine should be fresh (e.g. Sauvignon Blanc) but shows oxidation → fault.</li>'),
        ('<li>若酒款本應陳年 (如 Gran Reserva Rioja) 呈現適度氧化 → 正常。</li>',
         '<li>If the wine is meant for ageing (e.g. Gran Reserva Rioja) and shows moderate oxidation → normal.</li>'),
        ('<p class="note">訓練: 對比新鮮 vs 刻意暴露於空氣 48 小時的同款酒。</p>',
         '<p class="note">Training: Compare fresh wine vs the same wine deliberately exposed to air for 48 hours.</p>'),
        ('<h3>缺陷量化與閾值測試</h3>', '<h3>Fault Quantification and Threshold Testing</h3>'),
        ('<li><strong>閾值測試</strong>: 使用遞增濃度系列 (如 2, 5, 10, 20 ng/L TCA)，確定個人偵測閾值。</li>',
         '<li><strong>Threshold Testing</strong>: Use ascending concentration series (e.g. 2, 5, 10, 20 ng/L TCA) to determine personal detection threshold.</li>'),
        ('<li><strong>識別閾值</strong>: 能感受到「某種異味」的最低濃度。</li>',
         '<li><strong>Detection Threshold</strong>: The lowest concentration at which "some off-note" is perceived.</li>'),
        ('<li><strong>認知閾值</strong>: 能準確命名該缺陷的濃度 (通常高於識別閾值 2~3 倍)。</li>',
         '<li><strong>Recognition Threshold</strong>: The concentration at which the fault can be accurately named (typically 2–3× the detection threshold).</li>'),
        ('<li><strong>個體差異</strong>: TCA 閾值可相差 10 倍，需定期校準。</li>',
         '<li><strong>Individual Variation</strong>: TCA thresholds can differ 10-fold; calibrate regularly.</li>'),
        ('<h3>缺陷矯正策略</h3>', '<h3>Fault Correction Strategies</h3>'),
        ('<th>缺陷</th><th>預防</th><th>早期介入</th><th>成品矯正</th>',
         '<th>Fault</th><th>Prevention</th><th>Early Intervention</th><th>Finished Wine Correction</th>'),
        ('<td>TCA</td><td>避免受污染軟木塞</td><td>換桶、逆滲透</td><td>不可逆 (換瓶塞無效)</td>',
         '<td>TCA</td><td>Avoid contaminated corks</td><td>Racking, reverse osmosis</td><td>Irreversible (replacing stopper is ineffective)</td>'),
        ('<td>VA</td><td>衛生管理、SO₂</td><td>低溫、過濾醋酸菌</td><td>不可逆 (蒸餾去除)</td>',
         '<td>VA</td><td>Hygiene management, SO₂</td><td>Low temperature, filter acetobacter</td><td>Irreversible (remove by distillation)</td>'),
        ('<td>Brett</td><td>桶清潔、SO₂、過濾</td><td>早期過濾</td><td>逆滲透、PVPP 吸附</td>',
         '<td>Brett</td><td>Barrel sanitation, SO₂, filtration</td><td>Early filtration</td><td>Reverse osmosis, PVPP adsorption</td>'),
        ('<td>還原</td><td>適度氧氣、營養補充</td><td>打氣、銅處理</td><td>輕度可醒酒消散</td>',
         '<td>Reduction</td><td>Adequate oxygen, nutrient supplementation</td><td>Aeration, copper treatment</td><td>Mild cases dissipate with decanting</td>'),
        ('<td>氧化</td><td>惰性氣體、低溫</td><td>SO₂ 添加</td><td>不可逆</td>',
         '<td>Oxidation</td><td>Inert gas, low temperature</td><td>Add SO₂</td><td>Irreversible</td>'),

        # slides.8.content — Typicity Matrix
        ('<h3>典型性評估框架</h3>', '<h3>Typicity Assessment Framework</h3>'),
        ('<p><strong>典型性 (Typicity)</strong>: 酒款 符合其品種/產區/風格預期特徵的程度。</p>',
         '<p><strong>Typicity</strong>: The degree to which a wine meets the expected characteristics of its variety, region, or style.</p>'),
        ('<th>評估層次</th><th>問題</th><th>證據來源</th>',
         '<th>Assessment Level</th><th>Question</th><th>Evidence Sources</th>'),
        ('<td>品種典型性</td><td>此酒是否展現該品種核心特徵?</td><td>香氣譜、酸度、單 寧結構</td>',
         '<td>Varietal Typicity</td><td>Does this wine show the core characteristics of the variety?</td><td>Aroma profile, acidity, tannin structure</td>'),
        ('<td>產區典型性</td><td>此酒是否展現該產區 terroir?</td><td>礦物感、氣候訊號、土壤特徵</td>',
         '<td>Regional Typicity</td><td>Does this wine express the terroir of the appellation?</td><td>Minerality, climate signals, soil characteristics</td>'),
        ('<td>風格 典型性</td><td>此酒是否符合該風格預期?</td><td>釀造技術痕跡 (MLF、橡木、陳年)</td>',
         '<td>Stylistic Typicity</td><td>Does this wine meet the expected style?</td><td>Winemaking markers (MLF, oak, ageing)</td>'),
        ('<h3>品種典型性矩陣 ：紅葡萄</h3>', '<h3>Varietal Typicity Matrix: Red Grapes</h3>'),
        ('<label for="var-cabernet">Cabernet Sauv.</label>', '<label for="var-cabernet">Cabernet Sauv.</label>'),
        ('<label for="var-pinot">Pinot Noir</label>', '<label for="var-pinot">Pinot Noir</label>'),
        ('<label for="var-syrah">Syrah</label>', '<label for="var-syrah">Syrah</label>'),
        ('<h4>Cabernet Sauvignon 典型性指標</h4>', '<h4>Cabernet Sauvignon Typicity Indicators</h4>'),
        ('<td><strong>核心香氣</strong></td><td>黑醋栗、雪松、青椒 (pyrazine)、薄荷</td>',
         '<td><strong>Core Aromas</strong></td><td>Blackcurrant, cedar, green pepper (pyrazine), mint</td>'),
        ('<td><strong>結構</strong></td><td>高單寧 (粗獷 → 絲滑，視產區)、高 酸度、飽滿酒體</td>',
         '<td><strong>Structure</strong></td><td>High tannins (grippy → silky, by region), high acidity, full body</td>'),
        ('<td><strong>氣候訊號</strong></td><td>涼: 青椒主導 | 溫: 黑果主導 | 熱: 果醬、巧克力</td>',
         '<td><strong>Climate Signals</strong></td><td>Cool: green pepper dominates | Warm: black fruit | Hot: jam, chocolate</td>'),
        ('<td><strong>橡木整合</strong></td><td>高親和力，香草、雪松、煙燻明顯</td>',
         '<td><strong>Oak Integration</strong></td><td>High affinity; vanilla, cedar, smoke prominent</td>'),
        ('<td><strong>陳年潛力</strong></td><td>10~30 年，單寧演化為絲綢</td>',
         '<td><strong>Ageing Potential</strong></td><td>10–30 years; tannins evolve to silk</td>'),
        ('<p><strong>產區變異</strong>:</p>', '<p><strong>Regional Variation</strong>:</p>'),
        ('<li><strong>Pauillac</strong>: 雪松、鉛筆屑、礦物感，單寧架構強。</li>',
         '<li><strong>Pauillac</strong>: Cedar, pencil shavings, minerality; powerful tannin structure.</li>'),
        ('<li><strong>Napa Valley</strong>: 成熟黑果、薄荷、酒精感 高 (14.5%+)。</li>',
         '<li><strong>Napa Valley</strong>: Ripe black fruit, mint, high alcohol (14.5%+).</li>'),
        ('<li><strong>Coonawarra</strong>: 桉樹、薄 荷、Terra Rossa 紅土礦物感。</li>',
         '<li><strong>Coonawarra</strong>: Eucalyptus, mint, Terra Rossa red-earth minerality.</li>'),
        ('<p class="note">盲品關鍵: pyrazine 青椒味是 Cab 標誌，但過度則顯示未成熟。</p>',
         '<p class="note">Blind tasting key: pyrazine (green pepper) is the Cab marker, but excess indicates underripeness.</p>'),
        ('<h4>Pinot Noir 典型性指標</h4>', '<h4>Pinot Noir Typicity Indicators</h4>'),
        ('<td><strong>核心香氣</strong></td><td>紅櫻桃、草莓、蘑菇、濕土、玫瑰</td>',
         '<td><strong>Core Aromas</strong></td><td>Red cherry, strawberry, mushroom, wet earth, rose</td>'),
        ('<td><strong>結構</strong></td><td>低~中單寧 (絲滑)、高酸度、中~中+ 酒體</td>',
         '<td><strong>Structure</strong></td><td>Low–medium tannins (silky), high acidity, medium to medium-plus body</td>'),
        ('<td><strong>氣候訊號</strong></td><td>涼: 紅果、酸度犀利 | 溫: 黑櫻桃、果醬</td>',
         '<td><strong>Climate Signals</strong></td><td>Cool: red fruit, sharp acidity | Warm: black cherry, jam</td>'),
        ('<td><strong>橡木整合</strong></td><td>微妙，避免掩蓋細膩果味，多用舊桶</td>',
         '<td><strong>Oak Integration</strong></td><td>Subtle; avoid masking delicate fruit; mostly old oak</td>'),
        ('<td><strong>陳年演化</strong></td><td>5~15 年，發展森林地表、皮革、醬油</td>',
         '<td><strong>Ageing Evolution</strong></td><td>5–15 years; develops forest floor, leather, soy</td>'),
        ('<li><strong>Burgundy (Côte d\'Or)</strong>: 紅果、礦物、土壤 (濕土、蘑菇) ，高酸。</li>',
         '<li><strong>Burgundy (Côte d\'Or)</strong>: Red fruit, mineral, earth (wet soil, mushroom), high acidity.</li>'),
        ('<li><strong>Central Otago</strong>: 深色、黑櫻 桃、香料、較高酒精。</li>',
         '<li><strong>Central Otago</strong>: Deep colour, black cherry, spice, higher alcohol.</li>'),
        ('<li><strong>Oregon (Willamette)</strong>: 介於兩者，紅果 + 泥土，中等酒體。</li>',
         '<li><strong>Oregon (Willamette)</strong>: Between the two; red fruit + earth, medium body.</li>'),
        ('<p class="note">盲品關鍵: 絲滑單寧 + 高酸 + 紅果 = 高置信度 Pinot Noir。</p>',
         '<p class="note">Blind tasting key: silky tannins + high acidity + red fruit = high-confidence Pinot Noir.</p>'),
        ('<h4>Syrah / Shiraz 典型性指標</h4>', '<h4>Syrah / Shiraz Typicity Indicators</h4>'),
        ('<td><strong>核心香氣</strong></td><td>黑莓、黑胡椒、煙燻、橄欖、動物性</td>',
         '<td><strong>Core Aromas</strong></td><td>Blackberry, black pepper, smoke, olive, animal</td>'),
        ('<td><strong>結構</strong></td><td>中+ ~ 高單寧、 中酸度、飽滿酒體</td>',
         '<td><strong>Structure</strong></td><td>Medium-plus to high tannins, medium acidity, full body</td>'),
        ('<td><strong>氣候訊號</strong></td><td>涼: 胡椒、橄欖、煙燻 | 熱: 果醬、巧克力、甜香料</td>',
         '<td><strong>Climate Signals</strong></td><td>Cool: pepper, olive, smoke | Hot: jam, chocolate, sweet spice</td>'),
        ('<td><strong>橡木整合</strong></td><td>良好，煙燻、香草、摩卡</td>',
         '<td><strong>Oak Integration</strong></td><td>Good; smoke, vanilla, mocha</td>'),
        ('<td><strong>陳年潛力</strong></td><td>10~25 年，發 展皮革、焦油、醬油</td>',
         '<td><strong>Ageing Potential</strong></td><td>10–25 years; develops leather, tar, soy</td>'),
        ('<p><strong>Syrah vs Shiraz 風格</strong>:</p>', '<p><strong>Syrah vs Shiraz Style</strong>:</p>'),
        ('<th>特徵</th><th>Syrah (涼爽)</th><th>Shiraz (溫暖)</th>',
         '<th>Characteristic</th><th>Syrah (Cool)</th><th>Shiraz (Warm)</th>'),
        ('<td>產區代表</td><td>北 Rhône, 南非</td><td>Barossa, McLaren Vale</td>',
         '<td>Key Regions</td><td>N. Rhône, South Africa</td><td>Barossa, McLaren Vale</td>'),
        ('<td>香氣</td><td>黑胡椒、橄欖、煙燻</td><td>黑莓果醬、巧克力、桉 樹</td>',
         '<td>Aromas</td><td>Black pepper, olive, smoke</td><td>Blackberry jam, chocolate, eucalyptus</td>'),
        ('<td>酸度</td><td>中+ ~ 高</td><td>中 ~ 中+</td>',
         '<td>Acidity</td><td>Med+ to high</td><td>Med to med+</td>'),
        ('<td>酒精</td><td>12.5~13.5%</td><td>14~15.5%</td>',
         '<td>Alcohol</td><td>12.5–13.5%</td><td>14–15.5%</td>'),
        ('<p class="note">盲品關鍵: 黑胡椒 + 煙燻 = Syrah 標誌，但 Brett 也可能產生類 似煙燻。</p>',
         '<p class="note">Blind tasting key: black pepper + smoke = Syrah marker, but Brett can also produce similar smokiness.</p>'),
        ('<h3>產區典型性矩陣：白葡萄</h3>', '<h3>Regional Typicity Matrix: White Grapes</h3>'),
        ('<th>產區</th><th>品種</th><th>核心特徵</th><th>關鍵區分點</th>',
         '<th>Region</th><th>Variety</th><th>Core Characteristics</th><th>Key Differentiators</th>'),
        ('<td>Chablis</td><td>Chardonnay</td><td>高酸、礦物 (蠔殼、燧石)、無/微橡木</td><td>極淨、鋼鐵般酸度</td>',
         '<td>Chablis</td><td>Chardonnay</td><td>High acidity, mineral (oyster shell, flint), no/minimal oak</td><td>Very clean, steely acidity</td>'),
        ('<td>Meursault</td><td>Chardonnay</td><td>榛果、奶油、烤麵包、豐腴酒體</td><td>MLF + 橡木、更豐滿</td>',
         '<td>Meursault</td><td>Chardonnay</td><td>Hazelnut, butter, toast, rich body</td><td>MLF + oak, fuller</td>'),
        ('<td>Marlborough</td><td>Sauv. Blanc</td><td>百香果、醋栗、青椒、高酸</td><td>強烈果味、純淨</td>',
         '<td>Marlborough</td><td>Sauv. Blanc</td><td>Passionfruit, gooseberry, green pepper, high acidity</td><td>Intense fruit, clean</td>'),
        ('<td>Sancerre</td><td>Sauv. Blanc</td><td>柑橘、燧石、濕石頭、草本</td><td>礦物感主導、更內斂</td>',
         '<td>Sancerre</td><td>Sauv. Blanc</td><td>Citrus, flint, wet stone, herbal</td><td>Mineral-driven, more restrained</td>'),
        ('<td>Mosel</td><td>Riesling</td><td>青蘋果、蜂蜜、板岩、高酸、低酒精</td><td>殘糖平衡、汽油 (陳年)</td>',
         '<td>Mosel</td><td>Riesling</td><td>Green apple, honey, slate, high acidity, low alcohol</td><td>Residual sugar balance, petrol (aged)</td>'),
        ('<td>Alsace</td><td>Riesling</td><td>柑橘、花香、更干、更高酒精</td><td>較飽滿、礦物感不同</td>',
         '<td>Alsace</td><td>Riesling</td><td>Citrus, floral, drier, higher alcohol</td><td>Fuller, different minerality</td>'),
        ('<h3>盲品推論決策 樹</h3>', '<h3>Blind Tasting Inference Decision Tree</h3>'),
        ('<li><strong>Step 1: 顏色與結構</strong>', '<li><strong>Step 1: Colour and Structure</strong>'),
        ('<li>白 / 粉紅 / 紅? → 鎖定品種範圍。</li>',
         '<li>White / rosé / red? → Narrow the variety range.</li>'),
        ('<li>酒體輕重? 單寧高低? → 進一步縮小。</li>',
         '<li>Body light or full? Tannins high or low? → Narrow further.</li>'),
        ('<li><strong>Step 2: 香氣家族</strong>', '<li><strong>Step 2: Aroma Family</strong>'),
        ('<li>果味 (紅果 vs 黑果 vs 熱帶 vs 柑橘)?</li>',
         '<li>Fruit character (red fruit vs black fruit vs tropical vs citrus)?</li>'),
        ('<li>草本 / 香料 / 礦物 / 橡木?</li>',
         '<li>Herbal / spice / mineral / oak?</li>'),
        ('<li><strong>Step 3: 氣候訊號</strong>', '<li><strong>Step 3: Climate Signals</strong>'),
        ('<li>高酸 + 未成熟果 → 涼爽。</li>',
         '<li>High acidity + underripe fruit → cool climate.</li>'),
        ('<li>低酸 + 果醬 + 高酒精 → 溫暖。</li>',
         '<li>Low acidity + jam + high alcohol → warm climate.</li>'),
        ('<li><strong>Step 4: 釀造技術</strong>', '<li><strong>Step 4: Winemaking Technique</strong>'),
        ('<li>MLF?  橡木? 酒泥接觸? 全串發酵?</li>',
         '<li>MLF? Oak? Lees contact? Whole-cluster fermentation?</li>'),
        ('<li>氣候 + 釀造 → 鎖定產區。</li>',
         '<li>Climate + winemaking → identify the appellation.</li>'),
        ('<li><strong>Step 5: 置信 度評估</strong>', '<li><strong>Step 5: Confidence Assessment</strong>'),
        ('<li>3+ 個強證據 → 高置信度 。</li>',
         '<li>3+ strong pieces of evidence → high confidence.</li>'),
        ('<li>1~2 個證據 → 給出 2~3 個可能產區。</li>',
         '<li>1–2 pieces of evidence → give 2–3 possible appellations.</li>'),
        ('<h3>常見盲品陷阱</h3>', '<h3>Common Blind Tasting Traps</h3>'),
        ('<th>陷阱</th><th>錯誤推論</th><th>正確應對</th>',
         '<th>Trap</th><th>Faulty Reasoning</th><th>Correct Response</th>'),
        ('<td>過度依賴單一線索</td><td>聞到青椒 → 一定是 Cab Sauv</td><td>檢查結構、酸度、產區邏輯</td>',
         '<td>Over-relying on one clue</td><td>Smells green pepper → must be Cab Sauv</td><td>Check structure, acidity, and regional logic</td>'),
        ('<td>忽略氣候訊號</td><td>Pinot 只來自 Burgundy</td><td>考慮 NZ、Oregon、California</td>',
         '<td>Ignoring climate signals</td><td>Pinot only comes from Burgundy</td><td>Consider NZ, Oregon, California</td>'),
        ('<td>混淆釀造與品種</td><td>奶油味 → Chardonnay</td><td>MLF 可用於多品種</td>',
         '<td>Confusing winemaking with variety</td><td>Buttery → Chardonnay</td><td>MLF can be used for many varieties</td>'),
        ('<td>年份效應</td><td>2003 Bordeaux 像 Napa</td><td>極端年份打破常規</td>',
         '<td>Vintage effect</td><td>2003 Bordeaux resembles Napa</td><td>Extreme vintages break conventions</td>'),
        ('<td>生產者風格</td><td>某酒莊刻意模仿他產區</td><td>關注多數典型性，非個案</td>',
         '<td>Producer style</td><td>Some estates deliberately mimic other regions</td><td>Focus on general typicity, not outliers</td>'),

        # slides.10.content — Competition strategy
        ('<h3>時間管理策略</h3>', '<h3>Time Management Strategy</h3>'),
        ('<th>階段</th><th>時間分配</th><th>關鍵任務</th><th>常見錯誤</th>',
         '<th>Round</th><th>Time Allocation</th><th>Key Tasks</th><th>Common Mistakes</th>'),
        ('<td>第一輪 (掃描)</td><td>2 分鐘 / 款</td><td>快速記錄視覺、主導香氣、結構骨架</td><td>過度細節、拖延</td>',
         '<td>Round 1 (Scan)</td><td>2 min / wine</td><td>Quickly note visual, dominant aromas, structural skeleton</td><td>Over-detail, dawdling</td>'),
        ('<td>第二輪 (深入)</td><td>3 分鐘 / 款</td><td>完整香氣分析、味覺細節、初步推論</td><td>糾結單一酒款</td>',
         '<td>Round 2 (Deep)</td><td>3 min / wine</td><td>Full aroma analysis, palate detail, initial inference</td><td>Getting stuck on one wine</td>'),
        ('<td>第三輪 (確認)</td><td>1 分鐘 / 款</td><td>驗證推論、補充遺漏細節</td><td>過度修改</td>',
         '<td>Round 3 (Confirm)</td><td>1 min / wine</td><td>Verify inference, fill in missing details</td><td>Over-revising</td>'),
        ('<td>總結 (10 min)</td><td>整體檢視</td><td>檢查邏輯一致性、填補空白</td><td>緊張放棄</td>',
         '<td>Summary (10 min)</td><td>Overall review</td><td>Check logical consistency, fill gaps</td><td>Panic-quitting</td>'),
        ('<p><strong>範例</strong>: 12 款酒，總時間 90 分鐘 → 第一輪 24 min、第二輪 36 min、第三輪 12 min、總結 10 min、緩 衝 8 min。</p>',
         '<p><strong>Example</strong>: 12 wines, 90 min total → Round 1: 24 min, Round 2: 36 min, Round 3: 12 min, Summary: 10 min, Buffer: 8 min.</p>'),
        ('<h3>筆記系統優化</h3>', '<h3>Note-Taking System Optimisation</h3>'),
        ('<label for="note-grid">網格法</label>', '<label for="note-grid">Grid Method</label>'),
        ('<label for="note-shorthand">速記符號</label>', '<label for="note-shorthand">Shorthand</label>'),
        ('<label for="note-mental">心智地圖</label>', '<label for="note-mental">Mental Map</label>'),
        ('<h4>網格法 (Grid Method)</h4>', '<h4>Grid Method</h4>'),
        ('<p><strong> 優點</strong>: 結構化、易於對比、不遺漏項目。</p>',
         '<p><strong>Advantages</strong>: Structured, easy to compare, nothing missed.</p>'),
        ('<p><strong>設計</strong>:</p>', '<p><strong>Design</strong>:</p>'),
        ('<th>項目</th><th>酒 1</th><th>酒 2</th><th>酒 3</th>',
         '<th>Item</th><th>Wine 1</th><th>Wine 2</th><th>Wine 3</th>'),
        ('<td>外觀</td><td>深寶石紅</td><td>淡石榴紅</td><td>金黃</td>',
         '<td>Appearance</td><td>Deep ruby</td><td>Pale garnet</td><td>Golden</td>'),
        ('<td>香氣強度</td><td>中+</td><td>中</td><td>濃</td>',
         '<td>Aroma Intensity</td><td>Med+</td><td>Med</td><td>Pronounced</td>'),
        ('<td>主導香氣</td><td>黑醋栗、雪松</td><td>紅櫻桃、土壤</td><td>柑橘、蜂蜜</td>',
         '<td>Dominant Aromas</td><td>Blackcurrant, cedar</td><td>Red cherry, earth</td><td>Citrus, honey</td>'),
        ('<td>酸度</td><td>中+</td><td>高</td><td>高</td>',
         '<td>Acidity</td><td>Med+</td><td>High</td><td>High</td>'),
        ('<td>單寧</td><td>高</td><td>中</td><td>N/A</td>',
         '<td>Tannins</td><td>High</td><td>Med</td><td>N/A</td>'),
        ('<td>酒體</td><td>飽滿</td><td>中</td><td>中+</td>',
         '<td>Body</td><td>Full</td><td>Med</td><td>Med+</td>'),
        ('<td>初步推論</td><td>Cab Pauillac</td><td>PN Burg</td><td>Ries Mosel</td>',
         '<td>Initial Inference</td><td>Cab Pauillac</td><td>PN Burg</td><td>Ries Mosel</td>'),
        ('<p class="note">適合需要完整 記錄的正式考試 (如 Diploma)。</p>',
         '<p class="note">Best for formal exams requiring complete records (e.g. WSET Diploma).</p>'),
        ('<h4>速記符號系統</h4>', '<h4>Shorthand Notation System</h4>'),
        ('<p><strong>優點</strong>: 快速、節省空間、適合競賽。</p>',
         '<p><strong>Advantages</strong>: Fast, space-saving, ideal for competitions.</p>'),
        ('<p><strong>常用符號</strong>:</p>', '<p><strong>Common Symbols</strong>:</p>'),
        ('<li><strong>顏色</strong>: R (紅)、W (白)、Ro (粉紅)、深 (+)、淡 (-)。</li>',
         '<li><strong>Colour</strong>: R (red), W (white), Ro (rosé), deep (+), pale (-).</li>'),
        ('<li><strong>香氣</strong>: B (黑果)、R (紅果)、Cit (柑橘)、Trop (熱帶)、Oak (橡木)。</li>',
         '<li><strong>Aroma</strong>: B (black fruit), R (red fruit), Cit (citrus), Trop (tropical), Oak (oak).</li>'),
        ('<li><strong>結構</strong>: A (酸度)、T (單寧)、Alc (酒精)、↑ (高)、↓ (低)。</li>',
         '<li><strong>Structure</strong>: A (acidity), T (tannins), Alc (alcohol), ↑ (high), ↓ (low).</li>'),
        ('<li><strong>品質</strong>: * (良好)、** (優秀)、*** (傑出)。</li>',
         '<li><strong>Quality</strong>: * (good), ** (very good), *** (outstanding).</li>'),
        ('<p><strong>範例筆記</strong>:</p>', '<p><strong>Example Notes</strong>:</p>'),
        ('<p class="note">需事前訓練建立個人符號系統，考試前復習。</p>',
         '<p class="note">Requires pre-training to build a personal symbol system; revise before the exam.</p>'),
        ('<h4>心智地圖 (Mental Map)</h4>', '<h4>Mental Map</h4>'),
        ('<p><strong>優點</strong>: 關聯記憶、快速提取、適合經驗豐富者。</p>',
         '<p><strong>Advantages</strong>: Associative memory, rapid recall, ideal for experienced tasters.</p>'),
        ('<p><strong>方法</strong>:</p>', '<p><strong>Method</strong>:</p>'),
        ('<li>品評時在腦中建立「參考酒款」對應。</li>',
         '<li>While tasting, build a mental "reference wine" match.</li>'),
        ('<li>例如: 此酒 = 70% Pauillac 典型 + 30% 年份熱。</li>',
         '<li>Example: this wine = 70% typical Pauillac + 30% vintage heat.</li>'),
        ('<li>僅記錄關鍵區分點 (如「比標準 Pauillac 更成熟」)。</li>',
         '<li>Only record key differentiating points (e.g. "riper than standard Pauillac").</li>'),
        ('<li>最後統整時重構完整描述。</li>',
         '<li>Reconstruct the full description during the final summary.</li>'),
        ('<p><strong>風險</strong>: 記憶負荷高，若中斷易混淆。</p>',
         '<p><strong>Risk</strong>: High memory load; easy to confuse if interrupted.</p>'),
        ('<p class="note">需大量練習建立穩定「參考酒款庫」(100+ 款)。</p>',
         '<p class="note">Requires extensive practice to build a stable "reference wine library" (100+ wines).</p>'),
        ('<h3>對比品評技巧</h3>', '<h3>Comparative Tasting Techniques</h3>'),
        ('<li><strong>成對對比</strong>: 將同品種不同產區 酒款並排品評 (如 Burgundy PN vs Oregon PN)。</li>',
         '<li><strong>Paired Comparison</strong>: Taste same-variety wines from different regions side by side (e.g. Burgundy PN vs Oregon PN).</li>'),
        ('<li><strong>垂直 品評</strong>: 同酒款不同年份，學習年份效應與陳年演化。</li>',
         '<li><strong>Vertical Tasting</strong>: Same wine, different vintages; learn vintage effects and ageing evolution.</li>'),
        ('<li><strong>水平品評</strong>: 同產區同年份不同酒莊，學習風土微差異。</li>',
         '<li><strong>Horizontal Tasting</strong>: Same region and vintage, different producers; learn subtle terroir differences.</li>'),
        ('<li><strong>三角對比</strong>: A (標準) vs B (變異 1) vs C (變異 2)，強化區分 能力。</li>',
         '<li><strong>Triangle Comparison</strong>: A (standard) vs B (variation 1) vs C (variation 2); sharpen discrimination.</li>'),
        ('<h3>競賽常見題型策略</h3>', '<h3>Common Competition Question Types</h3>'),
        ('<th>題型</th><th>挑戰</th><th>策略</th><th>範例</th>',
         '<th>Question Type</th><th>Challenge</th><th>Strategy</th><th>Example</th>'),
        ('<td>經典產區</td><td>需精準識別 AOC</td><td>熟記典型性矩陣、村莊風格</td><td>Pauillac vs St-Julien</td>',
         '<td>Classic appellations</td><td>Must precisely identify AOC</td><td>Memorise typicity matrix and village styles</td><td>Pauillac vs St-Julien</td>'),
        ('<td>新世界模仿</td><td>風格相似度高</td><td>關注氣候訊號、酒精度</td><td>Napa Cab vs Pauillac</td>',
         '<td>New World mimics</td><td>High stylistic similarity</td><td>Focus on climate signals and alcohol level</td><td>Napa Cab vs Pauillac</td>'),
        ('<td>陷阱年份</td><td>極端年份打破常規</td><td>記錄重要年份特徵 (2003, 2011)</td><td>2003 Bordeaux (熱)</td>',
         '<td>Trap vintages</td><td>Extreme vintages break conventions</td><td>Memorise key vintage characteristics (2003, 2011)</td><td>2003 Bordeaux (hot)</td>'),
        ('<td>少見品種</td><td>香氣庫不足</td><td>排除法、結構推論</td><td>Négrette, Timorasso</td>',
         '<td>Obscure varieties</td><td>Insufficient aroma library</td><td>Elimination method, structural inference</td><td>Négrette, Timorasso</td>'),
        ('<td>加烈/甜酒</td><td>釀造多樣性</td><td>辨識氧化 vs 非氧化、加烈方式</td><td>PX vs Amontillado</td>',
         '<td>Fortified/sweet wines</td><td>Winemaking diversity</td><td>Identify oxidative vs non-oxidative, fortification method</td><td>PX vs Amontillado</td>'),
        ('<h3>心理壓力管理</h3>', '<h3>Psychological Pressure Management</h3>'),
        ('<li><strong>預期管理</strong>: 接受無法 100% 正確，目標 70~80% 準確率。</li>',
         '<li><strong>Expectation Management</strong>: Accept that 100% accuracy is impossible; aim for 70–80%.</li>'),
        ('<li><strong>錨定避免</strong>: 第一印象錯誤時，勇於推翻重新評估。</li>',
         '<li><strong>Avoid Anchoring</strong>: If the first impression is wrong, be bold enough to overturn and reassess.</li>'),
        ('<li><strong>時間焦慮</strong>: 設定中間檢查點 (如 30 分鐘完成 5 款)，避免最後趕工。</li>',
         '<li><strong>Time Anxiety</strong>: Set midpoint checkpoints (e.g. 5 wines in 30 min); avoid last-minute rushes.</li>'),
        ('<li><strong>呼吸調節</strong>: 感官疲勞時深呼吸 3 次，重置嗅覺。</li>',
         '<li><strong>Breathing</strong>: When sensory fatigue sets in, take 3 deep breaths to reset olfaction.</li>'),
        ('<h3>盲品訓練 計畫 (12 週)</h3>', '<h3>Blind Tasting Training Plan (12 Weeks)</h3>'),
        ('<th>週次</th><th>主題</th><th>訓練內容</th><th>酒款數</th>',
         '<th>Week</th><th>Theme</th><th>Training Content</th><th>No. of Wines</th>'),
        ('<tr><td>1~2</td><td>品種識別</td><td>單一品種，涵蓋 6 大紅、6 大白</td><td>12 款 × 2 週</td></tr>',
         '<tr><td>1–2</td><td>Variety Identification</td><td>Single varieties, covering 6 major reds and 6 major whites</td><td>12 wines × 2 wks</td></tr>'),
        ('<tr><td>3~4</td><td>氣候影響</td><td>同品種不同氣候區 (涼/ 溫/熱)</td><td>9 款 × 2 週</td></tr>',
         '<tr><td>3–4</td><td>Climate Influence</td><td>Same variety, different climate zones (cool/warm/hot)</td><td>9 wines × 2 wks</td></tr>'),
        ('<tr><td>5~6</td><td>產區典型性</td><td>經典產區對比 (法國 vs 新世界)</td><td>12 款 × 2 週</td></tr>',
         '<tr><td>5–6</td><td>Regional Typicity</td><td>Classic appellation comparisons (France vs New World)</td><td>12 wines × 2 wks</td></tr>'),
        ('<tr><td>7~8</td><td>釀造技術</td><td>橡木/MLF/酒泥/全串對比</td><td>8 款 × 2 週</td></tr>',
         '<tr><td>7–8</td><td>Winemaking Technique</td><td>Oak/MLF/lees/whole-cluster comparisons</td><td>8 wines × 2 wks</td></tr>'),
        ('<tr><td>9~10</td><td>陳年演化</td><td>垂直品評 (5~15 年)</td><td>6 款 × 2 週</td></tr>',
         '<tr><td>9–10</td><td>Ageing Evolution</td><td>Vertical tasting (5–15 years)</td><td>6 wines × 2 wks</td></tr>'),
        ('<tr><td>11~12</td><td>模擬競賽</td><td>混合題型、計時壓力</td><td>15 款 × 2 週</td></tr>',
         '<tr><td>11–12</td><td>Mock Competition</td><td>Mixed question types, timed pressure</td><td>15 wines × 2 wks</td></tr>'),
        ('<h3>後設認知檢核表</h3>', '<h3>Metacognitive Checklist</h3>'),
        ('<p>每次盲品後自我提問:</p>', '<p>Self-questioning after each blind tasting:</p>'),
        ('<li>哪些線索是強證據? 哪些是弱證 據?</li>',
         '<li>Which clues are strong evidence? Which are weak?</li>'),
        ('<li>我的推論邏輯鏈是否完整? (顏色 → 香氣 → 結構 → 產區)</li>',
         '<li>Is my inference logic chain complete? (Colour → Aroma → Structure → Appellation)</li>'),
        ('<li>我是否受到某種偏誤影響? (確認偏誤、錨定效應)</li>',
         '<li>Was I affected by any bias? (confirmation bias, anchoring effect)</li>'),
        ('<li>若錯誤，錯在哪個環節? (感知錯誤 vs 知識缺乏 vs 推論錯誤)</li>',
         '<li>If wrong, at which step did I go wrong? (perception error vs knowledge gap vs reasoning error)</li>'),
        ('<li>如何改進? (補充知識 vs 訓練感官 vs 優化流程)</li>',
         '<li>How to improve? (add knowledge vs train senses vs optimise process)</li>'),
    ]

    # Apply HTML translations to content blocks
    content_keys = ['slides.2.content', 'slides.4.content', 'slides.6.content',
                    'slides.8.content', 'slides.10.content']
    for key in content_keys:
        if key in data:
            val = data[key]
            for old, new in html_replacements:
                val = val.replace(old, new)
            data[key] = val

    with open(path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f'[OK] l4-9.json translated')


if __name__ == '__main__':
    translate_l4_9()
