import json

path = r"c:\Users\Chungshu\Desktop\教學網站製作20260220\Bordeaux Wine Learning\src\locales\en\lessons\bordeaux\l3-13-part1.json"

with open(path, encoding="utf-8") as f:
    data = json.load(f)

def tr(val, pairs):
    val = val.replace("[ZH] ", "").replace("[ZH]", "")
    for zh, en in pairs:
        val = val.replace(zh, en)
    return val

# ── slides.16.content ─────────────────────────────────────────────────────────
r16 = [
    ("AI發酵管理系統（一）｜智能溫度控制",
     "AI Fermentation Management System (I) | Intelligent Temperature Control"),
    ("差1°C決定優雅還是粗糙 × AI精準到 ±0.2°C × 32個罐同步協調",
     "1°C difference determines elegance or roughness × AI precision to ±0.2°C × 32 tanks coordinated simultaneously"),
    ("🎯 自適應溫控策略", "🎯 Adaptive Temperature Control Strategy"),
    ("🧬 品種專屬曲線", "🧬 Variety-Specific Curves"),
    (">品種<", ">Variety<"),
    (">溫度範圍<", ">Temperature Range<"),
    (">目標<", ">Objective<"),
    ("萃取單寧", "Extract tannins"),
    ("保留果香", "Preserve fruit aromas"),
    ("突顯草本", "Highlight herbaceous notes"),
    ("萃取色素", "Extract pigments"),
    ("<span style=\"color:#553c9a;font-weight:700\">💡 Pichon-Longueville Merlot 2024：</span>",
     "<span style=\"color:#553c9a;font-weight:700\">💡 Pichon-Longueville Merlot 2024:</span>"),
    ("傳統固定曲線 → 中期發酵過快，香氣損失",
     "Traditional fixed curve → mid-fermentation overheated, aroma loss"),
    ("AI自適應：每階段動態調整 ±0.5°C",
     "AI adaptive: dynamic ±0.5°C adjustment at each stage"),
    ("<span style=\"color:#c53030;font-weight:700\">→ 香氣保留 78% ➜ 91% × 評分87→90分 × 節能28%</span>",
     "<span style=\"color:#c53030;font-weight:700\">→ Aroma retention 78% ➜ 91% × score 87→90 pts × energy saving 28%</span>"),
    ("🔮 預測控制機制", "🔮 Predictive Control Mechanism"),
    ("提前2–4小時預測發酵進程",
     "Predicts fermentation progress 2–4 hours ahead"),
    ("智能學習 × 自動調整溫度曲線",
     "Intelligent learning × automatically adjusts temperature curves"),
    ("根據酵母活性即時響應", "Real-time response based on yeast activity"),
    ("在保證品質前提下節能20–35%",
     "Energy saving 20–35% while guaranteeing quality"),
    ("🏭 多罐協調與預防維護",
     "🏭 Multi-tank Coordination and Predictive Maintenance"),
    ("⚡ 32罐極限協調（Saint-Julien 2024）",
     "⚡ 32-tank Ultimate Coordination (Saint-Julien 2024)"),
    (">P1正牌(8罐)<", ">P1 Grand Vin (8 tanks)<"),
    ("目標溫度 ±0.2°C 保證", "Target temp ±0.2°C guaranteed"),
    (">P2副牌(15罐)<", ">P2 Second Wine (15 tanks)<"),
    ("目標溫度 ±0.5°C 保證", "Target temp ±0.5°C guaranteed"),
    (">P3入門(9罐)<", ">P3 Entry Level (9 tanks)<"),
    ("目標溫度 ±1.0°C 保證", "Target temp ±1.0°C guaranteed"),
    ("冷卻機故障（損失40kW）→ AI 5秒重新分配",
     "Chiller failure (40 kW lost) → AI redistributes in 5 s"),
    ("P1維持不變 × 40分鐘後機組修復",
     "P1 unchanged × unit repaired after 40 minutes"),
    ("<span style=\"color:#c53030;font-weight:700\">→ 32罐全部成功 × 能耗−32% × 利用率65→89%</span>",
     "<span style=\"color:#c53030;font-weight:700\">→ All 32 tanks successful × energy −32% × utilisation 65→89%</span>"),
    ("🔧 預測性維護（Pauillac 2024）",
     "🔧 Predictive Maintenance (Pauillac 2024)"),
    ("8/15 震動異常 → 8/18 能耗+8% → 8/20 AI警報",
     "8/15 vibration anomaly → 8/18 energy +8% → 8/20 AI alert"),
    ("預計5–7天內故障，可靠度 92%",
     "Failure predicted within 5–7 days, reliability 92%"),
    ("技師確認後智能排程：8/24晚維修（僅3罐需冷卻）",
     "After technician confirmation, smart scheduling: maintenance on night of 8/24 (only 3 tanks needing cooling)"),
    ("維修成本：<span style=\"color:#276749;font-weight:700\">€2,800</span> × 若採收高峰故障：<span style=\"color:#c53030\">€120,000</span>",
     "Repair cost: <span style=\"color:#276749;font-weight:700\">€2,800</span> × if failed during harvest peak: <span style=\"color:#c53030\">€120,000</span>"),
    ("<span style=\"color:#c53030;font-weight:700\">→ ROI 43倍 × 預測準確度92%→97% × 1年預防11次故障</span>",
     "<span style=\"color:#c53030;font-weight:700\">→ ROI 43× × prediction accuracy 92%→97% × 11 failures prevented in 1 year</span>"),
    ("<div style=\"opacity:.85\">P1正牌溫控精度</div>",
     "<div style=\"opacity:.85\">P1 Grand Vin temp precision</div>"),
    ("<div style=\"opacity:.85\">32罐協調節能</div>",
     "<div style=\"opacity:.85\">32-tank coordination energy saving</div>"),
    ("<div style=\"opacity:.85\">香氣保留提升</div>",
     "<div style=\"opacity:.85\">Aroma retention improvement</div>"),
    ("<div style=\"opacity:.85\">預測維護回報</div>",
     "<div style=\"opacity:.85\">Predictive maintenance ROI</div>"),
]
data["slides.16.content"] = tr(data["slides.16.content"], r16)

# ── slides.17.content ─────────────────────────────────────────────────────────
r17 = [
    ("AI發酵管理系統（二）｜發酵過程監控",
     "AI Fermentation Management System (II) | Fermentation Process Monitoring"),
    ("每天24次 → 28,800次 × 異常檢測從6小時縮短到5分鐘 × 24/7守護",
     "24 times/day → 28,800 readings × anomaly detection cut from 6 hours to 5 minutes × 24/7 monitoring"),
    ("📊 即時參數追蹤", "📊 Real-Time Parameter Tracking"),
    ("🔬 核心發酵參數（每5分鐘）",
     "🔬 Core Fermentation Parameters (every 5 minutes)"),
    ("密度監測 × 追蹤糖分轉化进程",
     "Density monitoring × tracks sugar conversion progress"),
    ("pH值控制 × 自動調節酸度",
     "pH control × automatic acidity adjustment"),
    ("CO₂產生速率 × 評估酵母活力",
     "CO₂ production rate × evaluates yeast vitality"),
    ("酒精濃度 × 連續預測監控",
     "Alcohol concentration × continuous predictive monitoring"),
    ("<span style=\"color:#276749;font-weight:700\">💡 Château Haut-Brion 2024 Cab.Sauv：</span>",
     "<span style=\"color:#276749;font-weight:700\">💡 Château Haut-Brion 2024 Cab.Sauv:</span>"),
    ("傳統：每天2次手工測 → 夜間異常10小時後才發現",
     "Traditional: 2 manual measurements/day → night-time anomaly detected only after 10 hours"),
    ("損失<span style=\"color:#c53030;font-weight:700\">€18,000</span>（降副牌）",
     "Loss <span style=\"color:#c53030;font-weight:700\">€18,000</span> (downgraded to second wine)"),
    ("AI：凌晨2:15密度加速 → 15分鐘內預警+自動冷卻",
     "AI: density surge at 2:15 AM → alert + automatic cooling within 15 minutes"),
    ("<span style=\"color:#c53030;font-weight:700\">→ 全程3,456數據點 × 評分89→94分</span>",
     "<span style=\"color:#c53030;font-weight:700\">→ 3,456 data points throughout × score 89→94 pts</span>"),
    ("🧪 MLF生化參數監控", "🧪 MLF Biochemical Parameter Monitoring"),
    ("乳酸菌活性 × MLF進程監測",
     "Lactic acid bacteria activity × MLF progress monitoring"),
    ("揮發酸控制 × 追蹤醋酸含量",
     "Volatile acidity control × tracks acetic acid content"),
    ("氧化還原電位 × 微生物活動",
     "Oxidation-reduction potential × microbial activity"),
    ("酚類物質 × 單寧/色素萃取",
     "Phenolic compounds × tannin/pigment extraction"),
    ("<span style=\"color:#276749;font-weight:700\">💡 Saint-Émilion MLF危機（2024/11）：</span>",
     "<span style=\"color:#276749;font-weight:700\">💡 Saint-Émilion MLF crisis (Nov 2024):</span>"),
    ("揮發酸晚9:30突升至0.45 g/L → AI高級警報",
     "VA spiked to 0.45 g/L at 9:30 PM → AI high-level alert"),
    ("預測24小時超標（&gt;0.8上限）→ 立即降溫+SO₂",
     "Predicted to exceed limit (&gt;0.8 threshold) within 24 h → immediate cooling + SO₂"),
    ("<span style=\"color:#c53030;font-weight:700\">→ 穩定在0.48 g/L × 避免損失€64,000 × 評分91分</span>",
     "<span style=\"color:#c53030;font-weight:700\">→ Stabilised at 0.48 g/L × loss avoided €64,000 × score 91 pts</span>"),
    ("🚨 智能異常檢測預警",
     "🚨 Intelligent Anomaly Detection and Warning"),
    ("🛑 發酵停滯預警（Pessac-Léognan 2024）",
     "🛑 Fermentation Arrest Warning (Pessac-Léognan 2024)"),
    ("速率−12% → 黃色警報，觀察24H",
     "Rate −12% → yellow alert, monitor 24 h"),
    ("速率−40%，CO₂驟降 → 停滯風險65%",
     "Rate −40%, CO₂ drop → arrest risk 65%"),
    ("添加營養劑+降溫 → 發酵恢復",
     "Nutrient addition + cooling → fermentation recovered"),
    ("<span style=\"color:#c53030;font-weight:700\">→ 本季16罐預測4次風險，全部成功救回</span>",
     "<span style=\"color:#c53030;font-weight:700\">→ 4 risks predicted across 16 tanks this season, all successfully rescued</span>"),
    ("避免損失 <span style=\"font-weight:700\">€95,000</span> × 提前2.5天預警",
     "Loss avoided <span style=\"font-weight:700\">€95,000</span> × 2.5-day advance warning"),
    ("🦠 Brett污染早期檢測（Pauillac 2024）",
     "🦠 Brett Contamination Early Detection (Pauillac 2024)"),
    ("光譜技術識別微生物污染",
     "Spectroscopic technology identifies microbial contamination"),
    ("代謝產物異常訊號偵測",
     "Metabolite anomaly signal detection"),
    ("污染模式匹配比對", "Contamination pattern matching"),
    ("來源追蹤與傳播路徑", "Source tracing and propagation pathways"),
    ("💡 4-ethylphenol = 120 μg/L（閾值30%）即預警",
     "💡 4-ethylphenol = 120 μg/L (30% of threshold) triggers alert"),
    ("傳統：裝瓶前才發現（已太遲）",
     "Traditional: detected only before bottling (too late)"),
    ("AI：污染初期即精準識別，立即處理",
     "AI: precisely identifies contamination at onset, immediate remediation"),
    ("<span style=\"color:#c53030;font-weight:700\">→ 避免損失 12,000L × €12/L = €144,000</span>",
     "<span style=\"color:#c53030;font-weight:700\">→ Loss avoided 12,000 L × €12/L = €144,000</span>"),
    ("<div style=\"opacity:.85\">數據點/天（傳統24次）</div>",
     "<div style=\"opacity:.85\">data points/day (traditional 24×)</div>"),
    ("<div style=\"opacity:.85\">異常檢測（傳統6小時）</div>",
     "<div style=\"opacity:.85\">anomaly detection (traditional 6 h)</div>"),
    ("<div style=\"opacity:.85\">Brett污染避免損失</div>",
     "<div style=\"opacity:.85\">Brett contamination loss avoided</div>"),
    ("<div style=\"opacity:.85\">發酵事故率</div>",
     "<div style=\"opacity:.85\">Fermentation incident rate</div>"),
]
data["slides.17.content"] = tr(data["slides.17.content"], r17)

with open(path, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Saved l3-13-part1.json (slides.16 + slides.17 updated)")
