import json, pathlib

f = pathlib.Path("src/locales/en/lessons/bordeaux/l4-5.json")
data = json.loads(f.read_text(encoding="utf-8"))

data["slides.0.title"] = "Learning Objectives"
data["slides.1.title"] = "Chapter 1"
data["slides.1.subtitle"] = "Brand Architecture"
data["slides.2.title"] = "Chapter 1: Brand Equity and Architecture Design"
data["slides.2.highlights.0.title"] = "Brand Equity"
data["slides.2.highlights.0.content"] = "Five dimensions: awareness, perceived quality, narrative, loyalty and differentiation."
data["slides.2.highlights.1.title"] = "Architecture Choice"
data["slides.2.highlights.1.content"] = "Monolithic vs sub-brand vs endorsed brand — pros and cons of each."
data["slides.2.highlights.2.title"] = "Value Proposition"
data["slides.2.highlights.2.content"] = "Functional, emotional and social value layers built around storytelling."
data["slides.3.title"] = "Chapter 2"
data["slides.3.subtitle"] = "Positioning Matrix"
data["slides.4.title"] = "Chapter 2: Positioning Matrix and Consumer Insights"
data["slides.4.highlights.0.title"] = "Segmentation Matrix"
data["slides.4.highlights.0.content"] = "Four customer segments mapped to needs, channels and messaging."
data["slides.4.highlights.1.title"] = "Positioning Quadrant"
data["slides.4.highlights.1.content"] = "Price × innovation quadrant checks for internal line cannibalisation."
data["slides.4.highlights.2.title"] = "Content Strategy"
data["slides.4.highlights.2.content"] = "Long-form storytelling, short video and authority endorsement on three axes."
data["slides.5.title"] = "Chapter 3"
data["slides.5.subtitle"] = "Price & Channels"
data["slides.6.title"] = "Chapter 3: Price Ladder and Channel Strategy"
data["slides.6.highlights.0.title"] = "Price Ladder"
data["slides.6.highlights.0.content"] = "EXW/retail price and margin structure from flagship to entry series."
data["slides.6.highlights.1.title"] = "Channel Decision"
data["slides.6.highlights.1.content"] = "Traditional distribution, DTC and hybrid model — pros and cons."
data["slides.6.highlights.2.title"] = "Strategy Dashboard"
data["slides.6.highlights.2.content"] = "Switch scenarios to compare export share, margin and KPIs."
data["slides.7.title"] = "Chapter 4"
data["slides.7.subtitle"] = "Market Insights"
data["slides.8.title"] = "Chapter 4: International Markets and Cultural Compliance"
data["slides.8.highlights.0.title"] = "Market Overview"
data["slides.8.highlights.0.content"] = "Comparing demand and regulations across US, China, Japan and Europe."
data["slides.8.highlights.1.title"] = "Cultural Simulation"
data["slides.8.highlights.1.content"] = "Interactive panel to switch between communication strategies by market."
data["slides.8.highlights.2.title"] = "Compliance Checklist"
data["slides.8.highlights.2.content"] = "Labelling, tax structures and digital marketing rules must be reviewed in advance."
data["slides.9.title"] = "Chapter 5"
data["slides.9.subtitle"] = "Brand Growth"
data["slides.10.title"] = "Chapter 5: Data-Driven Brand Growth"
data["slides.10.highlights.0.title"] = "Growth Flywheel"
data["slides.10.highlights.0.content"] = "Acquire → nurture → convert → amplify: the brand growth loop."
data["slides.10.highlights.1.title"] = "Brand KPIs"
data["slides.10.highlights.1.content"] = "Brand power, engagement rate, LTV/CAC and international revenue share listed in full."
data["slides.10.highlights.2.title"] = "Data Platform"
data["slides.10.highlights.2.content"] = "CDP, BI and AI support brand decisions and sustainability tracking."
data["slides.11.title"] = "Course Summary"
data["slides.12.title"] = "Post-Course Quiz"

f.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
print("Done. Updated 36 short text keys.")
