import json, pathlib

f = pathlib.Path("src/locales/en/lessons/bordeaux/l3-5.json")
data = json.loads(f.read_text(encoding="utf-8"))

updates = {
    "slides.0.title": "Course Introduction",
    "slides.0.content": "Bordeaux winemaking combines centuries of traditional wisdom with modern science. From the moment grapes enter the cellar, every decision shapes the final wine's quality and style. This course explores the complete red and white winemaking process—from destemming and maceration to MLF, fermentation control and maceration management—offering a comprehensive understanding of how winemaking techniques shape colour, tannin, flavour and ageing potential. You will learn how technical directors at top châteaux balance tradition and innovation to preserve terroir character while using modern technology to enhance quality consistency.",
    "slides.1.title": "Red Wine Winemaking",
    "slides.1.subtitle": "The Transformation Journey from Grape to Wine",
    "slides.1.description": "Understanding the Complete Process and Key Technologies of Red Wine Winemaking",
    "slides.2.title": "Red Wine Winemaking Introduction",
    "slides.3.title": "Red Wine Winemaking Process Overview",
    "slides.4.title": "Red Wine Winemaking: Detailed Step Analysis",
    "slides.5.title": "In-Depth Analysis of Maceration Techniques",
    "slides.5.content": "Maceration is the core stage of red winemaking, determining the degree of colour, tannin and flavour extraction. Bordeaux winemakers use multiple techniques to manage this process.\n\n**Key Maceration Techniques:**",
    "slides.6.title": "Maceration Technique Comparison Matrix",
    "slides.7.title": "Case Study: Château Margaux Maceration Management",
    "slides.8.title": "Chapter Two",
    "slides.8.subtitle": "White Wine Winemaking",
    "slides.8.description": "The Art of Bordeaux Dry White and Sweet White Winemaking",
    "slides.9.title": "White Wine Winemaking: Fundamental Differences from Red Wine",
    "slides.10.title": "White Wine Winemaking: Detailed Steps",
    "slides.11.title": "Case Study: Château Smith Haut Lafitte White Wine Winemaking",
    "slides.12.title": "Knowledge Check: Red Wine and White Wine Winemaking",
    "slides.13.title": "Winemaking: The Fusion of Art and Science",
    "slides.14.title": "Traditional Winemaking Philosophy",
    "slides.14.subtitle": "Minimal Intervention and Artisanal Craft",
    "slides.14.description": "The Essence of Bordeaux Traditional Winemaking Philosophy",
    "slides.15.title": "Traditional Winemaking Philosophy Introduction",
    "slides.16.title": "Three Principles of Traditional Winemaking Philosophy",
    "slides.17.title": "Traditional Clarification and Processing Methods",
    "slides.18.title": "The Birth of Liquid Gold",
    "slides.19.title": "Learning Objectives: Sweet Wine Production and Noble Rot",
    "slides.20.title": "Sweet Wine Production and Noble Rot Science",
    "slides.20.subtitle": "Sauternes: The Birth of Liquid Gold",
    "slides.20.description": "Exploring the Winemaking Secrets of the World's Finest Sweet White Wine",
    "slides.21.title": "Sweet Wine Production and Noble Rot Science Introduction",
    "slides.22.title": "Sauternes Winemaking Process: Six Stages of Extreme Precision",
    "slides.23.title": "Case Study: Château d'Yquem's Ultimate Quality Model",
    "slides.24.title": "Knowledge Check: Sweet Wine Production and Noble Rot",
    "slides.25.title": "Sweet Wine Production: The Ultimate Balance of Risk and Reward",
    "slides.25.content": "**Core Insights:**\n\n🍄 **Dual Nature of Noble Rot**: same fungus, different manifestations; requires a \"morning wet + afternoon dry\" microclimate window.\n🛠 **Harvest Strategy**: 6–8 selective harvests amplify labour costs but raise the quality ceiling.\n⚗️ **High-Sugar Fermentation Management**: stress-tolerant yeast cultivation, control volatile acidity, avoid reduction and stuck fermentation.\n🪵 **Oak and Time**: new barrels and extended barrel ageing assist redox buffering, integrating high concentrations of sugar/acid/flavour molecules.\n💰 **Economic Structure**: low yield + high labour intensity + high ageing potential = collectible and investment attributes.\n🌍 **Future Challenges**: climate change eroding stability → requires more precise data/selection technology (optical sorting, AI assessment).",
    "slides.26.title": "Part 2 Complete!",
    "slides.27.title": "L3-5 Part 3A",
    "slides.27.subtitle": "Oak Barrel Science Fundamentals",
    "slides.27.description": "From Forest to Cellar: Understanding the Science of Oak Barrels",
    "slides.28.title": "Oak Barrels: The Soul Companion of Winemaking",
    "slides.28.content": "Oak barrels serve multiple roles as container, flavour agent, micro-oxygenator and structure modifier — a dynamic chemical/physical/microbial reactor. Their influence comes from: chemical extraction (vanillin, lactones, eugenol, furfural, oak tannins), slow micro-oxygenation (promoting anthocyanin stabilisation and tannin polymerisation), and interaction with lees/microorganisms (texture and reductive protection).",
    "slides.29.title": "Learning Objectives: Oak Barrel Science Fundamentals",
    "slides.30.title": "Oak Barrel Science Fundamentals",
    "slides.30.subtitle": "The Science from Forest to Cellar",
    "slides.30.description": "Understanding How Oak Shapes Wine Flavour and Structure",
    "slides.31.title": "Oak Barrel Science Fundamentals Introduction",
    "slides.32.title": "Oak Species: The Origin of Flavour",
    "slides.33.title": "French Oak Region Characteristics Comparison",
    "slides.34.title": "Oak Barrel Manufacturing Craft",
    "slides.34.subtitle": "The Art of Air-Drying and Toasting",
    "slides.34.description": "Exploring the Traditional Craft of Top-Tier Cooperages",
    "slides.35.title": "Oak Barrel Manufacturing Craft Introduction",
    "slides.36.title": "Air-Drying: The Catalyst of Time",
    "slides.37.title": "Toasting: Flavour Sculpting",
    "slides.38.title": "Toasting Temperature and Time: Stage Chemistry",
    "slides.39.title": "Case Study: François Frères Two-Stage Toasting",
    "slides.40.title": "Knowledge Check: Oak Barrel Science Fundamentals",
    "slides.41.title": "Oak Barrel Science: Overall Review",
    "slides.42.title": "Part 3A Complete!",
    "slides.43.title": "L3-5 Part 3B",
    "slides.43.subtitle": "Modern Winemaking Technology and Equipment",
    "slides.43.description": "Technology Revolution: 21st-Century Winemaking Innovation",
    "slides.44.title": "The Digital Revolution in Winemaking Technology",
    "slides.44.content": "21st-century winemaking has entered the era of precision and data-driven approaches: optical / X-ray / AI sorting, precision temperature-controlled fermentation, real-time monitoring, membrane separation and concentration, and smart decision support — all improving consistency and reducing risk.",
    "slides.45.title": "Learning Objectives: Modern Winemaking Technology",
    "slides.46.title": "Modern Sorting Technology",
    "slides.46.subtitle": "Evolution from Manual to AI",
    "slides.46.description": "How Technology Enhances Grape Quality Control",
    "slides.47.title": "Modern Sorting Technology Introduction",
    "slides.48.title": "Evolution of Sorting Technology",
    "slides.48.content": "Manual → Mechanical → Optical → X-Ray → AI multi-modal fusion; core value: improving raw material uniformity + reducing defect risk + stabilising quality foundation.",
    "slides.49.title": "Comprehensive Comparison of Sorting Technologies",
    "slides.50.title": "Case Study: Château Margaux Sorting Upgrade",
    "slides.51.title": "Precision Fermentation Control System",
    "slides.51.subtitle": "From Experience to Data-Driven",
    "slides.51.description": "Modern Fermentation Monitoring and Automation Technology",
    "slides.52.title": "Precision Fermentation Control Introduction",
    "slides.53.title": "The Revolution in Fermentation Control Technology",
    "slides.53.content": "Traditional: manual measurement & passive adjustment; Modern: multi-point sensing + PID/predictive control + automated stirring/pump-over strategy, integrating temperature/extraction/micro-oxygenation into a unified model.",
    "slides.54.title": "Modern Fermentation Monitoring System",
    "slides.55.title": "Post-Processing Technology Innovation",
    "slides.55.subtitle": "Clarification, Stabilisation and Concentration",
    "slides.55.description": "How Modern Technology Enhances Wine Quality",
    "slides.56.title": "Post-Processing Technology Innovation Introduction",
    "slides.57.title": "Modernisation of Post-Processing Technology",
    "slides.57.content": "Goal: Improve stability and purity while preserving terroir and variety expression.\nMembrane separation → Precision; Freeze concentration → Physical selection; RO → Cautious strategic tool.",
    "slides.58.title": "Comprehensive Assessment of Post-Processing Technology",
    "slides.59.title": "Knowledge Check: Modern Winemaking Technology",
    "slides.60.title": "Technology and Tradition: An Integrated Perspective",
    "slides.60.content": "Technology = tool, not style; rational adoption follows: raw material bottleneck → quantifiable benefit → style consistency maintenance → iterative validation.",
    "slides.61.title": "Part 3B Complete!",
}

for key, val in updates.items():
    if key in data:
        data[key] = val
    else:
        print(f"WARNING: key not found: {key}")

f.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
print(f"Done. Updated {len(updates)} keys.")
