import json

path = r"c:\Users\Chungshu\Desktop\教學網站製作20260220\Bordeaux Wine Learning\src\locales\en\lessons\bordeaux\l3-13-part1.json"

with open(path, encoding="utf-8") as f:
    data = json.load(f)

def tr(val, pairs):
    val = val.replace("[ZH] ", "").replace("[ZH]", "")
    for zh, en in pairs:
        val = val.replace(zh, en)
    return val

# ── slides.12.content ─────────────────────────────────────────────────────────
r12 = [
    ("機器學習應用（一）｜預測建模系統",
     "Machine Learning Applications (I) | Predictive Modelling System"),
    ("從歷史數據學習規律 × 同時處理萬個變數 × 做出人腦無法完成的複雜預測",
     "Learning patterns from historical data × processing thousands of variables simultaneously × making complex predictions beyond human capability"),
    ("🍇 產量預測模型", "🍇 Yield Prediction Model"),
    ("📅 多階段預測流程", "📅 Multi-Stage Prediction Pipeline"),
    (">4–5月<", ">Apr–May<"),
    ("花期 × 氣象條件預測產量潛力（誤差25%）",
     "Flowering × weather conditions predict yield potential (error 25%)"),
    (">6–7月<", ">Jun–Jul<"),
    ("轉色期 × 果串數量+管理數據（誤差11%）",
     "Véraison × cluster count + management data (error 11%)"),
    (">8月下<", ">Late Aug<"),
    ("整合遙感數據 × 最終預測（誤差4%）",
     "Integrating remote-sensing data × final prediction (error 4%)"),
    ("<span style=\"color:#276749;font-weight:700\">💡 Château Latour 2025年：</span>",
     "<span style=\"color:#276749;font-weight:700\">💡 Château Latour 2025:</span>"),
    ("最終預測 54噸 ±2噸（8月30日）",
     "Final prediction 54 t ±2 t (30 Aug)"),
    ("實際採收：<span style=\"font-weight:700\">53.2噸</span>",
     "Actual harvest: <span style=\"font-weight:700\">53.2 t</span>"),
    ("<span style=\"color:#c53030;font-weight:700\">→ 預測誤差僅 1.5%！提前2週精準預測</span>",
     "<span style=\"color:#c53030;font-weight:700\">→ Prediction error only 1.5%! Precise forecast 2 weeks early</span>"),
    ("⚡ 算法性能比較", "⚡ Algorithm Performance Comparison"),
    (">算法<", ">Algorithm<"),
    (">推薦<", ">Recommended<"),
    (">線性回歸<", ">Linear Regression<"),
    (">隨機森林<", ">Random Forest<"),
    (">深度神經網絡<", ">Deep Neural Network<"),
    (">⭐推薦<", ">⭐ Recommended<"),
    ("中小規模數據（&lt;10年歷史）XGBoost 表現最佳",
     "For small/medium datasets (&lt;10 years history), XGBoost performs best"),
    ("🦠 病害預測模型", "🦠 Disease Prediction Model"),
    ("🚨 早期預警系統", "🚨 Early Warning System"),
    ("環境模型 × 溫濕度預測發生概率",
     "Environmental model × temperature/humidity predict occurrence probability"),
    ("圖像識別 × 自動識別病斑症狀",
     "Image recognition × automatically identifies disease symptoms"),
    ("傳播模型 × 預測擴散路徑",
     "Spread model × predicts propagation paths"),
    ("風險評估 × 各地塊病害風險",
     "Risk assessment × disease risk by plot"),
    ("<span style=\"color:#c53030;font-weight:700\">💡 2024年6月霜霉病預警：</span>",
     "<span style=\"color:#c53030;font-weight:700\">💡 June 2024 downy mildew warning:</span>"),
    ("AI預測發生概率 <span style=\"font-weight:700\">78%</span> → 提前噴藥（€120/公頃）",
     "AI predicts <span style=\"font-weight:700\">78%</span> probability → preventive spray (€120/ha)"),
    ("鄰近未防守園感染率 35%，本園僅 <span style=\"color:#276749;font-weight:700\">2%</span>",
     "Neighbouring unsprayed vineyard: 35% infection rate; this vineyard: only <span style=\"color:#276749;font-weight:700\">2%</span>"),
    ("<span style=\"color:#c53030;font-weight:700\">→ 避免損失 €2,500/公頃 × ROI 20:1</span>",
     "<span style=\"color:#c53030;font-weight:700\">→ Loss avoided €2,500/ha × ROI 20:1</span>"),
    ("🧠 深度學習應用", "🧠 Deep Learning Applications"),
    ("CNN × 分析葉片/果實影像特徵",
     "CNN × analyses leaf/fruit image features"),
    ("LSTM × 分析時序環境變化模式",
     "LSTM × analyses time-series environmental change patterns"),
    ("注意力機制 × 聚焦關鍵診斷特徵",
     "Attention mechanism × focuses on key diagnostic features"),
    ("遷移學習 × 快速適應新病害",
     "Transfer learning × rapid adaptation to new diseases"),
    ("<span style=\"color:#c53030;font-weight:700\">💡 葡萄病害自動診斷系統：</span>",
     "<span style=\"color:#c53030;font-weight:700\">💡 Automated grape disease diagnosis system:</span>"),
    ("訓練集：50,000張標註葉片 × 10類病害",
     "Training set: 50,000 annotated leaf images × 10 disease types"),
    ("整體準確率：<span style=\"font-weight:700\">94.3%</span>（霜霉病 96.8%）",
     "Overall accuracy: <span style=\"font-weight:700\">94.3%</span> (downy mildew 96.8%)"),
    ("處理速度：每張 0.08秒", "Processing speed: 0.08 s per image"),
    ("<span style=\"color:#c53030;font-weight:700\">→ 診斷時間 1天 ➜ 1分鐘</span>",
     "<span style=\"color:#c53030;font-weight:700\">→ Diagnosis time 1 day ➜ 1 minute</span>"),
    ("<div style=\"opacity:.85\">產量預測誤差（Latour）</div>",
     "<div style=\"opacity:.85\">Yield prediction error (Latour)</div>"),
    ("<div style=\"opacity:.85\">XGBoost 預測精度</div>",
     "<div style=\"opacity:.85\">XGBoost prediction accuracy</div>"),
    ("<div style=\"opacity:.85\">病害識別準確率</div>",
     "<div style=\"opacity:.85\">Disease identification accuracy</div>"),
    ("<div style=\"opacity:.85\">病害預防投資回報</div>",
     "<div style=\"opacity:.85\">Disease prevention ROI</div>"),
]
data["slides.12.content"] = tr(data["slides.12.content"], r12)

# ── slides.13.content ─────────────────────────────────────────────────────────
r13 = [
    ("機器學習應用（二）｜優化決策系統",
     "Machine Learning Applications (II) | Optimisation Decision System"),
    ("預測告訴我們「會發生什麼」× 優化系統告訴我們「應該怎麼做」",
     'Prediction tells us "what will happen" × optimisation tells us "what to do"'),
    ("🌱 資源配置優化", "🌱 Resource Allocation Optimisation"),
    ("💧 精準灌溉優化", "💧 Precision Irrigation Optimisation"),
    ("需水量模型 × 精確計算各發育期",
     "Water demand model × precisely calculates each growth stage"),
    ("水分平衡 × 降雨/蒸散發整合",
     "Water balance × rainfall/evapotranspiration integration"),
    ("適度水分脅迫 × 提高果實品質",
     "Moderate water stress × improves fruit quality"),
    ("排程優化 × 灌溉時間與頻率",
     "Schedule optimisation × irrigation timing and frequency"),
    ("<span style=\"color:#c05621;font-weight:700\">💡 Pessac-Léognan 50公頃：</span>",
     "<span style=\"color:#c05621;font-weight:700\">💡 Pessac-Léognan 50 ha:</span>"),
    ("傳統：5,000m³/季 × 均勻灌溉 × 品質85分",
     "Traditional: 5,000 m³/season × uniform irrigation × quality 85 pts"),
    ("AI優化：<span style=\"font-weight:700\">3,200m³（節水36%）</span> × 品質 <span style=\"color:#276749;font-weight:700\">88分（+3分）</span>",
     "AI-optimised: <span style=\"font-weight:700\">3,200 m³ (36% water saving)</span> × quality <span style=\"color:#276749;font-weight:700\">88 pts (+3)</span>"),
    ("<span style=\"color:#c53030;font-weight:700\">→ 節水€1,800 + 品質提升€25,000/年</span>",
     "<span style=\"color:#c53030;font-weight:700\">→ Water saving €1,800 + quality improvement €25,000/year</span>"),
    ("🌿 變量施肥優化", "🌿 Variable-Rate Fertilisation Optimisation"),
    ("土壤/植物分析 × 優化養分配比",
     "Soil/plant analysis × optimises nutrient ratios"),
    ("最佳施肥時機確定", "Optimal fertilisation timing determination"),
    ("200細分區塊 × 個別化方案",
     "200 sub-blocks × individualised plans"),
    ("最小化環境影響", "Minimise environmental impact"),
    ("<span style=\"color:#c05621;font-weight:700\">💡 Saint-Julien 50公頃：</span>",
     "<span style=\"color:#c05621;font-weight:700\">💡 Saint-Julien 50 ha:</span>"),
    ("北側低肥：15kg N/公頃 × 南側高肥：35kg N/公頃",
     "North low-fertility: 15 kg N/ha × South high-fertility: 35 kg N/ha"),
    ("全園生長勢均勻度提升 <span style=\"font-weight:700\">42%</span>",
     "Overall vineyard vigour uniformity improved by <span style=\"font-weight:700\">42%</span>"),
    ("<span style=\"color:#c53030;font-weight:700\">→ 氮肥總用量減少 28% × 節省€8,500/年</span>",
     "<span style=\"color:#c53030;font-weight:700\">→ Total nitrogen use reduced 28% × saving €8,500/year</span>"),
    ("🏭 釀造工藝優化", "🏭 Winemaking Process Optimisation"),
    ("🌡️ 發酵參數優化", "🌡️ Fermentation Parameter Optimisation"),
    ("每5分鐘測溫度/密度/酵母活性",
     "Measure temp/density/yeast activity every 5 minutes"),
    ("預測未來2小時發酵進程",
     "Predict fermentation progress 2 hours ahead"),
    ("能耗優化 × 節能20–35%", "Energy optimisation × 20–35% savings"),
    ("<span style=\"color:#553c9a;font-weight:700\">💡 Château Palmer（同時發酵30批次）：</span>",
     "<span style=\"color:#553c9a;font-weight:700\">💡 Château Palmer (30 fermentation batches simultaneously):</span>"),
    ("人工控制溫度波動：<span style=\"color:#c53030\">±2.5°C</span>",
     "Manual temperature control fluctuation: <span style=\"color:#c53030\">±2.5°C</span>"),
    ("AI控制溫度波動：<span style=\"color:#276749;font-weight:700\">±0.3°C</span>",
     "AI temperature control fluctuation: <span style=\"color:#276749;font-weight:700\">±0.3°C</span>"),
    ("<span style=\"color:#c53030;font-weight:700\">→ 發酵停滯風險降低85% × 年度品質一致性+35%</span>",
     "<span style=\"color:#c53030;font-weight:700\">→ Fermentation arrest risk reduced 85% × annual quality consistency +35%</span>"),
    ("🛢️ AI調配助手", "🛢️ AI Blending Assistant"),
    ("分析28個地塊化學成分與感官特徵",
     "Analyses chemical composition and sensory characteristics of 28 plots"),
    ("1億+種組合 → 推薦最優10個方案",
     "100 million+ combinations → recommends top 10 blends"),
    ("15年歷史調配數據訓練模型",
     "Model trained on 15 years of historical blending data"),
    ("預測陳年潛力與評分", "Predicts ageing potential and score"),
    ("<span style=\"color:#553c9a;font-weight:700\">💡 Pauillac一級酒莊2024：</span>",
     "<span style=\"color:#553c9a;font-weight:700\">💡 Pauillac first growth 2024:</span>"),
    ("AI推薦：地塊A 38% + 地塊E 25% + 地塊M 20%",
     "AI recommendation: Plot A 38% + Plot E 25% + Plot M 20%"),
    ("酒莊長微調 → A調至40%",
     "Winemaker adjusted → A increased to 40%"),
    ("<span style=\"color:#c53030;font-weight:700\">→ 實際評分：96分（Parker）✓</span>",
     "<span style=\"color:#c53030;font-weight:700\">→ Actual score: 96 pts (Parker) ✓</span>"),
    ("<div style=\"font-size:.78rem;text-align:center;margin-bottom:8px;opacity:.9;font-weight:700\">數據驅動決策完整閉環</div>",
     "<div style=\"font-size:.78rem;text-align:center;margin-bottom:8px;opacity:.9;font-weight:700\">Complete Data-Driven Decision Loop</div>"),
    (">收集<", ">Collect<"),
    (">處理<", ">Process<"),
    (">分析<", ">Analyse<"),
    (">預測<", ">Predict<"),
    (">優化<", ">Optimise<"),
    (">執行<", ">Execute<"),
    (">反饋改進 ↺<", ">Feedback &amp; Improve ↺<"),
    ("<div style=\"opacity:.8\">節水（Pessac-Léognan）</div>",
     "<div style=\"opacity:.8\">water saving (Pessac-Léognan)</div>"),
    ("<div style=\"opacity:.8\">節肥（Saint-Julien）</div>",
     "<div style=\"opacity:.8\">fertiliser saving (Saint-Julien)</div>"),
    ("<div style=\"opacity:.8\">AI溫控精度</div>",
     "<div style=\"opacity:.8\">AI temp control precision</div>"),
    ("<div style=\"opacity:.8\">AI調配 Parker評分</div>",
     "<div style=\"opacity:.8\">AI blending Parker score</div>"),
]
data["slides.13.content"] = tr(data["slides.13.content"], r13)

with open(path, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Saved l3-13-part1.json (slides.12 + slides.13 updated)")
