import json, pathlib

f = pathlib.Path("src/locales/en/lessons/bordeaux/l4-3.json")
data = json.loads(f.read_text(encoding="utf-8"))

# All short text keys
data["slides.0.title"] = "Learning Objectives"
data["slides.1.title"] = "Chapter 1"
data["slides.1.subtitle"] = "Wood Origins"
data["slides.2.title"] = "Chapter 1: Wood Science and Origin Design"
data["slides.2.highlights.0.title"] = "Origin Differences"
data["slides.2.highlights.0.content"] = "French, American and Eastern European oak differ greatly in grain and extraction rhythm."
data["slides.2.highlights.1.title"] = "Drying Traceability"
data["slides.2.highlights.1.content"] = "Moisture content and microbial monitoring determine subsequent flavour purity."
data["slides.2.highlights.2.title"] = "Supply Risk"
data["slides.2.highlights.2.content"] = "Price, certification and logistics must be incorporated into long-term contract management."
data["slides.3.title"] = "Chapter 2"
data["slides.3.subtitle"] = "Toasting"
data["slides.4.title"] = "Chapter 2: Toasting Curves and Surface Profiling"
data["slides.4.highlights.0.title"] = "Pyrolysis Layers"
data["slides.4.highlights.0.content"] = "Hemicellulose → lignin → fatty acids release different aromas in sequence."
data["slides.4.highlights.1.title"] = "Curve Monitoring"
data["slides.4.highlights.1.content"] = "Use thermocouples and infrared to monitor core barrel stave temperature."
data["slides.4.highlights.2.title"] = "Interactive Configuration"
data["slides.4.highlights.2.content"] = "Light/medium/heavy toast indicators allow real-time comparison of aroma and structure."
data["slides.5.title"] = "Chapter 3"
data["slides.5.subtitle"] = "Materials"
data["slides.6.title"] = "Chapter 3: Container Materials and Micro-Oxygenation Management"
data["slides.6.highlights.0.title"] = "Oxygen Permeability Reference"
data["slides.6.highlights.0.content"] = "Defines each container's oxygen delivery capacity in mg/L·month."
data["slides.6.highlights.1.title"] = "Thermal Inertia Advantage"
data["slides.6.highlights.1.content"] = "Concrete and amphora can smooth temperature fluctuations."
data["slides.6.highlights.2.title"] = "Container Chain"
data["slides.6.highlights.2.content"] = "Link multiple containers in staged ageing to modulate aroma and structure."
data["slides.7.title"] = "Chapter 4"
data["slides.7.subtitle"] = "Management"
data["slides.8.title"] = "Chapter 4: Barrel Age Management and Hygiene Control"
data["slides.8.highlights.0.title"] = "Barrel Age KPI"
data["slides.8.highlights.0.content"] = "Vanillin, tannin and sensory evaluation jointly determine barrel age category."
data["slides.8.highlights.1.title"] = "Three-Stage Hygiene"
data["slides.8.highlights.1.content"] = "Hot water → oxidant → drying monitoring, blocking microbial sources."
data["slides.8.highlights.2.title"] = "Life Extension Strategy"
data["slides.8.highlights.2.content"] = "Scraping plus re-toasting and UV/O₃ treatment can extend service life."
data["slides.9.title"] = "Chapter 5"
data["slides.9.subtitle"] = "Strategy"
data["slides.10.title"] = "Chapter 5: Multi-Container Synergy and Investment Decisions"
data["slides.10.highlights.0.title"] = "Investment Matrix"
data["slides.10.highlights.0.content"] = "CapEx/OpEx/lifespan at a glance to assist capital planning."
data["slides.10.highlights.1.title"] = "Scenario Configuration"
data["slides.10.highlights.1.content"] = "Three container scenarios cover classic, hybrid and innovation lines."
data["slides.10.highlights.2.title"] = "Performance Dashboard"
data["slides.10.highlights.2.content"] = "Three-dimensional KPI tracking across sensory, financial and sustainability dimensions."
data["slides.11.title"] = "Course Summary"
data["slides.12.title"] = "Post-Course Quiz"

f.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
print("Done. Updated 36 short text keys.")
